In [1]:
from splinter import Browser
from bs4 import BeautifulSoup
import requests
import pymongo
import pandas as pd
from urllib.parse import urlparse

In [2]:
#Mac Users
# executable_path = {'executable_path': '/usr/local/bin/chromedriver'}
# browser = Browser('chrome', **executable_path, headless=False)

# Windows Users
executable_path = {'executable_path': 'chromedriver.exe'}
browser = Browser('chrome', **executable_path, headless=False)

In [3]:
url = 'https://www.bjs.gov/index.cfm?ty=nps'

browser.visit(url)

In [4]:
html = browser.html
soup = BeautifulSoup(html,'html.parser')

In [17]:
print(html)

<html lang="en"><head><script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js"></script><script async="" src="//www.googletagmanager.com/gtm.js?id=GTM-WTVZN7"></script><script async="" src="https://www.google-analytics.com/analytics.js"></script><script type="text/javascript">/* <![CDATA[ */_cf_loadingtexthtml="<img alt=' ' src='/CFIDE/scripts/ajax/resources/cf/images/loading.gif'/>";
_cf_contextpath="";
_cf_ajaxscriptsrc="/CFIDE/scripts/ajax";
_cf_jsonprefix='//';
_cf_websocket_port=8575;
_cf_flash_policy_port=1243;
_cf_clientid='39947A2C709499599B04BF84740A410A';/* ]]> */</script><script type="text/javascript" src="/CFIDE/scripts/ajax/messages/cfmessage.js"></script>
<script type="text/javascript" src="/CFIDE/scripts/ajax/package/cfajax.js"></script>
<script type="text/javascript" src="/CFIDE/scripts/cfform.js"></script>
<script type="text/javascript" src="/CFIDE/scripts/masks.js"></script>
<script type="text/javascript" src="/CFIDE/scripts/cfformhistory.js"></script>

<!--[if IE 7]>   <script src="/inc/IE9.js"></script><html class="ie7"> <![endif]-->

<script language="javascript" id="_fed_an_ua_tag" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=DOJ&amp;subagency=BJS"></script>





<title>Bureau of Justice Statistics (BJS) - Data Analysis Tools - Corrections Statistical Analysis Tool (CSAT) - Prisoners</title>

    <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
    <meta name="title" content="Bureau of Justice Statistics Home page">
    <meta name="description" content="Statistics about - Crime and victims, Drugs and crime, Criminal offenders, The justice system in the United States, Law enforcement, Prosecution, Courts and sentencing, Corrections, Justice expenditure and employment.">
    <meta name="language" scheme="ISO639" content="en-us">
    <meta name="date.created" content="2008-12-03">
    <meta name="keywords" content="statistics, crime, victims, violence, drugs, criminals, offenders, justice system, law enforcement, prosecution, courts, sentencing, corrections, prisons, jails, probation, parole, inmates, Federal, State, local, criminal records">
<!--
BEGIN FILE /COMMON/HEADERBODY.CFM
--->






<link href="/inc/leftnav.css" rel="stylesheet" type="text/css" media="screen">

<script language="JavaScript" type="text/javascript">
	version=0;
	if (navigator.appVersion.indexOf("MSIE")!=-1)
	{
		temp=navigator.appVersion.split("MSIE");
		version=parseFloat(temp[1]);
	}
	if (version>=5.5)
	{
		document.write('<link href="/inc/styles.css" rel="stylesheet" type="text/css" media="screen">');
	}
	else
	{
		document.write('<link href="/inc/styles_all_brws.css" rel="stylesheet" type="text/css" media="screen">');
	}

	function jscheck()
	{
	  //alert(document.forms['search_mast_form'].txtKeyword_quick.value);
	   var varKeyWord = document.forms[0].txtKeyword_quick.value.replace( /^\s*/, "" ).replace( /\s*$/, "" );
	   if (varKeyWord == '' || varKeyWord.length < 2 || varKeyWord == 'Enter keywords')
	   {
		  alert("Please enter at least two characters in the keyword field!");
			return false;
	   }
	}


	function gsacheck()
	{
	  //alert(document.forms['search_mast_form'].txtKeyword_quick.value);
	   var varKeyWord = document.forms[0].q.value.replace( /^\s*/, "" ).replace( /\s*$/, "" );

		/*
	   alert('The BJS search engine is currently down.  Please search our site by going to google.com and prefixing your search terms with "site:bjs.gov" to limit your search to only our website.  We apologize for the inconvenience.');
	   return false;
	   */

	   if (varKeyWord == '' || varKeyWord.length < 2 || varKeyWord == 'Enter keywords')
	   {
		  	alert("Please enter at least two characters in the keyword field!");
			return false;
	   }
	}



</script><link href="/inc/styles_all_brws.css" rel="stylesheet" type="text/css" media="screen">



<noscript>
	<link href="/inc/styles.css" rel="stylesheet" type="text/css" media="screen">
</noscript>

<link href="/inc/print.css" rel="stylesheet" type="text/css" media="print">
<script language="JavaScript" type="text/javascript" src="/inc/topnav.js"></script>
<script language="JavaScript" type="text/javascript" src="/inc/leftnavfly.js"></script>


<script language="JavaScript" type="text/javascript" src="/inc/jquery-1.2.2.pack.js"></script>
<script language="JavaScript" type="text/javascript" src="/inc/ddaccordion.js"></script>
<script language="JavaScript" type="text/javascript" src="/inc/tabs.js"></script>
<script language="JavaScript" type="text/javascript" src="/inc/date.js"></script>
<script language="JavaScript" type="text/javascript" src="/inc/dw_event.js"></script>
<script language="JavaScript" type="text/javascript" src="/inc/dw_cookies.js"></script>
<script language="JavaScript" type="text/javascript" src="/inc/dw_sizerdx.js"></script>


<script type="text/javascript" src="/inc/anylinkmenu.js"></script>

<!-- Joseph (01/20/2010) publication index -->
<script language="JavaScript" type="text/javascript" src="/inc/browser_detect.js"></script>
<script language="JavaScript" type="text/javascript" src="/inc/pub_index.js"></script>

<script language="JavaScript" type="text/javascript">dw_Event.add(window, 'load', dw_fontSizerDX.init);</script>


<script src="/inc/SpryTabbedPanels.js" type="text/javascript"></script>
<script src="/inc/SpryAccordion.js" type="text/javascript"></script>
<script src="/inc/xpath.js" type="text/javascript"></script>
<script src="/inc/SpryData.js" type="text/javascript"></script>



	<link href="/inc/dataanal_styles.css" rel="stylesheet" type="text/css">


<!--  OJP Banner -->
<link rel="stylesheet" type="text/css" href="/inc/ojpbanner.css">

<!-- Joseph (01/11/2010) search results sorting and search links -->
<link href="/inc/tablesorter.css" rel="stylesheet" type="text/css">





<script type="text/javascript">/* <![CDATA[ */
	ColdFusion.Ajax.importTag('CFAJAXPROXY');
/* ]]> */</script>
<script type="text/javascript">
<!--
    _CF_checkfrmSearchGoogle = function(_CF_this)
    {
        //reset on submit
        _CF_error_exists = false;
        _CF_error_messages = new Array();
        _CF_error_fields = new Object();
        _CF_FirstErrorField = null;


        //display error messages and return success
        if( _CF_error_exists )
        {
            if( _CF_error_messages.length > 0 )
            {
                // show alert() message
                _CF_onErrorAlert(_CF_error_messages);
                // set focus to first form error, if the field supports js focus().
                if( _CF_this[_CF_FirstErrorField].type == "text" )
                { _CF_this[_CF_FirstErrorField].focus(); }

            }
            return false;
        }else {
            return true;
        }
    }
//-->
</script>

<script type="text/javascript">/* <![CDATA[ */
	ColdFusion.Ajax.importTag('CFFORM');
/* ]]> */</script>

<script type="text/javascript">/* <![CDATA[ */
	ColdFusion.Ajax.importTag('CFDIV');
/* ]]> */</script>
<script src="//gateway.answerscloud.com/bjs-gov/production/gateway.min.js" type="text/javascript" async="true" data-vendor="acs" data-role="gateway"></script></head>

<body onload="showPanel(document.getElementById('tab1'), 'panel1');"><span></span>
  <!-- Google Tag Manager -->
<noscript><iframe src="//www.googletagmanager.com/ns.html?id=GTM-WTVZN7"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WTVZN7');</script>
<!-- End Google Tag Manager -->









<!--googleoff: index-->
<!--googleoff: snippet-->




<div id="main_heading_print">BJS: Bureau of Justice Statistics<br><br></div>

<span class="ojpbannerarea"><script type="text/javascript" src="/inc/bjs-ojpbanner.js"></script><div id="ojpmain5208"><div id="col15208"><a href="https://ojp.gov"><img src="https://ojp.gov/ojpbanner/1_ojptab_01.gif" width="354" height="36" alt="Office of Justice Programs" border="0"></a></div></div><div id="ojp_container"><div id="row25208"><a href="https://ojp.gov"><img src="https://ojp.gov/ojpbanner/1_ojptab_03_rght_bk_gd_url.png" width="255" height="18" border="0" alt="ojp.gov"></a><img src="https://ojp.gov/ojpbanner/1_ojptab_arrow_off.gif" width="17" height="18" id="tabgraphic" onclick="toggle_visibility('tab_content2'); toggle_visibility('selGenSearch'); swap_button('tabgraphic');"></div><div id="lrow25208"></div><div id="tab_content2" style="display: none;"><table border="0" cellpadding="0" cellspacing="0" style="background-image: url(https://ojp.gov/ojpbanner/1_ojptab_04_open_cell.gif); position: absolute; z-index: 9999;"><tbody><tr><td><script type="text/javascript" src="https://ojp.gov/ojpbanner/ojpbanner-content.js"></script><ul class="style8glide5208"><li><a href="https://www.ojp.gov">OJP Homepage</a></li><li><a href="https://www.ojp.gov/training/training.htm">Training &amp; TA</a></li><li><a href="https://www.ojp.gov/funding/funding.htm">OJP Funding</a></li><li><a href="https://www.ojp.gov/newsroom/newsroom.htm">Newsroom</a></li></ul><script type="text/javascript" src="/inc/ojpbanner-close.js"></script><a href="" onclick="toggle_visibility('tab_content2'); toggle_visibility('selGenSearch'); javascript: swap_button('tabgraphic');" style="float: right; padding: 0 0 0px 6px; text-align: center; width: 70px; font-weight: bold; font-size: 12px;">[x]</a></td></tr><tr><td style=""><img src="https://ojp.gov/ojpbanner/1_ojptab_04_open_bttm.png" width="273" height="13" alt="border"></td></tr></tbody></table></div></div>
</span>

<a name="top"></a>

<div id="container_main">
<div id="main_mast"><!-- skip navigation link for main mast --><a href="#skipnav1" title="skip navigation for main mast"><img src="/images/clear.gif" width="1" height="1" alt="clear image" class="skipnav"></a><div id="main_mast_top2_l"><div id="main_mast_top2_r">
<table border="0" cellpadding="0" cellspacing="0">
<tbody><tr>
<td align="right" height="13px;">
<a href="/" class="main_mast_top2_r_link">Home</a> &nbsp;|&nbsp; <a href="/index.cfm?ty=abu" class="main_mast_top2_r_link">About Us</a> &nbsp;|&nbsp; <a href="/index.cfm?ty=contactus" class="main_mast_top2_r_link">Contact Us</a> &nbsp;|&nbsp; <a href="/help/index.cfm" class="main_mast_top2_r_link">Help</a> &nbsp;|&nbsp; <a href="/index.cfm?ty=atoz" class="main_mast_top2_r_link">A-Z Topic List</a>

</td>
</tr>





<tr><td>







<form name="frmSearchGoogle" id="frmSearchGoogle" action="/search/index.cfm" method="GET" onsubmit="return _CF_checkfrmSearchGoogle(this)">





<table border="0" cellpadding="0" cellspacing="0" id="search_mast_table" align="right">
<tbody><tr>
<td align="left" valign="bottom">


<input type="text" name="q" title="q" size="100" maxlength="256" class="search_mast_input" style="width:174px; height:15px;" value="Enter keywords" autocomplete="off" onfocus="if (this.value=='Enter keywords') {this.value='';} ">



</td>
<td align="left" valign="bottom">













</td>
<td align="right" valign="bottom" width="26">
  <input name="Go" type="image" src="/images/1_go_bttn.gif" width="22" height="21" alt="Go" class="gobutton" border="0" vspace="0" hspace="6" onclick="return gsacheck()">


</td>
<td class="advancedsearchcell">&nbsp;<br>&nbsp;</td>
</tr>
</tbody></table>


</form>










</td></tr></tbody></table></div>
<a href="/"><img src="/images/n_1_main_01.gif" width="533" height="76" alt="Bureau of Justice Statistics (BJS)" border="0" vspace="0" hspace="0"></a></div></div>

    <div id="nav_mast">
        <div id="nav_mast_inner"><div id="sizer" style="float: right; display: block;">
                <a href="/index.cfm?ty=rss" class="tab"><img id="Img2" src="/images/rss_icon.jpg" alt="RSS" border="0" name="image2" class="print_img"></a>
		&nbsp;
        <a href="#" onclick="window.print()" title="Printer-Friendly"><img src="/images/print_icon.gif" width="15" height="12" alt="Printer-Friendly" border="0" class="print_img"></a>&nbsp;<a class="box_right_print" href="#" onclick="window.print()" title="Printer-Friendly">Print</a>&nbsp;&nbsp;<a class="reset box_right_print" href="#" title="Click for default font">Text Size:</a>&nbsp;[<a class="decrease box_right_print" href="#" title="Click for small font">-</a>]&nbsp;[<a class="increase box_right_print" href="#" title="Click for large font">+</a>]</div><div id="bannerMenu">
                <ul>

                <li class="first" title="Home"><a href="/" class="top2">Home</a></li>

                <li class="first" id="topicLink" title="Topics"><a href="#" class="top2">Topics</a>

                <ul style="width:900px; margin: 0px 0 0 -35px;">
                	<li target="_top" class="topnavdd" style="width:900px;border-bottom: 1px solid #999999;">


                        <table width="100%" id="tblMegamenu">
                         <tbody><tr style="vertical-align:top;">
                        <td width="250">

  <table id="topicTable" name="topicTable">
  	<tbody><tr>
    	<td style="padding:5px"><a href="/index.cfm?ty=tp&amp;tid=1">
        	<span class="DIN black" style="font-size:11px;color:#2767AF;">Corrections</span></a>
        </td>
    </tr>


                  <tr>
                   <td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
                        <a href="/index.cfm?ty=tp&amp;tid=18" style="font-weight:normal; font-size:10px; color: #000000;">Capital Punishment</a></td>
                  </tr>
                  <tr>
                       <td height="1px" style="background-color:#ccc"></td>
                  </tr>

                  <tr>
                   <td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
                        <a href="/index.cfm?ty=tp&amp;tid=15" style="font-weight:normal; font-size:10px; color: #000000;">Community Corrections (Probation and Parole)</a></td>
                  </tr>
                  <tr>
                       <td height="1px" style="background-color:#ccc"></td>
                  </tr>

                  <tr>
                   <td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
                        <a href="/index.cfm?ty=tp&amp;tid=16" style="font-weight:normal; font-size:10px; color: #000000;">Expenditures/Employment</a></td>
                  </tr>
                  <tr>
                       <td height="1px" style="background-color:#ccc"></td>
                  </tr>

                  <tr>
                   <td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
                        <a href="/index.cfm?ty=tp&amp;tid=12" style="font-weight:normal; font-size:10px; color: #000000;">Local jail inmates and jail facilities</a></td>
                  </tr>
                  <tr>
                       <td height="1px" style="background-color:#ccc"></td>
                  </tr>

                  <tr>
                   <td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
                        <a href="/index.cfm?ty=tp&amp;tid=19" style="font-weight:normal; font-size:10px; color: #000000;">Mortality in Correctional Institutions (MCI) (Formerly Deaths in Custody Reporting Program (DCRP))</a></td>
                  </tr>
                  <tr>
                       <td height="1px" style="background-color:#ccc"></td>
                  </tr>

                  <tr>
                   <td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
                        <a href="/index.cfm?ty=tp&amp;tid=20" style="font-weight:normal; font-size:10px; color: #000000;">Prison Rape Elimination Act (Sexual Victimization in Correctional Facilities)
</a></td>
                  </tr>
                  <tr>
                       <td height="1px" style="background-color:#ccc"></td>
                  </tr>

                  <tr>
                   <td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
                        <a href="/index.cfm?ty=tp&amp;tid=17" style="font-weight:normal; font-size:10px; color: #000000;">Recidivism</a></td>
                  </tr>
                  <tr>
                       <td height="1px" style="background-color:#ccc"></td>
                  </tr>

                  <tr>
                   <td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
                        <a href="/index.cfm?ty=tp&amp;tid=14" style="font-weight:normal; font-size:10px; color: #000000;">Special populations</a></td>
                  </tr>
                  <tr>
                       <td height="1px" style="background-color:#ccc"></td>
                  </tr>

                  <tr>
                   <td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
                        <a href="/index.cfm?ty=tp&amp;tid=13" style="font-weight:normal; font-size:10px; color: #000000;">State and federal prisoners and prison facilities</a></td>
                  </tr>
                  <tr>
                       <td height="1px" style="background-color:#ccc"></td>
                  </tr>

                  <tr>
                   <td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
                        <a href="/index.cfm?ty=tp&amp;tid=11" style="font-weight:normal; font-size:10px; color: #000000;">Total correctional population</a></td>
                  </tr>
                  <tr>
                       <td height="1px" style="background-color:#ccc"></td>
                  </tr>

    </tbody></table>

  <table id="topicTable" name="topicTable">
  	<tbody><tr>
    	<td style="padding:5px"><a href="/index.cfm?ty=tp&amp;tid=6">
        	<span class="DIN black" style="font-size:11px;color:#2767AF;">Federal</span></a>
        </td>
    </tr>


                  <tr>
                   <td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
                        <a href="/index.cfm?ty=tp&amp;tid=65" style="font-weight:normal; font-size:10px; color: #000000;">Corrections</a></td>
                  </tr>
                  <tr>
                       <td height="1px" style="background-color:#ccc"></td>
                  </tr>

                  <tr>
                   <td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
                        <a href="/index.cfm?ty=tp&amp;tid=64" style="font-weight:normal; font-size:10px; color: #000000;">Courts</a></td>
                  </tr>
                  <tr>
                       <td height="1px" style="background-color:#ccc"></td>
                  </tr>

                  <tr>
                   <td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
                        <a href="/index.cfm?ty=tp&amp;tid=62" style="font-weight:normal; font-size:10px; color: #000000;">Law Enforcement</a></td>
                  </tr>
                  <tr>
                       <td height="1px" style="background-color:#ccc"></td>
                  </tr>

                  <tr>
                   <td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
                        <a href="/index.cfm?ty=tp&amp;tid=63" style="font-weight:normal; font-size:10px; color: #000000;">Prosecution</a></td>
                  </tr>
                  <tr>
                       <td height="1px" style="background-color:#ccc"></td>
                  </tr>

    </tbody></table>

                        </td>
                        <td width="200">

  <table id="topicTable" name="topicTable">
  	<tbody><tr>
    	<td style="padding:5px"><a href="/index.cfm?ty=tp&amp;tid=2">
        	<span class="DIN black" style="font-size:11px;color:#2767AF;">Courts</span></a>
        </td>
    </tr>


                  <tr>

In [18]:
print(soup)

<html lang="en"><head><script async="" src="https://www.google-analytics.com/analytics.js" type="text/javascript"></script><script async="" src="//www.googletagmanager.com/gtm.js?id=GTM-WTVZN7"></script><script async="" src="https://www.google-analytics.com/analytics.js"></script><script type="text/javascript">/* <![CDATA[ */_cf_loadingtexthtml="<img alt=' ' src='/CFIDE/scripts/ajax/resources/cf/images/loading.gif'/>";
_cf_contextpath="";
_cf_ajaxscriptsrc="/CFIDE/scripts/ajax";
_cf_jsonprefix='//';
_cf_websocket_port=8575;
_cf_flash_policy_port=1243;
_cf_clientid='39947A2C709499599B04BF84740A410A';/* ]]> */</script><script src="/CFIDE/scripts/ajax/messages/cfmessage.js" type="text/javascript"></script>
<script src="/CFIDE/scripts/ajax/package/cfajax.js" type="text/javascript"></script>
<script src="/CFIDE/scripts/cfform.js" type="text/javascript"></script>
<script src="/CFIDE/scripts/masks.js" type="text/javascript"></script>
<script src="/CFIDE/scripts/cfformhistory.js" type="text/javascript"></script>
<!--[if IE 7]>   <script src="/inc/IE9.js"></script><html class="ie7"> <![endif]-->
<script id="_fed_an_ua_tag" language="javascript" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=DOJ&amp;subagency=BJS"></script>
<title>Bureau of Justice Statistics (BJS) - Data Analysis Tools - Corrections Statistical Analysis Tool (CSAT) - Prisoners</title>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
<meta content="Bureau of Justice Statistics Home page" name="title"/>
<meta content="Statistics about - Crime and victims, Drugs and crime, Criminal offenders, The justice system in the United States, Law enforcement, Prosecution, Courts and sentencing, Corrections, Justice expenditure and employment." name="description"/>
<meta content="en-us" name="language" scheme="ISO639"/>
<meta content="2008-12-03" name="date.created"/>
<meta content="statistics, crime, victims, violence, drugs, criminals, offenders, justice system, law enforcement, prosecution, courts, sentencing, corrections, prisons, jails, probation, parole, inmates, Federal, State, local, criminal records" name="keywords"/>
<!--
BEGIN FILE /COMMON/HEADERBODY.CFM
--->
<link href="/inc/leftnav.css" media="screen" rel="stylesheet" type="text/css"/>
<script language="JavaScript" type="text/javascript">
	version=0;
	if (navigator.appVersion.indexOf("MSIE")!=-1)
	{
		temp=navigator.appVersion.split("MSIE");
		version=parseFloat(temp[1]);
	}
	if (version>=5.5)
	{
		document.write('<link href="/inc/styles.css" rel="stylesheet" type="text/css" media="screen">');
	}
	else
	{
		document.write('<link href="/inc/styles_all_brws.css" rel="stylesheet" type="text/css" media="screen">');
	}

	function jscheck()
	{
	  //alert(document.forms['search_mast_form'].txtKeyword_quick.value);
	   var varKeyWord = document.forms[0].txtKeyword_quick.value.replace( /^\s*/, "" ).replace( /\s*$/, "" );
	   if (varKeyWord == '' || varKeyWord.length < 2 || varKeyWord == 'Enter keywords')
	   {
		  alert("Please enter at least two characters in the keyword field!");
			return false;
	   }
	}


	function gsacheck()
	{
	  //alert(document.forms['search_mast_form'].txtKeyword_quick.value);
	   var varKeyWord = document.forms[0].q.value.replace( /^\s*/, "" ).replace( /\s*$/, "" );

		/*
	   alert('The BJS search engine is currently down.  Please search our site by going to google.com and prefixing your search terms with "site:bjs.gov" to limit your search to only our website.  We apologize for the inconvenience.');
	   return false;
	   */

	   if (varKeyWord == '' || varKeyWord.length < 2 || varKeyWord == 'Enter keywords')
	   {
		  	alert("Please enter at least two characters in the keyword field!");
			return false;
	   }
	}



</script><link href="/inc/styles_all_brws.css" media="screen" rel="stylesheet" type="text/css"/>
<noscript>
<link href="/inc/styles.css" media="screen" rel="stylesheet" type="text/css"/>
</noscript>
<link href="/inc/print.css" media="print" rel="stylesheet" type="text/css"/>
<script language="JavaScript" src="/inc/topnav.js" type="text/javascript"></script>
<script language="JavaScript" src="/inc/leftnavfly.js" type="text/javascript"></script>
<script language="JavaScript" src="/inc/jquery-1.2.2.pack.js" type="text/javascript"></script>
<script language="JavaScript" src="/inc/ddaccordion.js" type="text/javascript"></script>
<script language="JavaScript" src="/inc/tabs.js" type="text/javascript"></script>
<script language="JavaScript" src="/inc/date.js" type="text/javascript"></script>
<script language="JavaScript" src="/inc/dw_event.js" type="text/javascript"></script>
<script language="JavaScript" src="/inc/dw_cookies.js" type="text/javascript"></script>
<script language="JavaScript" src="/inc/dw_sizerdx.js" type="text/javascript"></script>
<script src="/inc/anylinkmenu.js" type="text/javascript"></script>
<!-- Joseph (01/20/2010) publication index -->
<script language="JavaScript" src="/inc/browser_detect.js" type="text/javascript"></script>
<script language="JavaScript" src="/inc/pub_index.js" type="text/javascript"></script>
<script language="JavaScript" type="text/javascript">dw_Event.add(window, 'load', dw_fontSizerDX.init);</script>
<script src="/inc/SpryTabbedPanels.js" type="text/javascript"></script>
<script src="/inc/SpryAccordion.js" type="text/javascript"></script>
<script src="/inc/xpath.js" type="text/javascript"></script>
<script src="/inc/SpryData.js" type="text/javascript"></script>
<link href="/inc/dataanal_styles.css" rel="stylesheet" type="text/css"/>
<!--  OJP Banner -->
<link href="/inc/ojpbanner.css" rel="stylesheet" type="text/css"/>
<!-- Joseph (01/11/2010) search results sorting and search links -->
<link href="/inc/tablesorter.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript">/* <![CDATA[ */
	ColdFusion.Ajax.importTag('CFAJAXPROXY');
/* ]]> */</script>
<script type="text/javascript">
<!--
    _CF_checkfrmSearchGoogle = function(_CF_this)
    {
        //reset on submit
        _CF_error_exists = false;
        _CF_error_messages = new Array();
        _CF_error_fields = new Object();
        _CF_FirstErrorField = null;


        //display error messages and return success
        if( _CF_error_exists )
        {
            if( _CF_error_messages.length > 0 )
            {
                // show alert() message
                _CF_onErrorAlert(_CF_error_messages);
                // set focus to first form error, if the field supports js focus().
                if( _CF_this[_CF_FirstErrorField].type == "text" )
                { _CF_this[_CF_FirstErrorField].focus(); }

            }
            return false;
        }else {
            return true;
        }
    }
//-->
</script>
<script type="text/javascript">/* <![CDATA[ */
	ColdFusion.Ajax.importTag('CFFORM');
/* ]]> */</script>
<script type="text/javascript">/* <![CDATA[ */
	ColdFusion.Ajax.importTag('CFDIV');
/* ]]> */</script>
<script async="true" data-role="gateway" data-vendor="acs" src="//gateway.answerscloud.com/bjs-gov/production/gateway.min.js" type="text/javascript"></script></head>
<body onload="showPanel(document.getElementById('tab1'), 'panel1');"><span></span>
<!-- Google Tag Manager -->
<noscript><iframe height="0" src="//www.googletagmanager.com/ns.html?id=GTM-WTVZN7" style="display:none;visibility:hidden" width="0"></iframe></noscript>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-WTVZN7');</script>
<!-- End Google Tag Manager -->
<!--googleoff: index-->
<!--googleoff: snippet-->
<div id="main_heading_print">BJS: Bureau of Justice Statistics<br/><br/></div>
<span class="ojpbannerarea"><script src="/inc/bjs-ojpbanner.js" type="text/javascript"></script><div id="ojpmain5208"><div id="col15208"><a href="https://ojp.gov"><img alt="Office of Justice Programs" border="0" height="36" src="https://ojp.gov/ojpbanner/1_ojptab_01.gif" width="354"/></a></div></div><div id="ojp_container"><div id="row25208"><a href="https://ojp.gov"><img alt="ojp.gov" border="0" height="18" src="https://ojp.gov/ojpbanner/1_ojptab_03_rght_bk_gd_url.png" width="255"/></a><img height="18" id="tabgraphic" onclick="toggle_visibility('tab_content2'); toggle_visibility('selGenSearch'); swap_button('tabgraphic');" src="https://ojp.gov/ojpbanner/1_ojptab_arrow_off.gif" width="17"/></div><div id="lrow25208"></div><div id="tab_content2" style="display: none;"><table border="0" cellpadding="0" cellspacing="0" style="background-image: url(https://ojp.gov/ojpbanner/1_ojptab_04_open_cell.gif); position: absolute; z-index: 9999;"><tbody><tr><td><script src="https://ojp.gov/ojpbanner/ojpbanner-content.js" type="text/javascript"></script><ul class="style8glide5208"><li><a href="https://www.ojp.gov">OJP Homepage</a></li><li><a href="https://www.ojp.gov/training/training.htm">Training &amp; TA</a></li><li><a href="https://www.ojp.gov/funding/funding.htm">OJP Funding</a></li><li><a href="https://www.ojp.gov/newsroom/newsroom.htm">Newsroom</a></li></ul><script src="/inc/ojpbanner-close.js" type="text/javascript"></script><a href="" onclick="toggle_visibility('tab_content2'); toggle_visibility('selGenSearch'); javascript: swap_button('tabgraphic');" style="float: right; padding: 0 0 0px 6px; text-align: center; width: 70px; font-weight: bold; font-size: 12px;">[x]</a></td></tr><tr><td style=""><img alt="border" height="13" src="https://ojp.gov/ojpbanner/1_ojptab_04_open_bttm.png" width="273"/></td></tr></tbody></table></div></div>
</span>
<a name="top"></a>
<div id="container_main">
<div id="main_mast"><!-- skip navigation link for main mast --><a href="#skipnav1" title="skip navigation for main mast"><img alt="clear image" class="skipnav" height="1" src="/images/clear.gif" width="1"/></a><div id="main_mast_top2_l"><div id="main_mast_top2_r">
<table border="0" cellpadding="0" cellspacing="0">
<tbody><tr>
<td align="right" height="13px;">
<a class="main_mast_top2_r_link" href="/">Home</a>  |  <a class="main_mast_top2_r_link" href="/index.cfm?ty=abu">About Us</a>  |  <a class="main_mast_top2_r_link" href="/index.cfm?ty=contactus">Contact Us</a>  |  <a class="main_mast_top2_r_link" href="/help/index.cfm">Help</a>  |  <a class="main_mast_top2_r_link" href="/index.cfm?ty=atoz">A-Z Topic List</a>
</td>
</tr>
<tr><td>
<form action="/search/index.cfm" id="frmSearchGoogle" method="GET" name="frmSearchGoogle" onsubmit="return _CF_checkfrmSearchGoogle(this)">
<table align="right" border="0" cellpadding="0" cellspacing="0" id="search_mast_table">
<tbody><tr>
<td align="left" valign="bottom">
<input autocomplete="off" class="search_mast_input" maxlength="256" name="q" onfocus="if (this.value=='Enter keywords') {this.value='';} " size="100" style="width:174px; height:15px;" title="q" type="text" value="Enter keywords"/>
</td>
<td align="left" valign="bottom">
</td>
<td align="right" valign="bottom" width="26">
<input alt="Go" border="0" class="gobutton" height="21" hspace="6" name="Go" onclick="return gsacheck()" src="/images/1_go_bttn.gif" type="image" vspace="0" width="22"/>
</td>
<td class="advancedsearchcell"> <br/> </td>
</tr>
</tbody></table>
</form>
</td></tr></tbody></table></div>
<a href="/"><img alt="Bureau of Justice Statistics (BJS)" border="0" height="76" hspace="0" src="/images/n_1_main_01.gif" vspace="0" width="533"/></a></div></div>
<div id="nav_mast">
<div id="nav_mast_inner"><div id="sizer" style="float: right; display: block;">
<a class="tab" href="/index.cfm?ty=rss"><img alt="RSS" border="0" class="print_img" id="Img2" name="image2" src="/images/rss_icon.jpg"/></a>

        <a href="#" onclick="window.print()" title="Printer-Friendly"><img alt="Printer-Friendly" border="0" class="print_img" height="12" src="/images/print_icon.gif" width="15"/></a> <a class="box_right_print" href="#" onclick="window.print()" title="Printer-Friendly">Print</a>  <a class="reset box_right_print" href="#" title="Click for default font">Text Size:</a> [<a class="decrease box_right_print" href="#" title="Click for small font">-</a>] [<a class="increase box_right_print" href="#" title="Click for large font">+</a>]</div><div id="bannerMenu">
<ul>
<li class="first" title="Home"><a class="top2" href="/">Home</a></li>
<li class="first" id="topicLink" title="Topics"><a class="top2" href="#">Topics</a>
<ul style="width:900px; margin: 0px 0 0 -35px;">
<li class="topnavdd" style="width:900px;border-bottom: 1px solid #999999;" target="_top">
<table id="tblMegamenu" width="100%">
<tbody><tr style="vertical-align:top;">
<td width="250">
<table id="topicTable" name="topicTable">
<tbody><tr>
<td style="padding:5px"><a href="/index.cfm?ty=tp&amp;tid=1">
<span class="DIN black" style="font-size:11px;color:#2767AF;">Corrections</span></a>
</td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=18" style="font-weight:normal; font-size:10px; color: #000000;">Capital Punishment</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=15" style="font-weight:normal; font-size:10px; color: #000000;">Community Corrections (Probation and Parole)</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=16" style="font-weight:normal; font-size:10px; color: #000000;">Expenditures/Employment</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=12" style="font-weight:normal; font-size:10px; color: #000000;">Local jail inmates and jail facilities</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=19" style="font-weight:normal; font-size:10px; color: #000000;">Mortality in Correctional Institutions (MCI) (Formerly Deaths in Custody Reporting Program (DCRP))</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=20" style="font-weight:normal; font-size:10px; color: #000000;">Prison Rape Elimination Act (Sexual Victimization in Correctional Facilities)
</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=17" style="font-weight:normal; font-size:10px; color: #000000;">Recidivism</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=14" style="font-weight:normal; font-size:10px; color: #000000;">Special populations</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=13" style="font-weight:normal; font-size:10px; color: #000000;">State and federal prisoners and prison facilities</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=11" style="font-weight:normal; font-size:10px; color: #000000;">Total correctional population</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
</tbody></table>
<table id="topicTable" name="topicTable">
<tbody><tr>
<td style="padding:5px"><a href="/index.cfm?ty=tp&amp;tid=6">
<span class="DIN black" style="font-size:11px;color:#2767AF;">Federal</span></a>
</td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=65" style="font-weight:normal; font-size:10px; color: #000000;">Corrections</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=64" style="font-weight:normal; font-size:10px; color: #000000;">Courts</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=62" style="font-weight:normal; font-size:10px; color: #000000;">Law Enforcement</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=63" style="font-weight:normal; font-size:10px; color: #000000;">Prosecution</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
</tbody></table>
</td>
<td width="200">
<table id="topicTable" name="topicTable">
<tbody><tr>
<td style="padding:5px"><a href="/index.cfm?ty=tp&amp;tid=2">
<span class="DIN black" style="font-size:11px;color:#2767AF;">Courts</span></a>
</td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=67" style="font-weight:normal; font-size:10px; color: #000000;">Civil Rights</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=45" style="font-weight:normal; font-size:10px; color: #000000;">Civil cases</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=23" style="font-weight:normal; font-size:10px; color: #000000;">Criminal Cases</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=28" style="font-weight:normal; font-size:10px; color: #000000;">Indigent Defense Systems</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=27" style="font-weight:normal; font-size:10px; color: #000000;">Prosecutors Offices</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=30" style="font-weight:normal; font-size:10px; color: #000000;">State Court Caseload Statistics</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=26" style="font-weight:normal; font-size:10px; color: #000000;">State Court Organization</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">
<a href="/index.cfm?ty=tp&amp;tid=29" style="font-weight:normal; font-size:10px; color: #000000;">Tribal courts</a></td>
</tr>
<tr>
<td height="1px" style="background-color:#ccc"></td>
</tr>
</tbody></table>
<table id="topicTable" name="topicTable">
<tbody><tr>
<td style="padding:5px"><a href="/index.cfm?ty=tp&amp;tid=9">
<span class="DIN black" style="font-size:11px;color:#2767AF;">Victims</span></a>
</td>
</tr>
<tr>
<td style="padding-left:10px;padding-top:2px;padding-bottom:2px;">

## Click Custom Tables in the website

In [5]:
custom_tables = browser.find_by_id('ct').click()

### Click the Yearend population measure
* Ignore the errors, it still clicks it

In [6]:
#POPULATION
element = browser.find_by_xpath('//select[@name="measure"]//option[@value="all"]')
element.click()

WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=76.0.3809.132)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.18362 x86_64)

### Click Total Jurisdiction Population as the first variable

In [7]:
# FIRST VARIABLE
element2 = browser.find_by_xpath('//select[@name="measurevar"]//option[@value="jurtot"]')
element2.click()

WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=76.0.3809.132)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.18362 x86_64)

### Click Sex as your second variable

In [8]:
# 2ND VARIABLE
element3 = browser.find_by_xpath('//select[@name="tier1var"]//option[@value="sex"]')
element3.click()

WebDriverException: Message: unknown error: call function result missing 'value'
  (Session info: chrome=76.0.3809.132)
  (Driver info: chromedriver=2.34.522940 (1a76f96f66e3ca7b8e57d503b4dd3bccfba87af1),platform=Windows NT 10.0.18362 x86_64)

## Generate your table, this will take a couple of minutes...

In [9]:
# GENERATE TABLE
element_table = browser.find_by_xpath('//input[@id="submitcount"]')
element_table.click()

## Reading the Table into Pandas as Dataframe

In [10]:
html = browser.html

In [11]:
soup = BeautifulSoup(html, "html.parser")

In [12]:
tbl_data = pd.read_html(soup.prettify(), skiprows = 2, flavor = 'bs4')[11]

In [13]:
tbl_data

,0,1,2,3,4,5,6,7,8,9,...,70,71,72,73,74,75,76,77,78,79
0,"National Statistics (U.S. Total) 15 , 16 ,...","National Statistics (U.S. Total) 15 , 16 ,...",307276,NaN,314457,NaN,329821,NaN,369930,NaN,...,1570397,NaN,1576950,NaN,1562319,NaN,1526603,NaN,1505397,NaN
1,NaN,"Male 256 , 528 , 662 , 663 , 664 , ...",294530,NaN,301462,NaN,316401,NaN,354393,NaN,...,1461625,NaN,1465592,NaN,1449291,NaN,1415112,NaN,1393975,NaN
2,NaN,"Female 256 , 528 , 662 , 663 , 664 ,...",12746,NaN,12995,NaN,13420,NaN,15537,NaN,...,108772,NaN,111358,NaN,113028,NaN,111491,NaN,111422,NaN
3,"Federal Institutions 15 , 16 , 17 , 18 ...","Federal Institutions 15 , 16 , 17 , 18 ...",29803,NaN,26371,NaN,24363,NaN,28133,NaN,...,217815,NaN,215866,NaN,210567,NaN,196455,NaN,189192,NaN
4,NaN,"Male 662 , 663 , 664 , 665 , 666 , ...",27975,NaN,24835,NaN,22964,NaN,26574,NaN,...,203766,NaN,201697,NaN,196568,NaN,183502,NaN,176495,NaN
5,NaN,"Female 662 , 663 , 664 , 665 , 666 ,...",1828,NaN,1536,NaN,1399,NaN,1559,NaN,...,14049,NaN,14169,NaN,13999,NaN,12953,NaN,12697,NaN
6,"State Institutions (Total) 21 , 22 , 23 ...","State Institutions (Total) 21 , 22 , 23 ...",277473,NaN,288086,NaN,305458,NaN,341797,NaN,...,1352582,NaN,1361084,NaN,1351752,NaN,1330148,NaN,1316205,NaN
7,NaN,"Male 256 , 528 , 683 , 684 , 685 , ...",266555,NaN,276627,NaN,293437,NaN,327819,NaN,...,1257859,NaN,1263895,NaN,1252723,NaN,1231610,NaN,1217480,NaN
8,NaN,"Female 256 , 528 , 683 , 684 , 685 ,...",10918,NaN,11459,NaN,12021,NaN,13978,NaN,...,94723,NaN,97189,NaN,99029,NaN,98538,NaN,98725,NaN
9,"Alabama 33 , 34 , 35 , 36 , 37","Alabama 33 , 34 , 35 , 36 , 37",5625,NaN,5464,NaN,6543,NaN,7657,NaN,...,32431,NaN,32381,NaN,31771,NaN,30810,NaN,28883,NaN
10,NaN,Male,5368,NaN,5221,NaN,6278,NaN,7339,NaN,...,29782,NaN,29660,NaN,29182,NaN,28220,NaN,26506,NaN
11,NaN,Female,257,NaN,243,NaN,265,NaN,318,NaN,...,2649,NaN,2721,NaN,2589,NaN,2590,NaN,2377,NaN
12,"Alaska 38 , 39 , 40 , 41 , 42 , 43 ...","Alaska 38 , 39 , 40 , 41 , 42 , 43 ...",712,NaN,760,NaN,822,NaN,1024,NaN,...,5633,NaN,5081,NaN,5794,NaN,5338,NaN,4434,NaN
13,NaN,"Male 683 , 684 , 685",678,NaN,729,NaN,801,NaN,977,NaN,...,4934,NaN,4450,NaN,5091,NaN,4761,NaN,4024,NaN
14,NaN,"Female 683 , 684 , 685",34,NaN,31,NaN,21,NaN,47,NaN,...,699,NaN,631,NaN,703,NaN,577,NaN,410,NaN
15,"Arizona 60 , 61 , 62 , 63 , 64 , 65...","Arizona 60 , 61 , 62 , 63 , 64 , 65...",3456,NaN,3749,NaN,4372,NaN,5223,NaN,...,40080,NaN,41177,NaN,42259,NaN,42719,NaN,42320,NaN
16,NaN,"Male 686 , 687 , 688",3275,NaN,3573,NaN,4153,NaN,4986,NaN,...,36447,NaN,37402,NaN,38295,NaN,38738,NaN,38323,NaN
17,NaN,"Female 686 , 687 , 688",181,NaN,176,NaN,219,NaN,237,NaN,...,3633,NaN,3775,NaN,3964,NaN,3981,NaN,3997,NaN
18,"Arkansas 82 , 83 , 84 , 85 , 86 , 8...","Arkansas 82 , 83 , 84 , 85 , 86 , 8...",2654,NaN,3042,NaN,2911,NaN,3328,NaN,...,14654,NaN,17235,NaN,17874,NaN,17707,NaN,17537,NaN
19,NaN,"Male 689 , 690 , 691",2553,NaN,2927,NaN,2805,NaN,3197,NaN,...,13594,NaN,15904,NaN,16476,NaN,16305,NaN,16161,NaN
20,NaN,"Female 689 , 690 , 691",101,NaN,115,NaN,106,NaN,131,NaN,...,1060,NaN,1331,NaN,1398,NaN,1402,NaN,1376,NaN
21,"California 66 , 91 , 92 , 93 , 94 , ...","California 66 , 91 , 92 , 93 , 94 , ...",21325,NaN,22632,NaN,24569,NaN,29202,NaN,...,134534,NaN,135981,NaN,136085,NaN,129593,NaN,130390,NaN
22,NaN,Male,20178,NaN,21400,NaN,23253,NaN,27775,NaN,...,128436,NaN,129684,NaN,129703,NaN,123808,NaN,124487,NaN
23,NaN,Female,1147,NaN,1232,NaN,1316,NaN,1427,NaN,...,6098,NaN,6297,NaN,6382,NaN,5785,NaN,5903,NaN
24,"Colorado 100 , 101 , 102 , 103 , 104 ...","Colorado 100 , 101 , 102 , 103 , 104 ...",2486,NaN,2668,NaN,2629,NaN,2772,NaN,...,20462,NaN,20371,NaN,20646,NaN,20041,NaN,19981,NaN
25,NaN,"Male 692 , 693 , 694 , 695 , 696 , 697",2419,NaN,2587,NaN,2560,NaN,2691,NaN,...,18739,NaN,18556,NaN,18738,NaN,18199,NaN,18078,NaN
26,NaN,"Female 692 , 693 , 694 , 695 , 696 ,...",67,NaN,81,NaN,69,NaN,81,NaN,...,1723,NaN,1815,NaN,1908,NaN,1842,NaN,1903,NaN
27,"Connecticut 38 , 41 , 43 , 47 , 58 ,...","Connecticut 38 , 41 , 43 , 47 , 58 ,...",3189,NaN,4061,NaN,4308,NaN,5263,NaN,...,17530,NaN,17563,NaN,16636,NaN,15816,NaN,14957,NaN
28,NaN,Male,3044,NaN,3919,NaN,4102,NaN,5011,NaN,...,16312,NaN,16328,NaN,15510,NaN,14695,NaN,13892,NaN
29,NaN,Female,145,NaN,142,NaN,206,NaN,252,NaN,...,1218,NaN,1235,NaN,1126,NaN,1121,NaN,1065,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,"South Dakota 543 , 544 , 545","South Dakota 543 , 544 , 545",532,NaN,562,NaN,635,NaN,693,NaN,...,3650,NaN,3682,NaN,3608,NaN,3564,NaN,3831,NaN
133,NaN,Male 761,514,NaN,538,NaN,617,NaN,664,NaN,...,3227,NaN,3240,NaN,3199,NaN,3148,NaN,3333,NaN
134,NaN,Female 761,18,NaN,24,NaN,18,NaN,29,NaN,...,423,NaN,442,NaN,409,NaN,416,NaN,498,NaN
135,"Tennessee 177 , 230 , 231 , 232 , 233...","Tennessee 177 , 230 , 231 , 232 , 233...",5835,NaN,6629,NaN,7022,NaN,7897,NaN,...,28411,NaN,28521,NaN,28769,NaN,28172,NaN,28203,NaN
136,NaN,"Male 762 , 763 , 764 , 765",5574,NaN,6346,NaN,6686,NaN,7502,NaN,...,26048,NaN,26069,NaN,26160,NaN,25532,NaN,25481,NaN
137,NaN,"Female 762 , 763",261,NaN,283,NaN,336,NaN,395,NaN,...,2363,NaN,2452,NaN,2609,NaN,2640,NaN,2722,NaN
138,"Texas 66 , 91 , 218 , 231 , 565 , 5...","Texas 66 , 91 , 218 , 231 , 565 , 5...",24575,NaN,26522,NaN,29892,NaN,31502,NaN,...,166372,NaN,168280,NaN,166043,NaN,163909,NaN,163703,NaN
139,NaN,"Male 766 , 767 , 768 , 769",23570,NaN,25355,NaN,28671,NaN,30050,NaN,...,152823,NaN,154450,NaN,151717,NaN,149501,NaN,149368,NaN
140,NaN,"Female 766 , 767 , 768 , 769",1005,NaN,1167,NaN,1221,NaN,1452,NaN,...,13549,NaN,13830,NaN,14326,NaN,14408,NaN,14335,NaN
141,"Utah 223 , 576 , 579 , 580 , 581 , 582","Utah 223 , 576 , 579 , 580 , 581 , 582",911,NaN,960,NaN,932,NaN,1140,NaN,...,6962,NaN,7077,NaN,7031,NaN,6495,NaN,6182,NaN
142,NaN,Male,875,NaN,926,NaN,905,NaN,1099,NaN,...,6323,NaN,6415,NaN,6369,NaN,5980,NaN,5777,NaN
143,NaN,Female,36,NaN,34,NaN,27,NaN,41,NaN,...,639,NaN,662,NaN,662,NaN,515,NaN,405,NaN
144,"Vermont 38 , 41 , 47 , 128 , 528 , ...","Vermont 38 , 41 , 47 , 128 , 528 , ...",441,NaN,431,NaN,480,NaN,534,NaN,...,2034,NaN,2078,NaN,1979,NaN,1750,NaN,1735,NaN
145,NaN,Male 770,430,NaN,420,NaN,464,NaN,519,NaN,...,1907,NaN,1924,NaN,1823,NaN,1600,NaN,1600,NaN
146,NaN,Female 770,11,NaN,11,NaN,16,NaN,15,NaN,...,127,NaN,154,NaN,156,NaN,150,NaN,135,NaN
147,"Virginia 416 , 420 , 610 , 611 , 612 ...","Virginia 416 , 420 , 610 , 611 , 612 ...",8344,NaN,8449,NaN,8920,NaN,9388,NaN,...,37044,NaN,36982,NaN,37544,NaN,38403,NaN,37813,NaN
148,NaN,"Male 771 , 772 , 773 , 774 , 775 , ...",7985,NaN,8148,NaN,8617,NaN,9040,NaN,...,34150,NaN,34133,NaN,34529,NaN,35167,NaN,34704,NaN
149,NaN,"Female 771 , 772 , 773 , 774 , 775 ,...",359,NaN,301,NaN,303,NaN,348,NaN,...,2894,NaN,2849,NaN,3015,NaN,3236,NaN,3109,NaN
150,"Washington 416 , 624 , 625 , 626 , 62...","Washington 416 , 624 , 625 , 626 , 62...",4487,NaN,4342,NaN,4399,NaN,5336,NaN,...,17271,NaN,17984,NaN,18120,NaN,18284,NaN,19104,NaN
151,NaN,"Male 780 , 781",4251,NaN,4137,NaN,4209,NaN,5124,NaN,...,15934,NaN,16535,NaN,16666,NaN,16829,NaN,17446,NaN
152,NaN,"Female 780 , 781",236,NaN,205,NaN,190,NaN,212,NaN,...,1337,NaN,1449,NaN,1454,NaN,1455,NaN,1658,NaN
153,"West Virginia 65 , 66 , 633 , 634 , 6...","West Virginia 65 , 66 , 633 , 634 , 6...",1237,NaN,1251,NaN,1257,NaN,1565,NaN,...,7070,NaN,6824,NaN,6896,NaN,7118,NaN,7162,NaN
154,NaN,Male,1208,NaN,1218,NaN,1227,NaN,1528,NaN,...,6265,NaN,6016,NaN,6065,NaN,6253,NaN,6286,NaN
155,NaN,Female,29,NaN,33,NaN,30,NaN,37,NaN,...,805,NaN,808,NaN,831,NaN,865,NaN,876,NaN
156,"Wisconsin 643 , 644 , 645 , 646 , 647...","Wisconsin 643 , 644 , 645 , 646 , 647...",3432,NaN,3677,NaN,3980,NaN,4385,NaN,...,22600,NaN,22471,NaN,22597,NaN,22975,NaN,23377,NaN
157,NaN,"Male 782 , 783 , 784 , 785 , 786 , ...",3285,NaN,3532,NaN,3826,NaN,4216,NaN,...,21375,NaN,21232,NaN,21219,NaN,21567,NaN,21889,NaN
158,NaN,"Female 782 , 783 , 784 , 785 , 786 ,...",147,NaN,145,NaN,154,NaN,169,NaN,...,1225,NaN,1239,NaN,1378,NaN,1408,NaN,1488,NaN
159,"Wyoming 66 , 656 , 657 , 658 , 659 ,...","Wyoming 66 , 656 , 657 , 658 , 659 ,...",433,NaN,504,NaN,534,NaN,556,NaN,...,2204,NaN,2310,NaN,2383,NaN,2424,NaN,2374,NaN
160,NaN,Male,414,NaN,474,NaN,505,NaN,532,NaN,...,1966,NaN,2050,NaN,2106,NaN,2157,NaN,2088,NaN
161,NaN,Female,19,NaN,30,NaN,29,NaN,24,NaN,...,238,NaN,260,NaN,277,NaN,267,NaN,286,NaN

## Getting rid of the columns with NaN

In [14]:
tbl_data_copy = tbl_data.dropna(axis=1, how='all')
tbl_data_copy

,0,1,2,4,6,8,10,12,14,16,...,60,62,64,66,68,70,72,74,76,78
0,"National Statistics (U.S. Total) 15 , 16 ,...","National Statistics (U.S. Total) 15 , 16 ,...",307276,314457,329821,369930,413806,436855,462002,502507,...,1596835,1608282,1615487,1613803,1598968,1570397,1576950,1562319,1526603,1505397
1,NaN,"Male 256 , 528 , 662 , 663 , 664 , ...",294530,301462,316401,354393,396021,417835,441208,479359,...,1482524,1493670,1502002,1500936,1487561,1461625,1465592,1449291,1415112,1393975
2,NaN,"Female 256 , 528 , 662 , 663 , 664 ,...",12746,12995,13420,15537,17785,19020,20794,23148,...,114311,114612,113485,112867,111407,108772,111358,113028,111491,111422
3,"Federal Institutions 15 , 16 , 17 , 18 ...","Federal Institutions 15 , 16 , 17 , 18 ...",29803,26371,24363,28133,29673,31926,34263,40223,...,199618,201280,208118,209771,216362,217815,215866,210567,196455,189192
4,NaN,"Male 662 , 663 , 664 , 665 , 666 , ...",27975,24835,22964,26574,28046,30172,32267,37819,...,186280,188007,194493,196222,202462,203766,201697,196568,183502,176495
5,NaN,"Female 662 , 663 , 664 , 665 , 666 ,...",1828,1536,1399,1559,1627,1754,1996,2404,...,13338,13273,13625,13549,13900,14049,14169,13999,12953,12697
6,"State Institutions (Total) 21 , 22 , 23 ...","State Institutions (Total) 21 , 22 , 23 ...",277473,288086,305458,341797,384133,404929,427739,462284,...,1397217,1407002,1407369,1404032,1382606,1352582,1361084,1351752,1330148,1316205
7,NaN,"Male 256 , 528 , 683 , 684 , 685 , ...",266555,276627,293437,327819,367975,387663,408941,441540,...,1296244,1305663,1307509,1304714,1285099,1257859,1263895,1252723,1231610,1217480
8,NaN,"Female 256 , 528 , 683 , 684 , 685 ,...",10918,11459,12021,13978,16158,17266,18798,20744,...,100973,101339,99860,99318,97507,94723,97189,99029,98538,98725
9,"Alabama 33 , 34 , 35 , 36 , 37","Alabama 33 , 34 , 35 , 36 , 37",5625,5464,6543,7657,9233,9856,10482,11015,...,29412,30508,31874,31764,32270,32431,32381,31771,30810,28883
10,NaN,Male,5368,5221,6278,7339,8757,9375,9961,10453,...,27254,28277,29419,29261,29696,29782,29660,29182,28220,26506
11,NaN,Female,257,243,265,318,476,481,521,562,...,2158,2231,2455,2503,2574,2649,2721,2589,2590,2377
12,"Alaska 38 , 39 , 40 , 41 , 42 , 43 ...","Alaska 38 , 39 , 40 , 41 , 42 , 43 ...",712,760,822,1024,1322,1631,1967,2329,...,5167,5014,5285,5391,5597,5633,5081,5794,5338,4434
13,NaN,"Male 683 , 684 , 685",678,729,801,977,1276,1557,1888,2207,...,4603,4511,4696,4782,4932,4934,4450,5091,4761,4024
14,NaN,"Female 683 , 684 , 685",34,31,21,47,46,74,79,122,...,564,503,589,609,665,699,631,703,577,410
15,"Arizona 60 , 61 , 62 , 63 , 64 , 65...","Arizona 60 , 61 , 62 , 63 , 64 , 65...",3456,3749,4372,5223,6069,6889,7845,8531,...,37746,39502,40544,40209,40020,40080,41177,42259,42719,42320
16,NaN,"Male 686 , 687 , 688",3275,3573,4153,4986,5788,6566,7482,8134,...,34286,35739,36768,36521,36470,36447,37402,38295,38738,38323
17,NaN,"Female 686 , 687 , 688",181,176,219,237,281,323,363,397,...,3460,3763,3776,3688,3550,3633,3775,3964,3981,3997
18,"Arkansas 82 , 83 , 84 , 85 , 86 , 8...","Arkansas 82 , 83 , 84 , 85 , 86 , 8...",2654,3042,2911,3328,3922,4246,4482,4611,...,14314,14716,15208,16204,16108,14654,17235,17874,17707,17537
19,NaN,"Male 689 , 690 , 691",2553,2927,2805,3197,3755,4050,4286,4394,...,13248,13656,14147,15040,14995,13594,15904,16476,16305,16161
20,NaN,"Female 689 , 690 , 691",101,115,106,131,167,196,196,217,...,1066,1060,1061,1164,1113,1060,1331,1398,1402,1376
21,"California 66 , 91 , 92 , 93 , 94 , ...","California 66 , 91 , 92 , 93 , 94 , ...",21325,22632,24569,29202,34640,39373,43197,50158,...,174282,173670,171275,165062,149569,134534,135981,136085,129593,130390
22,NaN,Male,20178,21400,23253,27775,32987,37353,40892,47248,...,162654,162050,160286,155104,141382,128436,129684,129703,123808,124487
23,NaN,Female,1147,1232,1316,1427,1653,2020,2305,2910,...,11628,11620,10989,9958,8187,6098,6297,6382,5785,5903
24,"Colorado 100 , 101 , 102 , 103 , 104 ...","Colorado 100 , 101 , 102 , 103 , 104 ...",2486,2668,2629,2772,3042,3244,3231,3386,...,22841,23274,22795,22815,21978,20462,20371,20646,20041,19981
25,NaN,"Male 692 , 693 , 694 , 695 , 696 , 697",2419,2587,2560,2691,2923,3108,3091,3238,...,20506,20980,20694,20763,19957,18739,18556,18738,18199,18078
26,NaN,"Female 692 , 693 , 694 , 695 , 696 ,...",67,81,69,81,119,136,140,148,...,2335,2294,2101,2052,2021,1723,1815,1908,1842,1903
27,"Connecticut 38 , 41 , 43 , 47 , 58 ,...","Connecticut 38 , 41 , 43 , 47 , 58 ,...",3189,4061,4308,5263,5156,5474,5718,6149,...,20924,20661,19716,19321,18324,17530,17563,16636,15816,14957
28,NaN,Male,3044,3919,4102,5011,4952,5193,5431,5826,...,19428,19159,18381,18075,17090,16312,16328,15510,14695,13892
29,NaN,Female,145,142,206,252,204,281,287,323,...,1496,1502,1335,1246,1234,1218,1235,1126,1121,1065
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,"South Dakota 543 , 544 , 545","South Dakota 543 , 544 , 545",532,562,635,693,791,826,921,1049,...,3311,3342,3434,3434,3535,3650,3682,3608,3564,3831
133,NaN,Male 761,514,538,617,664,748,785,889,1008,...,2942,2987,3054,3023,3094,3227,3240,3199,3148,3333
134,NaN,Female 761,18,24,18,29,43,41,32,41,...,369,355,380,411,441,423,442,409,416,498
135,"Tennessee 177 , 230 , 231 , 232 , 233...","Tennessee 177 , 230 , 231 , 232 , 233...",5835,6629,7022,7897,7869,8201,7307,7127,...,26267,27228,26965,27451,28479,28411,28521,28769,28172,28203
136,NaN,"Male 762 , 763 , 764 , 765",5574,6346,6686,7502,7489,7803,6993,6825,...,24344,25099,24956,25345,26070,26048,26069,26160,25532,25481
137,NaN,"Female 762 , 763",261,283,336,395,380,398,314,302,...,1923,2129,2009,2106,2409,2363,2452,2609,2640,2722
138,"Texas 66 , 91 , 218 , 231 , 565 , 5...","Texas 66 , 91 , 218 , 231 , 565 , 5...",24575,26522,29892,31502,36149,35259,36682,37532,...,171790,172506,171249,173649,172224,166372,168280,166043,163909,163703
139,NaN,"Male 766 , 767 , 768 , 769",23570,25355,28671,30050,34472,33789,34987,35938,...,157859,158653,157679,159298,158036,152823,154450,151717,149501,149368
140,NaN,"Female 766 , 767 , 768 , 769",1005,1167,1221,1452,1677,1470,1695,1594,...,13931,13853,13570,14351,14188,13549,13830,14326,14408,14335
141,"Utah 223 , 576 , 579 , 580 , 581 , 582","Utah 223 , 576 , 579 , 580 , 581 , 582",911,960,932,1140,1216,1274,1504,1633,...,6515,6552,6538,6807,6879,6962,7077,7031,6495,6182
142,NaN,Male,875,926,905,1099,1169,1223,1456,1570,...,5883,5912,5956,6199,6266,6323,6415,6369,5980,5777
143,NaN,Female,36,34,27,41,47,51,48,63,...,632,640,582,608,613,639,662,662,515,405
144,"Vermont 38 , 41 , 47 , 128 , 528 , ...","Vermont 38 , 41 , 47 , 128 , 528 , ...",441,431,480,534,599,497,501,677,...,2116,2116,2220,2079,2053,2034,2078,1979,1750,1735
145,NaN,Male 770,430,420,464,519,582,488,488,660,...,1998,1998,2065,1930,1905,1907,1924,1823,1600,1600
146,NaN,Female 770,11,11,16,15,17,9,13,17,...,118,118,155,149,148,127,154,156,150,135
147,"Virginia 416 , 420 , 610 , 611 , 612 ...","Virginia 416 , 420 , 610 , 611 , 612 ...",8344,8449,8920,9388,10079,10093,10839,12073,...,37984,38216,38059,37638,38130,37044,36982,37544,38403,37813
148,NaN,"Male 771 , 772 , 773 , 774 , 775 , ...",7985,8148,8617,9040,9715,9712,10406,11604,...,35055,35249,35156,34790,35321,34150,34133,34529,35167,34704
149,NaN,"Female 771 , 772 , 773 , 774 , 775 ,...",359,301,303,348,364,381,433,469,...,2929,2967,2903,2848,2809,2894,2849,3015,3236,3109
150,"Washington 416 , 624 , 625 , 626 , 62...","Washington 416 , 624 , 625 , 626 , 62...",4487,4342,4399,5336,6264,6658,6821,6919,...,17772,17926,18233,18235,17847,17271,17984,18120,18284,19104
151,NaN,"Male 780 , 781",4251,4137,4209,5124,6018,6416,6567,6689,...,16258,16522,16836,16808,16452,15934,16535,16666,16829,17446
152,NaN,"Female 780 , 781",236,205,190,212,246,242,254,230,...,1514,1404,1397,1427,1395,1337,1449,1454,1455,1658
153,"West Virginia 65 , 66 , 633 , 634 , 6...","West Virginia 65 , 66 , 633 , 634 , 6...",1237,1251,1257,1565,1547,1611,1579,1725,...,6056,6059,6367,6681,6826,7070,6824,6896,7118,7162
154,NaN,Male,1208,1218,1227,1528,1500,1553,1528,1658,...,5422,5411,5683,5956,6074,6265,6016,6065,6253,6286
155,NaN,Female,29,33,30,37,47,58,51,67,...,634,648,684,725,752,805,808,831,865,876
156,"Wisconsin 643 , 644 , 645 , 646 , 647...","Wisconsin 643 , 644 , 645 , 646 , 647...",3432,3677,3980,4385,4714,4845,4974,5425,...,23743,23379,23165,22729,22657,22600,22471,22597,22975,23377
157,NaN,"Male 782 , 783 , 784 , 785 , 786 , ...",3285,3532,3826,4216,4517,4632,4747,5174,...,22216,22022,21859,21465,21472,21375,21232,21219,21567,21889
158,NaN,"Female 782 , 783 , 784 , 785 , 786 ,...",147,145,154,169,197,213,227,251,...,1527,1357,1306,1264,1185,1225,1239,1378,1408,1488
159,"Wyoming 66 , 656 , 657 , 658 , 659 ,...","Wyoming 66 , 656 , 657 , 658 , 659 ,...",433,504,534,556,702,721,724,762,...,2084,2084,2075,2112,2183,2204,2310,2383,2424,2374
160,NaN,Male,414,474,505,532,674,688,685,716,...,1838,1876,1861,1881,1944,1966,2050,2106,2157,2088
161,NaN,Female,19,30,29,24,28,33,39,46,...,246,208,214,231,239,238,260,277,267,286

## Renaming columns

In [15]:
import numpy as np

In [16]:
col = np.arange(1978,2017)
name_list = ["State","Total/Sex"]

name_list
print(col)

[1978 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991
 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005
 2006 2007 2008 2009 2010 2011 2012 2013 2014 2015 2016]

In [17]:
# Step 1 : Convert numpy array to a list
lst_col = list(col)

In [18]:
# Step 2 : Insert Name list to column list at index 0 and 1
lst_col.insert(0,name_list[0])
lst_col.insert(1,name_list[1])

In [19]:
lst_col

['State',
 'Total/Sex',
 1978,
 1979,
 1980,
 1981,
 1982,
 1983,
 1984,
 1985,
 1986,
 1987,
 1988,
 1989,
 1990,
 1991,
 1992,
 1993,
 1994,
 1995,
 1996,
 1997,
 1998,
 1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016]

In [20]:
# Step 3: Change dataframe column values to this new list
tbl_data_copy.columns = lst_col

In [21]:
tbl_data_copy.head()

,State,Total/Sex,1978,1979,1980,1981,1982,1983,1984,1985,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,"National Statistics (U.S. Total) 15 , 16 ,...","National Statistics (U.S. Total) 15 , 16 ,...",307276,314457,329821,369930,413806,436855,462002,502507,...,1596835,1608282,1615487,1613803,1598968,1570397,1576950,1562319,1526603,1505397
1,NaN,"Male 256 , 528 , 662 , 663 , 664 , ...",294530,301462,316401,354393,396021,417835,441208,479359,...,1482524,1493670,1502002,1500936,1487561,1461625,1465592,1449291,1415112,1393975
2,NaN,"Female 256 , 528 , 662 , 663 , 664 ,...",12746,12995,13420,15537,17785,19020,20794,23148,...,114311,114612,113485,112867,111407,108772,111358,113028,111491,111422
3,"Federal Institutions 15 , 16 , 17 , 18 ...","Federal Institutions 15 , 16 , 17 , 18 ...",29803,26371,24363,28133,29673,31926,34263,40223,...,199618,201280,208118,209771,216362,217815,215866,210567,196455,189192
4,NaN,"Male 662 , 663 , 664 , 665 , 666 , ...",27975,24835,22964,26574,28046,30172,32267,37819,...,186280,188007,194493,196222,202462,203766,201697,196568,183502,176495

In [22]:
test = tbl_data_copy

### Data Cleanup

In [23]:
test.loc[test['Total/Sex'].str.contains('Female'), 'Total/Sex'] = 'Female'

C:\Users\ivvya\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [24]:
test.loc[test['Total/Sex'].str.contains('Male'), 'Total/Sex'] = "Male"

In [25]:
test.loc[test['Total/Sex'].str.contains('National Statistics'), 'Total/Sex'] = "Total"

In [26]:
test.loc[test['Total/Sex'].str.contains('Federal Institutions'), 'Total/Sex'] = "Total"

In [27]:
test.loc[test['Total/Sex'].str.contains('State Institutions'), 'Total/Sex'] = "Total"

In [28]:
test

,State,Total/Sex,1978,1979,1980,1981,1982,1983,1984,1985,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,"National Statistics (U.S. Total) 15 , 16 ,...",Total,307276,314457,329821,369930,413806,436855,462002,502507,...,1596835,1608282,1615487,1613803,1598968,1570397,1576950,1562319,1526603,1505397
1,NaN,Male,294530,301462,316401,354393,396021,417835,441208,479359,...,1482524,1493670,1502002,1500936,1487561,1461625,1465592,1449291,1415112,1393975
2,NaN,Female,12746,12995,13420,15537,17785,19020,20794,23148,...,114311,114612,113485,112867,111407,108772,111358,113028,111491,111422
3,"Federal Institutions 15 , 16 , 17 , 18 ...",Total,29803,26371,24363,28133,29673,31926,34263,40223,...,199618,201280,208118,209771,216362,217815,215866,210567,196455,189192
4,NaN,Male,27975,24835,22964,26574,28046,30172,32267,37819,...,186280,188007,194493,196222,202462,203766,201697,196568,183502,176495
5,NaN,Female,1828,1536,1399,1559,1627,1754,1996,2404,...,13338,13273,13625,13549,13900,14049,14169,13999,12953,12697
6,"State Institutions (Total) 21 , 22 , 23 ...",Total,277473,288086,305458,341797,384133,404929,427739,462284,...,1397217,1407002,1407369,1404032,1382606,1352582,1361084,1351752,1330148,1316205
7,NaN,Male,266555,276627,293437,327819,367975,387663,408941,441540,...,1296244,1305663,1307509,1304714,1285099,1257859,1263895,1252723,1231610,1217480
8,NaN,Female,10918,11459,12021,13978,16158,17266,18798,20744,...,100973,101339,99860,99318,97507,94723,97189,99029,98538,98725
9,"Alabama 33 , 34 , 35 , 36 , 37","Alabama 33 , 34 , 35 , 36 , 37",5625,5464,6543,7657,9233,9856,10482,11015,...,29412,30508,31874,31764,32270,32431,32381,31771,30810,28883
10,NaN,Male,5368,5221,6278,7339,8757,9375,9961,10453,...,27254,28277,29419,29261,29696,29782,29660,29182,28220,26506
11,NaN,Female,257,243,265,318,476,481,521,562,...,2158,2231,2455,2503,2574,2649,2721,2589,2590,2377
12,"Alaska 38 , 39 , 40 , 41 , 42 , 43 ...","Alaska 38 , 39 , 40 , 41 , 42 , 43 ...",712,760,822,1024,1322,1631,1967,2329,...,5167,5014,5285,5391,5597,5633,5081,5794,5338,4434
13,NaN,Male,678,729,801,977,1276,1557,1888,2207,...,4603,4511,4696,4782,4932,4934,4450,5091,4761,4024
14,NaN,Female,34,31,21,47,46,74,79,122,...,564,503,589,609,665,699,631,703,577,410
15,"Arizona 60 , 61 , 62 , 63 , 64 , 65...","Arizona 60 , 61 , 62 , 63 , 64 , 65...",3456,3749,4372,5223,6069,6889,7845,8531,...,37746,39502,40544,40209,40020,40080,41177,42259,42719,42320
16,NaN,Male,3275,3573,4153,4986,5788,6566,7482,8134,...,34286,35739,36768,36521,36470,36447,37402,38295,38738,38323
17,NaN,Female,181,176,219,237,281,323,363,397,...,3460,3763,3776,3688,3550,3633,3775,3964,3981,3997
18,"Arkansas 82 , 83 , 84 , 85 , 86 , 8...","Arkansas 82 , 83 , 84 , 85 , 86 , 8...",2654,3042,2911,3328,3922,4246,4482,4611,...,14314,14716,15208,16204,16108,14654,17235,17874,17707,17537
19,NaN,Male,2553,2927,2805,3197,3755,4050,4286,4394,...,13248,13656,14147,15040,14995,13594,15904,16476,16305,16161
20,NaN,Female,101,115,106,131,167,196,196,217,...,1066,1060,1061,1164,1113,1060,1331,1398,1402,1376
21,"California 66 , 91 , 92 , 93 , 94 , ...","California 66 , 91 , 92 , 93 , 94 , ...",21325,22632,24569,29202,34640,39373,43197,50158,...,174282,173670,171275,165062,149569,134534,135981,136085,129593,130390
22,NaN,Male,20178,21400,23253,27775,32987,37353,40892,47248,...,162654,162050,160286,155104,141382,128436,129684,129703,123808,124487
23,NaN,Female,1147,1232,1316,1427,1653,2020,2305,2910,...,11628,11620,10989,9958,8187,6098,6297,6382,5785,5903
24,"Colorado 100 , 101 , 102 , 103 , 104 ...","Colorado 100 , 101 , 102 , 103 , 104 ...",2486,2668,2629,2772,3042,3244,3231,3386,...,22841,23274,22795,22815,21978,20462,20371,20646,20041,19981
25,NaN,Male,2419,2587,2560,2691,2923,3108,3091,3238,...,20506,20980,20694,20763,19957,18739,18556,18738,18199,18078
26,NaN,Female,67,81,69,81,119,136,140,148,...,2335,2294,2101,2052,2021,1723,1815,1908,1842,1903
27,"Connecticut 38 , 41 , 43 , 47 , 58 ,...","Connecticut 38 , 41 , 43 , 47 , 58 ,...",3189,4061,4308,5263,5156,5474,5718,6149,...,20924,20661,19716,19321,18324,17530,17563,16636,15816,14957
28,NaN,Male,3044,3919,4102,5011,4952,5193,5431,5826,...,19428,19159,18381,18075,17090,16312,16328,15510,14695,13892
29,NaN,Female,145,142,206,252,204,281,287,323,...,1496,1502,1335,1246,1234,1218,1235,1126,1121,1065
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,"South Dakota 543 , 544 , 545","South Dakota 543 , 544 , 545",532,562,635,693,791,826,921,1049,...,3311,3342,3434,3434,3535,3650,3682,3608,3564,3831
133,NaN,Male,514,538,617,664,748,785,889,1008,...,2942,2987,3054,3023,3094,3227,3240,3199,3148,3333
134,NaN,Female,18,24,18,29,43,41,32,41,...,369,355,380,411,441,423,442,409,416,498
135,"Tennessee 177 , 230 , 231 , 232 , 233...","Tennessee 177 , 230 , 231 , 232 , 233...",5835,6629,7022,7897,7869,8201,7307,7127,...,26267,27228,26965,27451,28479,28411,28521,28769,28172,28203
136,NaN,Male,5574,6346,6686,7502,7489,7803,6993,6825,...,24344,25099,24956,25345,26070,26048,26069,26160,25532,25481
137,NaN,Female,261,283,336,395,380,398,314,302,...,1923,2129,2009,2106,2409,2363,2452,2609,2640,2722
138,"Texas 66 , 91 , 218 , 231 , 565 , 5...","Texas 66 , 91 , 218 , 231 , 565 , 5...",24575,26522,29892,31502,36149,35259,36682,37532,...,171790,172506,171249,173649,172224,166372,168280,166043,163909,163703
139,NaN,Male,23570,25355,28671,30050,34472,33789,34987,35938,...,157859,158653,157679,159298,158036,152823,154450,151717,149501,149368
140,NaN,Female,1005,1167,1221,1452,1677,1470,1695,1594,...,13931,13853,13570,14351,14188,13549,13830,14326,14408,14335
141,"Utah 223 , 576 , 579 , 580 , 581 , 582","Utah 223 , 576 , 579 , 580 , 581 , 582",911,960,932,1140,1216,1274,1504,1633,...,6515,6552,6538,6807,6879,6962,7077,7031,6495,6182
142,NaN,Male,875,926,905,1099,1169,1223,1456,1570,...,5883,5912,5956,6199,6266,6323,6415,6369,5980,5777
143,NaN,Female,36,34,27,41,47,51,48,63,...,632,640,582,608,613,639,662,662,515,405
144,"Vermont 38 , 41 , 47 , 128 , 528 , ...","Vermont 38 , 41 , 47 , 128 , 528 , ...",441,431,480,534,599,497,501,677,...,2116,2116,2220,2079,2053,2034,2078,1979,1750,1735
145,NaN,Male,430,420,464,519,582,488,488,660,...,1998,1998,2065,1930,1905,1907,1924,1823,1600,1600
146,NaN,Female,11,11,16,15,17,9,13,17,...,118,118,155,149,148,127,154,156,150,135
147,"Virginia 416 , 420 , 610 , 611 , 612 ...","Virginia 416 , 420 , 610 , 611 , 612 ...",8344,8449,8920,9388,10079,10093,10839,12073,...,37984,38216,38059,37638,38130,37044,36982,37544,38403,37813
148,NaN,Male,7985,8148,8617,9040,9715,9712,10406,11604,...,35055,35249,35156,34790,35321,34150,34133,34529,35167,34704
149,NaN,Female,359,301,303,348,364,381,433,469,...,2929,2967,2903,2848,2809,2894,2849,3015,3236,3109
150,"Washington 416 , 624 , 625 , 626 , 62...","Washington 416 , 624 , 625 , 626 , 62...",4487,4342,4399,5336,6264,6658,6821,6919,...,17772,17926,18233,18235,17847,17271,17984,18120,18284,19104
151,NaN,Male,4251,4137,4209,5124,6018,6416,6567,6689,...,16258,16522,16836,16808,16452,15934,16535,16666,16829,17446
152,NaN,Female,236,205,190,212,246,242,254,230,...,1514,1404,1397,1427,1395,1337,1449,1454,1455,1658
153,"West Virginia 65 , 66 , 633 , 634 , 6...","West Virginia 65 , 66 , 633 , 634 , 6...",1237,1251,1257,1565,1547,1611,1579,1725,...,6056,6059,6367,6681,6826,7070,6824,6896,7118,7162
154,NaN,Male,1208,1218,1227,1528,1500,1553,1528,1658,...,5422,5411,5683,5956,6074,6265,6016,6065,6253,6286
155,NaN,Female,29,33,30,37,47,58,51,67,...,634,648,684,725,752,805,808,831,865,876
156,"Wisconsin 643 , 644 , 645 , 646 , 647...","Wisconsin 643 , 644 , 645 , 646 , 647...",3432,3677,3980,4385,4714,4845,4974,5425,...,23743,23379,23165,22729,22657,22600,22471,22597,22975,23377
157,NaN,Male,3285,3532,3826,4216,4517,4632,4747,5174,...,22216,22022,21859,21465,21472,21375,21232,21219,21567,21889
158,NaN,Female,147,145,154,169,197,213,227,251,...,1527,1357,1306,1264,1185,1225,1239,1378,1408,1488
159,"Wyoming 66 , 656 , 657 , 658 , 659 ,...","Wyoming 66 , 656 , 657 , 658 , 659 ,...",433,504,534,556,702,721,724,762,...,2084,2084,2075,2112,2183,2204,2310,2383,2424,2374
160,NaN,Male,414,474,505,532,674,688,685,716,...,1838,1876,1861,1881,1944,1966,2050,2106,2157,2088
161,NaN,Female,19,30,29,24,28,33,39,46,...,246,208,214,231,239,238,260,277,267,286

In [29]:
test1 = test

In [30]:
test1.head()

,State,Total/Sex,1978,1979,1980,1981,1982,1983,1984,1985,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,"National Statistics (U.S. Total) 15 , 16 ,...",Total,307276,314457,329821,369930,413806,436855,462002,502507,...,1596835,1608282,1615487,1613803,1598968,1570397,1576950,1562319,1526603,1505397
1,NaN,Male,294530,301462,316401,354393,396021,417835,441208,479359,...,1482524,1493670,1502002,1500936,1487561,1461625,1465592,1449291,1415112,1393975
2,NaN,Female,12746,12995,13420,15537,17785,19020,20794,23148,...,114311,114612,113485,112867,111407,108772,111358,113028,111491,111422
3,"Federal Institutions 15 , 16 , 17 , 18 ...",Total,29803,26371,24363,28133,29673,31926,34263,40223,...,199618,201280,208118,209771,216362,217815,215866,210567,196455,189192
4,NaN,Male,27975,24835,22964,26574,28046,30172,32267,37819,...,186280,188007,194493,196222,202462,203766,201697,196568,183502,176495

In [31]:
# Cleaning up the 'Total/Sex' column to just have Total, Male, and Female 

test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*A.*$)', 'Total')

C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [32]:
type(test1)

pandas.core.frame.DataFrame

In [35]:
test1.head(25)

,State,Total/Sex,1978,1979,1980,1981,1982,1983,1984,1985,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,"National Statistics (U.S. Total) 15 , 16 ,...",Total,307276,314457,329821,369930,413806,436855,462002,502507,...,1596835,1608282,1615487,1613803,1598968,1570397,1576950,1562319,1526603,1505397
1,NaN,Male,294530,301462,316401,354393,396021,417835,441208,479359,...,1482524,1493670,1502002,1500936,1487561,1461625,1465592,1449291,1415112,1393975
2,NaN,Female,12746,12995,13420,15537,17785,19020,20794,23148,...,114311,114612,113485,112867,111407,108772,111358,113028,111491,111422
3,"Federal Institutions 15 , 16 , 17 , 18 ...",Total,29803,26371,24363,28133,29673,31926,34263,40223,...,199618,201280,208118,209771,216362,217815,215866,210567,196455,189192
4,NaN,Male,27975,24835,22964,26574,28046,30172,32267,37819,...,186280,188007,194493,196222,202462,203766,201697,196568,183502,176495
5,NaN,Female,1828,1536,1399,1559,1627,1754,1996,2404,...,13338,13273,13625,13549,13900,14049,14169,13999,12953,12697
6,"State Institutions (Total) 21 , 22 , 23 ...",Total,277473,288086,305458,341797,384133,404929,427739,462284,...,1397217,1407002,1407369,1404032,1382606,1352582,1361084,1351752,1330148,1316205
7,NaN,Male,266555,276627,293437,327819,367975,387663,408941,441540,...,1296244,1305663,1307509,1304714,1285099,1257859,1263895,1252723,1231610,1217480
8,NaN,Female,10918,11459,12021,13978,16158,17266,18798,20744,...,100973,101339,99860,99318,97507,94723,97189,99029,98538,98725
9,"Alabama 33 , 34 , 35 , 36 , 37",Total,5625,5464,6543,7657,9233,9856,10482,11015,...,29412,30508,31874,31764,32270,32431,32381,31771,30810,28883
10,NaN,Male,5368,5221,6278,7339,8757,9375,9961,10453,...,27254,28277,29419,29261,29696,29782,29660,29182,28220,26506
11,NaN,Female,257,243,265,318,476,481,521,562,...,2158,2231,2455,2503,2574,2649,2721,2589,2590,2377
12,"Alaska 38 , 39 , 40 , 41 , 42 , 43 ...",Total,712,760,822,1024,1322,1631,1967,2329,...,5167,5014,5285,5391,5597,5633,5081,5794,5338,4434
13,NaN,Male,678,729,801,977,1276,1557,1888,2207,...,4603,4511,4696,4782,4932,4934,4450,5091,4761,4024
14,NaN,Female,34,31,21,47,46,74,79,122,...,564,503,589,609,665,699,631,703,577,410
15,"Arizona 60 , 61 , 62 , 63 , 64 , 65...",Total,3456,3749,4372,5223,6069,6889,7845,8531,...,37746,39502,40544,40209,40020,40080,41177,42259,42719,42320
16,NaN,Male,3275,3573,4153,4986,5788,6566,7482,8134,...,34286,35739,36768,36521,36470,36447,37402,38295,38738,38323
17,NaN,Female,181,176,219,237,281,323,363,397,...,3460,3763,3776,3688,3550,3633,3775,3964,3981,3997
18,"Arkansas 82 , 83 , 84 , 85 , 86 , 8...",Total,2654,3042,2911,3328,3922,4246,4482,4611,...,14314,14716,15208,16204,16108,14654,17235,17874,17707,17537
19,NaN,Male,2553,2927,2805,3197,3755,4050,4286,4394,...,13248,13656,14147,15040,14995,13594,15904,16476,16305,16161
20,NaN,Female,101,115,106,131,167,196,196,217,...,1066,1060,1061,1164,1113,1060,1331,1398,1402,1376
21,"California 66 , 91 , 92 , 93 , 94 , ...",Total,21325,22632,24569,29202,34640,39373,43197,50158,...,174282,173670,171275,165062,149569,134534,135981,136085,129593,130390
22,NaN,Male,20178,21400,23253,27775,32987,37353,40892,47248,...,162654,162050,160286,155104,141382,128436,129684,129703,123808,124487
23,NaN,Female,1147,1232,1316,1427,1653,2020,2305,2910,...,11628,11620,10989,9958,8187,6098,6297,6382,5785,5903
24,"Colorado 100 , 101 , 102 , 103 , 104 ...",Total,2486,2668,2629,2772,3042,3244,3231,3386,...,22841,23274,22795,22815,21978,20462,20371,20646,20041,19981

In [34]:
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*C.*$)', 'Total')

C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [36]:
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*D.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*Fl.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*G.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*H.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*I.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*K.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*L.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*Mai.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*Mar.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*Mas.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*Mi.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*Mo.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*N.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*O.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*P.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*R.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*S.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*Te.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*U.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*V.*$)', 'Total')
test1['Total/Sex'] = test['Total/Sex'].str.replace(r'(^.*W.*$)', 'Total')

C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\ivvya\Anaconda3\lib\site-packages\ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [37]:
test1

,State,Total/Sex,1978,1979,1980,1981,1982,1983,1984,1985,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,"National Statistics (U.S. Total) 15 , 16 ,...",Total,307276,314457,329821,369930,413806,436855,462002,502507,...,1596835,1608282,1615487,1613803,1598968,1570397,1576950,1562319,1526603,1505397
1,NaN,Male,294530,301462,316401,354393,396021,417835,441208,479359,...,1482524,1493670,1502002,1500936,1487561,1461625,1465592,1449291,1415112,1393975
2,NaN,Female,12746,12995,13420,15537,17785,19020,20794,23148,...,114311,114612,113485,112867,111407,108772,111358,113028,111491,111422
3,"Federal Institutions 15 , 16 , 17 , 18 ...",Total,29803,26371,24363,28133,29673,31926,34263,40223,...,199618,201280,208118,209771,216362,217815,215866,210567,196455,189192
4,NaN,Male,27975,24835,22964,26574,28046,30172,32267,37819,...,186280,188007,194493,196222,202462,203766,201697,196568,183502,176495
5,NaN,Female,1828,1536,1399,1559,1627,1754,1996,2404,...,13338,13273,13625,13549,13900,14049,14169,13999,12953,12697
6,"State Institutions (Total) 21 , 22 , 23 ...",Total,277473,288086,305458,341797,384133,404929,427739,462284,...,1397217,1407002,1407369,1404032,1382606,1352582,1361084,1351752,1330148,1316205
7,NaN,Male,266555,276627,293437,327819,367975,387663,408941,441540,...,1296244,1305663,1307509,1304714,1285099,1257859,1263895,1252723,1231610,1217480
8,NaN,Female,10918,11459,12021,13978,16158,17266,18798,20744,...,100973,101339,99860,99318,97507,94723,97189,99029,98538,98725
9,"Alabama 33 , 34 , 35 , 36 , 37",Total,5625,5464,6543,7657,9233,9856,10482,11015,...,29412,30508,31874,31764,32270,32431,32381,31771,30810,28883
10,NaN,Male,5368,5221,6278,7339,8757,9375,9961,10453,...,27254,28277,29419,29261,29696,29782,29660,29182,28220,26506
11,NaN,Female,257,243,265,318,476,481,521,562,...,2158,2231,2455,2503,2574,2649,2721,2589,2590,2377
12,"Alaska 38 , 39 , 40 , 41 , 42 , 43 ...",Total,712,760,822,1024,1322,1631,1967,2329,...,5167,5014,5285,5391,5597,5633,5081,5794,5338,4434
13,NaN,Male,678,729,801,977,1276,1557,1888,2207,...,4603,4511,4696,4782,4932,4934,4450,5091,4761,4024
14,NaN,Female,34,31,21,47,46,74,79,122,...,564,503,589,609,665,699,631,703,577,410
15,"Arizona 60 , 61 , 62 , 63 , 64 , 65...",Total,3456,3749,4372,5223,6069,6889,7845,8531,...,37746,39502,40544,40209,40020,40080,41177,42259,42719,42320
16,NaN,Male,3275,3573,4153,4986,5788,6566,7482,8134,...,34286,35739,36768,36521,36470,36447,37402,38295,38738,38323
17,NaN,Female,181,176,219,237,281,323,363,397,...,3460,3763,3776,3688,3550,3633,3775,3964,3981,3997
18,"Arkansas 82 , 83 , 84 , 85 , 86 , 8...",Total,2654,3042,2911,3328,3922,4246,4482,4611,...,14314,14716,15208,16204,16108,14654,17235,17874,17707,17537
19,NaN,Male,2553,2927,2805,3197,3755,4050,4286,4394,...,13248,13656,14147,15040,14995,13594,15904,16476,16305,16161
20,NaN,Female,101,115,106,131,167,196,196,217,...,1066,1060,1061,1164,1113,1060,1331,1398,1402,1376
21,"California 66 , 91 , 92 , 93 , 94 , ...",Total,21325,22632,24569,29202,34640,39373,43197,50158,...,174282,173670,171275,165062,149569,134534,135981,136085,129593,130390
22,NaN,Male,20178,21400,23253,27775,32987,37353,40892,47248,...,162654,162050,160286,155104,141382,128436,129684,129703,123808,124487
23,NaN,Female,1147,1232,1316,1427,1653,2020,2305,2910,...,11628,11620,10989,9958,8187,6098,6297,6382,5785,5903
24,"Colorado 100 , 101 , 102 , 103 , 104 ...",Total,2486,2668,2629,2772,3042,3244,3231,3386,...,22841,23274,22795,22815,21978,20462,20371,20646,20041,19981
25,NaN,Male,2419,2587,2560,2691,2923,3108,3091,3238,...,20506,20980,20694,20763,19957,18739,18556,18738,18199,18078
26,NaN,Female,67,81,69,81,119,136,140,148,...,2335,2294,2101,2052,2021,1723,1815,1908,1842,1903
27,"Connecticut 38 , 41 , 43 , 47 , 58 ,...",Total,3189,4061,4308,5263,5156,5474,5718,6149,...,20924,20661,19716,19321,18324,17530,17563,16636,15816,14957
28,NaN,Male,3044,3919,4102,5011,4952,5193,5431,5826,...,19428,19159,18381,18075,17090,16312,16328,15510,14695,13892
29,NaN,Female,145,142,206,252,204,281,287,323,...,1496,1502,1335,1246,1234,1218,1235,1126,1121,1065
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,"South Dakota 543 , 544 , 545",Total,532,562,635,693,791,826,921,1049,...,3311,3342,3434,3434,3535,3650,3682,3608,3564,3831
133,NaN,Male,514,538,617,664,748,785,889,1008,...,2942,2987,3054,3023,3094,3227,3240,3199,3148,3333
134,NaN,Female,18,24,18,29,43,41,32,41,...,369,355,380,411,441,423,442,409,416,498
135,"Tennessee 177 , 230 , 231 , 232 , 233...",Total,5835,6629,7022,7897,7869,8201,7307,7127,...,26267,27228,26965,27451,28479,28411,28521,28769,28172,28203
136,NaN,Male,5574,6346,6686,7502,7489,7803,6993,6825,...,24344,25099,24956,25345,26070,26048,26069,26160,25532,25481
137,NaN,Female,261,283,336,395,380,398,314,302,...,1923,2129,2009,2106,2409,2363,2452,2609,2640,2722
138,"Texas 66 , 91 , 218 , 231 , 565 , 5...",Total,24575,26522,29892,31502,36149,35259,36682,37532,...,171790,172506,171249,173649,172224,166372,168280,166043,163909,163703
139,NaN,Male,23570,25355,28671,30050,34472,33789,34987,35938,...,157859,158653,157679,159298,158036,152823,154450,151717,149501,149368
140,NaN,Female,1005,1167,1221,1452,1677,1470,1695,1594,...,13931,13853,13570,14351,14188,13549,13830,14326,14408,14335
141,"Utah 223 , 576 , 579 , 580 , 581 , 582",Total,911,960,932,1140,1216,1274,1504,1633,...,6515,6552,6538,6807,6879,6962,7077,7031,6495,6182
142,NaN,Male,875,926,905,1099,1169,1223,1456,1570,...,5883,5912,5956,6199,6266,6323,6415,6369,5980,5777
143,NaN,Female,36,34,27,41,47,51,48,63,...,632,640,582,608,613,639,662,662,515,405
144,"Vermont 38 , 41 , 47 , 128 , 528 , ...",Total,441,431,480,534,599,497,501,677,...,2116,2116,2220,2079,2053,2034,2078,1979,1750,1735
145,NaN,Male,430,420,464,519,582,488,488,660,...,1998,1998,2065,1930,1905,1907,1924,1823,1600,1600
146,NaN,Female,11,11,16,15,17,9,13,17,...,118,118,155,149,148,127,154,156,150,135
147,"Virginia 416 , 420 , 610 , 611 , 612 ...",Total,8344,8449,8920,9388,10079,10093,10839,12073,...,37984,38216,38059,37638,38130,37044,36982,37544,38403,37813
148,NaN,Male,7985,8148,8617,9040,9715,9712,10406,11604,...,35055,35249,35156,34790,35321,34150,34133,34529,35167,34704
149,NaN,Female,359,301,303,348,364,381,433,469,...,2929,2967,2903,2848,2809,2894,2849,3015,3236,3109
150,"Washington 416 , 624 , 625 , 626 , 62...",Total,4487,4342,4399,5336,6264,6658,6821,6919,...,17772,17926,18233,18235,17847,17271,17984,18120,18284,19104
151,NaN,Male,4251,4137,4209,5124,6018,6416,6567,6689,...,16258,16522,16836,16808,16452,15934,16535,16666,16829,17446
152,NaN,Female,236,205,190,212,246,242,254,230,...,1514,1404,1397,1427,1395,1337,1449,1454,1455,1658
153,"West Virginia 65 , 66 , 633 , 634 , 6...",Total,1237,1251,1257,1565,1547,1611,1579,1725,...,6056,6059,6367,6681,6826,7070,6824,6896,7118,7162
154,NaN,Male,1208,1218,1227,1528,1500,1553,1528,1658,...,5422,5411,5683,5956,6074,6265,6016,6065,6253,6286
155,NaN,Female,29,33,30,37,47,58,51,67,...,634,648,684,725,752,805,808,831,865,876
156,"Wisconsin 643 , 644 , 645 , 646 , 647...",Total,3432,3677,3980,4385,4714,4845,4974,5425,...,23743,23379,23165,22729,22657,22600,22471,22597,22975,23377
157,NaN,Male,3285,3532,3826,4216,4517,4632,4747,5174,...,22216,22022,21859,21465,21472,21375,21232,21219,21567,21889
158,NaN,Female,147,145,154,169,197,213,227,251,...,1527,1357,1306,1264,1185,1225,1239,1378,1408,1488
159,"Wyoming 66 , 656 , 657 , 658 , 659 ,...",Total,433,504,534,556,702,721,724,762,...,2084,2084,2075,2112,2183,2204,2310,2383,2424,2374
160,NaN,Male,414,474,505,532,674,688,685,716,...,1838,1876,1861,1881,1944,1966,2050,2106,2157,2088
161,NaN,Female,19,30,29,24,28,33,39,46,...,246,208,214,231,239,238,260,277,267,286

## Fill the null rows with the non-null column value above
### Fill respective state rows which were previous null in "State" column

In [38]:

test1['State'].fillna( method ='ffill', inplace = True)

C:\Users\ivvya\Anaconda3\lib\site-packages\pandas\core\generic.py:6130: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)

In [39]:
test1.head(10)

,State,Total/Sex,1978,1979,1980,1981,1982,1983,1984,1985,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,"National Statistics (U.S. Total) 15 , 16 ,...",Total,307276,314457,329821,369930,413806,436855,462002,502507,...,1596835,1608282,1615487,1613803,1598968,1570397,1576950,1562319,1526603,1505397
1,"National Statistics (U.S. Total) 15 , 16 ,...",Male,294530,301462,316401,354393,396021,417835,441208,479359,...,1482524,1493670,1502002,1500936,1487561,1461625,1465592,1449291,1415112,1393975
2,"National Statistics (U.S. Total) 15 , 16 ,...",Female,12746,12995,13420,15537,17785,19020,20794,23148,...,114311,114612,113485,112867,111407,108772,111358,113028,111491,111422
3,"Federal Institutions 15 , 16 , 17 , 18 ...",Total,29803,26371,24363,28133,29673,31926,34263,40223,...,199618,201280,208118,209771,216362,217815,215866,210567,196455,189192
4,"Federal Institutions 15 , 16 , 17 , 18 ...",Male,27975,24835,22964,26574,28046,30172,32267,37819,...,186280,188007,194493,196222,202462,203766,201697,196568,183502,176495
5,"Federal Institutions 15 , 16 , 17 , 18 ...",Female,1828,1536,1399,1559,1627,1754,1996,2404,...,13338,13273,13625,13549,13900,14049,14169,13999,12953,12697
6,"State Institutions (Total) 21 , 22 , 23 ...",Total,277473,288086,305458,341797,384133,404929,427739,462284,...,1397217,1407002,1407369,1404032,1382606,1352582,1361084,1351752,1330148,1316205
7,"State Institutions (Total) 21 , 22 , 23 ...",Male,266555,276627,293437,327819,367975,387663,408941,441540,...,1296244,1305663,1307509,1304714,1285099,1257859,1263895,1252723,1231610,1217480
8,"State Institutions (Total) 21 , 22 , 23 ...",Female,10918,11459,12021,13978,16158,17266,18798,20744,...,100973,101339,99860,99318,97507,94723,97189,99029,98538,98725
9,"Alabama 33 , 34 , 35 , 36 , 37",Total,5625,5464,6543,7657,9233,9856,10482,11015,...,29412,30508,31874,31764,32270,32431,32381,31771,30810,28883

### Clean State Column values
### Ex: each row should be state name or Institution name. Get rid of the numbers in the column

In [40]:
test1.State = test1.State.apply(lambda x: 'National Statistics' if 'National Statistics' in x else x)
test1.State = test1.State.apply(lambda x: 'Federal Institutions' if 'Federal Institutions' in x else x)
test1.State = test1.State.apply(lambda x: 'State Institutions' if 'State Institutions' in x else x)
test1.State = test1.State.apply(lambda x: 'Alabama' if 'Alabama' in x else x)
test1.State = test1.State.apply(lambda x: 'Alaska' if 'Alaska' in x else x)
test1.State = test1.State.apply(lambda x: 'Arizona' if 'Arizona' in x else x)
test1.State = test1.State.apply(lambda x: 'Arkansas' if 'Arkansas' in x else x)
test1.State = test1.State.apply(lambda x: 'California' if 'California' in x else x)
test1.State = test1.State.apply(lambda x: 'Connecticut' if 'Connecticut' in x else x)
test1.State = test1.State.apply(lambda x: 'Colorado' if 'Colorado' in x else x)
test1.State = test1.State.apply(lambda x: 'Delaware' if 'Delaware' in x else x)
test1.State = test1.State.apply(lambda x: 'District of Columbia' if 'District of Columbia' in x else x)
test1.State = test1.State.apply(lambda x: 'Florida' if 'Florida' in x else x)
test1.State = test1.State.apply(lambda x: 'Georgia' if 'Georgia' in x else x)
test1.State = test1.State.apply(lambda x: 'Hawaii' if 'Hawaii' in x else x)
test1.State = test1.State.apply(lambda x: 'Idaho' if 'Idaho' in x else x)
test1.State = test1.State.apply(lambda x: 'Illinois' if 'Illinois' in x else x)
test1.State = test1.State.apply(lambda x: 'Indiana' if 'Indiana' in x else x)
test1.State = test1.State.apply(lambda x: 'Iowa' if 'Iowa' in x else x)
test1.State = test1.State.apply(lambda x: 'Kansas' if 'Kansas' in x else x)
test1.State = test1.State.apply(lambda x: 'Kentucky' if 'Kentucky' in x else x)
test1.State = test1.State.apply(lambda x: 'Louisiana' if 'Louisiana' in x else x)
test1.State = test1.State.apply(lambda x: 'Maine' if 'Maine' in x else x)
test1.State = test1.State.apply(lambda x: 'Maryland' if 'Maryland' in x else x)
test1.State = test1.State.apply(lambda x: 'Massachusetts' if 'Massachusetts' in x else x)
test1.State = test1.State.apply(lambda x: 'Michigan' if 'Michigan' in x else x)
test1.State = test1.State.apply(lambda x: 'Minnesota' if 'Minnesota' in x else x)
test1.State = test1.State.apply(lambda x: 'Mississippi' if 'Mississippi' in x else x)
test1.State = test1.State.apply(lambda x: 'Missouri' if 'Missouri' in x else x)
test1.State = test1.State.apply(lambda x: 'Montana' if 'Montana' in x else x)
test1.State = test1.State.apply(lambda x: 'Nebraska' if 'Nebraska' in x else x)
test1.State = test1.State.apply(lambda x: 'Nevada' if 'Nevada' in x else x)
test1.State = test1.State.apply(lambda x: 'New Hampshire' if 'New Hampshire' in x else x)
test1.State = test1.State.apply(lambda x: 'New Jersey' if 'New Jersey' in x else x)
test1.State = test1.State.apply(lambda x: 'New Mexico' if 'New Mexico' in x else x)
test1.State = test1.State.apply(lambda x: 'New York' if 'New York' in x else x)
test1.State = test1.State.apply(lambda x: 'North Carolina' if 'North Carolina' in x else x)
test1.State = test1.State.apply(lambda x: 'North Dakota' if 'North Dakota' in x else x)
test1.State = test1.State.apply(lambda x: 'Ohio' if 'Ohio' in x else x)
test1.State = test1.State.apply(lambda x: 'Oklahoma' if 'Oklahoma' in x else x)
test1.State = test1.State.apply(lambda x: 'Oregon' if 'Oregon' in x else x)
test1.State = test1.State.apply(lambda x: 'Pennsylvania' if 'Pennsylvania' in x else x)
test1.State = test1.State.apply(lambda x: 'Rhode Island' if 'Rhode Island' in x else x)
test1.State = test1.State.apply(lambda x: 'South Carolina' if 'South Carolina' in x else x)
test1.State = test1.State.apply(lambda x: 'South Dakota' if 'South Dakota' in x else x)
test1.State = test1.State.apply(lambda x: 'Tennessee' if 'Tennessee' in x else x)
test1.State = test1.State.apply(lambda x: 'Texas' if 'Texas' in x else x)
test1.State = test1.State.apply(lambda x: 'Utah' if 'Utah' in x else x)
test1.State = test1.State.apply(lambda x: 'Vermont' if 'Vermont' in x else x)
test1.State = test1.State.apply(lambda x: 'Virginia' if 'Virginia' in x else x)
test1.State = test1.State.apply(lambda x: 'Washington' if 'Washington' in x else x)
test1.State = test1.State.apply(lambda x: 'West Virginia' if 'West Virginia' in x else x)
test1.State = test1.State.apply(lambda x: 'Wisconsin' if 'Wisconsin' in x else x)
test1.State = test1.State.apply(lambda x: 'Wyoming' if 'Wyoming' in x else x)

C:\Users\ivvya\Anaconda3\lib\site-packages\pandas\core\generic.py:5096: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [41]:
test1.head(10)

,State,Total/Sex,1978,1979,1980,1981,1982,1983,1984,1985,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,National Statistics,Total,307276,314457,329821,369930,413806,436855,462002,502507,...,1596835,1608282,1615487,1613803,1598968,1570397,1576950,1562319,1526603,1505397
1,National Statistics,Male,294530,301462,316401,354393,396021,417835,441208,479359,...,1482524,1493670,1502002,1500936,1487561,1461625,1465592,1449291,1415112,1393975
2,National Statistics,Female,12746,12995,13420,15537,17785,19020,20794,23148,...,114311,114612,113485,112867,111407,108772,111358,113028,111491,111422
3,Federal Institutions,Total,29803,26371,24363,28133,29673,31926,34263,40223,...,199618,201280,208118,209771,216362,217815,215866,210567,196455,189192
4,Federal Institutions,Male,27975,24835,22964,26574,28046,30172,32267,37819,...,186280,188007,194493,196222,202462,203766,201697,196568,183502,176495
5,Federal Institutions,Female,1828,1536,1399,1559,1627,1754,1996,2404,...,13338,13273,13625,13549,13900,14049,14169,13999,12953,12697
6,State Institutions,Total,277473,288086,305458,341797,384133,404929,427739,462284,...,1397217,1407002,1407369,1404032,1382606,1352582,1361084,1351752,1330148,1316205
7,State Institutions,Male,266555,276627,293437,327819,367975,387663,408941,441540,...,1296244,1305663,1307509,1304714,1285099,1257859,1263895,1252723,1231610,1217480
8,State Institutions,Female,10918,11459,12021,13978,16158,17266,18798,20744,...,100973,101339,99860,99318,97507,94723,97189,99029,98538,98725
9,Alabama,Total,5625,5464,6543,7657,9233,9856,10482,11015,...,29412,30508,31874,31764,32270,32431,32381,31771,30810,28883

In [42]:
# Confirm that every state name has been changed
test1['State'].unique()

array(['National Statistics', 'Federal Institutions',
       'State Institutions', 'Alabama', 'Alaska', 'Arizona', 'Arkansas',
       'California', 'Colorado', 'Connecticut', 'Delaware',
       'District of Columbia', 'Florida', 'Georgia', 'Hawaii', 'Idaho',
       'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana',
       'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota',
       'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada',
       'New Hampshire', 'New Jersey', 'New Mexico', 'New York',
       'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon',
       'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota',
       'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'Wisconsin', 'Wyoming'], dtype=object)

In [82]:
# Export the prison dataframe to csv
test1.to_csv('Data/prison_data.csv')

## Loading data to Mongodb

In [69]:
import pymongo
from pprint import pprint

In [76]:
# Set up Mongo Connection
conn = "mongodb://localhost:27017"
client = pymongo.MongoClient(conn)

In [88]:
## Set up Mongo Database and Collection
db = client.incarceration
collection = db.jail_collection
db.collection.drop()

In [84]:
# Make year columns into strings to make into dictionary
test1.columns = test1.columns.astype(str)

In [85]:
list(test1.columns)

['State', 'Total/Sex', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016']

In [89]:
collection.insert_many(test1.to_dict('records'))

In [87]:
pprint(list(jail_collection.find()))

[{'1978': '307276',
  '1979': 314457,
  '1980': 329821,
  '1981': 369930,
  '1982': 413806,
  '1983': 436855,
  '1984': 462002,
  '1985': 502507,
  '1986': 544972,
  '1987': 585084,
  '1988': 627600,
  '1989': 712364,
  '1990': 773919,
  '1991': 825559,
  '1992': 882500,
  '1993': 969301,
  '1994': 1054702,
  '1995': 1125874,
  '1996': 1181919,
  '1997': 1240659,
  '1998': 1307154,
  '1999': 1363686,
  '2000': 1394231,
  '2001': 1404032,
  '2002': 1440144,
  '2003': 1468601,
  '2004': 1497100,
  '2005': 1525910,
  '2006': 1568674,
  '2007': 1596835,
  '2008': 1608282,
  '2009': 1615487,
  '2010': 1613803,
  '2011': 1598968,
  '2012': 1570397,
  '2013': 1576950,
  '2014': 1562319,
  '2015': 1526603,
  '2016': 1505397,
  'State': 'National Statistics',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d064b')},
 {'1978': '294530',
  '1979': 301462,
  '1980': 316401,
  '1981': 354393,
  '1982': 396021,
  '1983': 417835,
  '1984': 441208,
  '1985': 479359,
  '1986': 518441,
  '1987': 555961,
  '1988': 594996,
  '1989': 671752,
  '1990': 729840,
  '1991': 777908,
  '1992': 832093,
  '1993': 911044,
  '1994': 990306,
  '1995': 1057406,
  '1996': 1107109,
  '1997': 1161468,
  '1998': 1222273,
  '1999': 1273258,
  '2000': 1300997,
  '2001': 1311053,
  '2002': 1342513,
  '2003': 1367755,
  '2004': 1392278,
  '2005': 1418392,
  '2006': 1456366,
  '2007': 1482524,
  '2008': 1493670,
  '2009': 1502002,
  '2010': 1500936,
  '2011': 1487561,
  '2012': 1461625,
  '2013': 1465592,
  '2014': 1449291,
  '2015': 1415112,
  '2016': 1393975,
  'State': 'National Statistics',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d064c')},
 {'1978': '12746',
  '1979': 12995,
  '1980': 13420,
  '1981': 15537,
  '1982': 17785,
  '1983': 19020,
  '1984': 20794,
  '1985': 23148,
  '1986': 26531,
  '1987': 29123,
  '1988': 32604,
  '1989': 40612,
  '1990': 44079,
  '1991': 47651,
  '1992': 50407,
  '1993': 58257,
  '1994': 64396,
  '1995': 68468,
  '1996': 74810,
  '1997': 79191,
  '1998': 84881,
  '1999': 90428,
  '2000': 93234,
  '2001': 92979,
  '2002': 97631,
  '2003': 100846,
  '2004': 104822,
  '2005': 107518,
  '2006': 112308,
  '2007': 114311,
  '2008': 114612,
  '2009': 113485,
  '2010': 112867,
  '2011': 111407,
  '2012': 108772,
  '2013': 111358,
  '2014': 113028,
  '2015': 111491,
  '2016': 111422,
  'State': 'National Statistics',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d064d')},
 {'1978': '29803',
  '1979': 26371,
  '1980': 24363,
  '1981': 28133,
  '1982': 29673,
  '1983': 31926,
  '1984': 34263,
  '1985': 40223,
  '1986': 44408,
  '1987': 48300,
  '1988': 49928,
  '1989': 59171,
  '1990': 65526,
  '1991': 71608,
  '1992': 80259,
  '1993': 89587,
  '1994': 95034,
  '1995': 100250,
  '1996': 105544,
  '1997': 112973,
  '1998': 123041,
  '1999': 135246,
  '2000': 145416,
  '2001': 156993,
  '2002': 163528,
  '2003': 173059,
  '2004': 180328,
  '2005': 187618,
  '2006': 193046,
  '2007': 199618,
  '2008': 201280,
  '2009': 208118,
  '2010': 209771,
  '2011': 216362,
  '2012': 217815,
  '2013': 215866,
  '2014': 210567,
  '2015': 196455,
  '2016': 189192,
  'State': 'Federal Institutions',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d064e')},
 {'1978': '27975',
  '1979': 24835,
  '1980': 22964,
  '1981': 26574,
  '1982': 28046,
  '1983': 30172,
  '1984': 32267,
  '1985': 37819,
  '1986': 41575,
  '1987': 45273,
  '1988': 46686,
  '1989': 54736,
  '1990': 60515,
  '1991': 65954,
  '1992': 73860,
  '1993': 82696,
  '1994': 87894,
  '1995': 92852,
  '1996': 97844,
  '1997': 104667,
  '1998': 113855,
  '1999': 125333,
  '2000': 135171,
  '2001': 146020,
  '2002': 152294,
  '2003': 161424,
  '2004': 168164,
  '2005': 175196,
  '2006': 180071,
  '2007': 186280,
  '2008': 188007,
  '2009': 194493,
  '2010': 196222,
  '2011': 202462,
  '2012': 203766,
  '2013': 201697,
  '2014': 196568,
  '2015': 183502,
  '2016': 176495,
  'State': 'Federal Institutions',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d064f')},
 {'1978': '1828',
  '1979': 1536,
  '1980': 1399,
  '1981': 1559,
  '1982': 1627,
  '1983': 1754,
  '1984': 1996,
  '1985': 2404,
  '1986': 2833,
  '1987': 3027,
  '1988': 3242,
  '1989': 4435,
  '1990': 5011,
  '1991': 5654,
  '1992': 6399,
  '1993': 6891,
  '1994': 7140,
  '1995': 7398,
  '1996': 7700,
  '1997': 8306,
  '1998': 9186,
  '1999': 9913,
  '2000': 10245,
  '2001': 10973,
  '2002': 11234,
  '2003': 11635,
  '2004': 12164,
  '2005': 12422,
  '2006': 12975,
  '2007': 13338,
  '2008': 13273,
  '2009': 13625,
  '2010': 13549,
  '2011': 13900,
  '2012': 14049,
  '2013': 14169,
  '2014': 13999,
  '2015': 12953,
  '2016': 12697,
  'State': 'Federal Institutions',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d0650')},
 {'1978': '277473',
  '1979': 288086,
  '1980': 305458,
  '1981': 341797,
  '1982': 384133,
  '1983': 404929,
  '1984': 427739,
  '1985': 462284,
  '1986': 500564,
  '1987': 536784,
  '1988': 577672,
  '1989': 653193,
  '1990': 708393,
  '1991': 753951,
  '1992': 802241,
  '1993': 879714,
  '1994': 959668,
  '1995': 1025624,
  '1996': 1076375,
  '1997': 1127686,
  '1998': 1184113,
  '1999': 1228440,
  '2000': 1248815,
  '2001': 1247039,
  '2002': 1276616,
  '2003': 1295542,
  '2004': 1316772,
  '2005': 1338292,
  '2006': 1375628,
  '2007': 1397217,
  '2008': 1407002,
  '2009': 1407369,
  '2010': 1404032,
  '2011': 1382606,
  '2012': 1352582,
  '2013': 1361084,
  '2014': 1351752,
  '2015': 1330148,
  '2016': 1316205,
  'State': 'State Institutions',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d0651')},
 {'1978': '266555',
  '1979': 276627,
  '1980': 293437,
  '1981': 327819,
  '1982': 367975,
  '1983': 387663,
  '1984': 408941,
  '1985': 441540,
  '1986': 476866,
  '1987': 510688,
  '1988': 548310,
  '1989': 617016,
  '1990': 669325,
  '1991': 711954,
  '1992': 758233,
  '1993': 828348,
  '1994': 902412,
  '1995': 964554,
  '1996': 1009265,
  '1997': 1056801,
  '1998': 1108418,
  '1999': 1147925,
  '2000': 1165826,
  '2001': 1165033,
  '2002': 1190219,
  '2003': 1206331,
  '2004': 1224114,
  '2005': 1243196,
  '2006': 1276295,
  '2007': 1296244,
  '2008': 1305663,
  '2009': 1307509,
  '2010': 1304714,
  '2011': 1285099,
  '2012': 1257859,
  '2013': 1263895,
  '2014': 1252723,
  '2015': 1231610,
  '2016': 1217480,
  'State': 'State Institutions',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d0652')},
 {'1978': '10918',
  '1979': 11459,
  '1980': 12021,
  '1981': 13978,
  '1982': 16158,
  '1983': 17266,
  '1984': 18798,
  '1985': 20744,
  '1986': 23698,
  '1987': 26096,
  '1988': 29362,
  '1989': 36177,
  '1990': 39068,
  '1991': 41997,
  '1992': 44008,
  '1993': 51366,
  '1994': 57256,
  '1995': 61070,
  '1996': 67110,
  '1997': 70885,
  '1998': 75695,
  '1999': 80515,
  '2000': 82989,
  '2001': 82006,
  '2002': 86397,
  '2003': 89211,
  '2004': 92658,
  '2005': 95096,
  '2006': 99333,
  '2007': 100973,
  '2008': 101339,
  '2009': 99860,
  '2010': 99318,
  '2011': 97507,
  '2012': 94723,
  '2013': 97189,
  '2014': 99029,
  '2015': 98538,
  '2016': 98725,
  'State': 'State Institutions',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d0653')},
 {'1978': '5625',
  '1979': 5464,
  '1980': 6543,
  '1981': 7657,
  '1982': 9233,
  '1983': 9856,
  '1984': 10482,
  '1985': 11015,
  '1986': 11710,
  '1987': 12827,
  '1988': 12610,
  '1989': 13907,
  '1990': 15665,
  '1991': 16760,
  '1992': 17453,
  '1993': 18624,
  '1994': 19573,
  '1995': 20718,
  '1996': 21760,
  '1997': 22290,
  '1998': 22676,
  '1999': 24658,
  '2000': 26406,
  '2001': 26741,
  '2002': 27947,
  '2003': 27913,
  '2004': 25887,
  '2005': 27888,
  '2006': 28241,
  '2007': 29412,
  '2008': 30508,
  '2009': 31874,
  '2010': 31764,
  '2011': 32270,
  '2012': 32431,
  '2013': 32381,
  '2014': 31771,
  '2015': 30810,
  '2016': 28883,
  'State': 'Alabama',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d0654')},
 {'1978': '5368',
  '1979': 5221,
  '1980': 6278,
  '1981': 7339,
  '1982': 8757,
  '1983': 9375,
  '1984': 9961,
  '1985': 10453,
  '1986': 11094,
  '1987': 12095,
  '1988': 11858,
  '1989': 13062,
  '1990': 14710,
  '1991': 15705,
  '1992': 16352,
  '1993': 17493,
  '1994': 18359,
  '1995': 19423,
  '1996': 20403,
  '1997': 20930,
  '1998': 21215,
  '1999': 22990,
  '2000': 24580,
  '2001': 24958,
  '2002': 26250,
  '2003': 25910,
  '2004': 24139,
  '2005': 25923,
  '2006': 26191,
  '2007': 27254,
  '2008': 28277,
  '2009': 29419,
  '2010': 29261,
  '2011': 29696,
  '2012': 29782,
  '2013': 29660,
  '2014': 29182,
  '2015': 28220,
  '2016': 26506,
  'State': 'Alabama',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d0655')},
 {'1978': '257',
  '1979': 243,
  '1980': 265,
  '1981': 318,
  '1982': 476,
  '1983': 481,
  '1984': 521,
  '1985': 562,
  '1986': 616,
  '1987': 732,
  '1988': 752,
  '1989': 845,
  '1990': 955,
  '1991': 1055,
  '1992': 1101,
  '1993': 1131,
  '1994': 1214,
  '1995': 1295,
  '1996': 1357,
  '1997': 1360,
  '1998': 1461,
  '1999': 1668,
  '2000': 1826,
  '2001': 1783,
  '2002': 1697,
  '2003': 2003,
  '2004': 1748,
  '2005': 1965,
  '2006': 2050,
  '2007': 2158,
  '2008': 2231,
  '2009': 2455,
  '2010': 2503,
  '2011': 2574,
  '2012': 2649,
  '2013': 2721,
  '2014': 2589,
  '2015': 2590,
  '2016': 2377,
  'State': 'Alabama',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d0656')},
 {'1978': '712',
  '1979': 760,
  '1980': 822,
  '1981': 1024,
  '1982': 1322,
  '1983': 1631,
  '1984': 1967,
  '1985': 2329,
  '1986': 2460,
  '1987': 2528,
  '1988': 2588,
  '1989': 2744,
  '1990': 2622,
  '1991': 2706,
  '1992': 2865,
  '1993': 2703,
  '1994': 3292,
  '1995': 3522,
  '1996': 3716,
  '1997': 4165,
  '1998': 4097,
  '1999': 3949,
  '2000': 4173,
  '2001': 4571,
  '2002': 4398,
  '2003': 4527,
  '2004': 4554,
  '2005': 4812,
  '2006': 5069,
  '2007': 5167,
  '2008': 5014,
  '2009': 5285,
  '2010': 5391,
  '2011': 5597,
  '2012': 5633,
  '2013': 5081,
  '2014': 5794,
  '2015': 5338,
  '2016': 4434,
  'State': 'Alaska',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d0657')},
 {'1978': '678',
  '1979': 729,
  '1980': 801,
  '1981': 977,
  '1982': 1276,
  '1983': 1557,
  '1984': 1888,
  '1985': 2207,
  '1986': 2344,
  '1987': 2408,
  '1988': 2465,
  '1989': 2583,
  '1990': 2494,
  '1991': 2574,
  '1992': 2716,
  '1993': 2581,
  '1994': 3074,
  '1995': 3279,
  '1996': 3446,
  '1997': 3861,
  '1998': 3795,
  '1999': 3661,
  '2000': 3889,
  '2001': 4212,
  '2002': 4049,
  '2003': 4135,
  '2004': 4157,
  '2005': 4347,
  '2006': 4551,
  '2007': 4603,
  '2008': 4511,
  '2009': 4696,
  '2010': 4782,
  '2011': 4932,
  '2012': 4934,
  '2013': 4450,
  '2014': 5091,
  '2015': 4761,
  '2016': 4024,
  'State': 'Alaska',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d0658')},
 {'1978': '34',
  '1979': 31,
  '1980': 21,
  '1981': 47,
  '1982': 46,
  '1983': 74,
  '1984': 79,
  '1985': 122,
  '1986': 116,
  '1987': 120,
  '1988': 123,
  '1989': 161,
  '1990': 128,
  '1991': 132,
  '1992': 149,
  '1993': 122,
  '1994': 218,
  '1995': 243,
  '1996': 270,
  '1997': 304,
  '1998': 302,
  '1999': 288,
  '2000': 284,
  '2001': 359,
  '2002': 349,
  '2003': 392,
  '2004': 397,
  '2005': 465,
  '2006': 518,
  '2007': 564,
  '2008': 503,
  '2009': 589,
  '2010': 609,
  '2011': 665,
  '2012': 699,
  '2013': 631,
  '2014': 703,
  '2015': 577,
  '2016': 410,
  'State': 'Alaska',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d0659')},
 {'1978': '3456',
  '1979': 3749,
  '1980': 4372,
  '1981': 5223,
  '1982': 6069,
  '1983': 6889,
  '1984': 7845,
  '1985': 8531,
  '1986': 9434,
  '1987': 10948,
  '1988': 12095,
  '1989': 13251,
  '1990': 14261,
  '1991': 15415,
  '1992': 16477,
  '1993': 17811,
  '1994': 19746,
  '1995': 21341,
  '1996': 22493,
  '1997': 23484,
  '1998': 25515,
  '1999': 25986,
  '2000': 26510,
  '2001': 27710,
  '2002': 29359,
  '2003': 31170,
  '2004': 32515,
  '2005': 33471,
  '2006': 35801,
  '2007': 37746,
  '2008': 39502,
  '2009': 40544,
  '2010': 40209,
  '2011': 40020,
  '2012': 40080,
  '2013': 41177,
  '2014': 42259,
  '2015': 42719,
  '2016': 42320,
  'State': 'Arizona',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d065a')},
 {'1978': '3275',
  '1979': 3573,

  '1980': 4153,
  '1981': 4986,
  '1982': 5788,
  '1983': 6566,
  '1984': 7482,
  '1985': 8134,
  '1986': 8948,
  '1987': 10339,
  '1988': 11381,
  '1989': 12471,
  '1990': 13426,
  '1991': 14476,
  '1992': 15476,
  '1993': 16774,
  '1994': 18473,
  '1995': 19909,
  '1996': 20978,
  '1997': 21924,
  '1998': 23718,
  '1999': 24131,
  '2000': 24546,
  '2001': 25542,
  '2002': 26931,
  '2003': 28514,
  '2004': 29750,
  '2005': 30575,
  '2006': 32650,
  '2007': 34286,
  '2008': 35739,
  '2009': 36768,
  '2010': 36521,
  '2011': 36470,
  '2012': 36447,
  '2013': 37402,
  '2014': 38295,
  '2015': 38738,
  '2016': 38323,
  'State': 'Arizona',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d065b')},
 {'1978': '181',
  '1979': 176,
  '1980': 219,
  '1981': 237,
  '1982': 281,
  '1983': 323,
  '1984': 363,
  '1985': 397,
  '1986': 486,
  '1987': 609,
  '1988': 714,
  '1989': 780,
  '1990': 835,
  '1991': 939,
  '1992': 1001,
  '1993': 1037,
  '1994': 1273,
  '1995': 1432,
  '1996': 1515,
  '1997': 1560,
  '1998': 1797,
  '1999': 1855,
  '2000': 1964,
  '2001': 2168,
  '2002': 2428,
  '2003': 2656,
  '2004': 2765,
  '2005': 2896,
  '2006': 3151,
  '2007': 3460,
  '2008': 3763,
  '2009': 3776,
  '2010': 3688,
  '2011': 3550,
  '2012': 3633,
  '2013': 3775,
  '2014': 3964,
  '2015': 3981,
  '2016': 3997,
  'State': 'Arizona',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d065c')},
 {'1978': '2654',
  '1979': 3042,
  '1980': 2911,
  '1981': 3328,
  '1982': 3922,
  '1983': 4246,
  '1984': 4482,
  '1985': 4611,
  '1986': 4701,
  '1987': 5441,
  '1988': 5519,
  '1989': 6649,
  '1990': 7322,
  '1991': 7766,
  '1992': 8285,
  '1993': 8625,
  '1994': 8957,
  '1995': 8910,
  '1996': 9407,
  '1997': 10021,
  '1998': 10638,
  '1999': 11415,
  '2000': 11915,
  '2001': 12594,
  '2002': 13091,
  '2003': 13315,
  '2004': 13807,
  '2005': 13511,
  '2006': 13729,
  '2007': 14314,
  '2008': 14716,
  '2009': 15208,
  '2010': 16204,
  '2011': 16108,
  '2012': 14654,
  '2013': 17235,
  '2014': 17874,
  '2015': 17707,
  '2016': 17537,
  'State': 'Arkansas',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d065d')},
 {'1978': '2553',
  '1979': 2927,
  '1980': 2805,
  '1981': 3197,
  '1982': 3755,
  '1983': 4050,
  '1984': 4286,
  '1985': 4394,
  '1986': 4477,
  '1987': 5179,
  '1988': 5224,
  '1989': 6206,
  '1990': 6887,
  '1991': 7329,
  '1992': 7821,
  '1993': 8130,
  '1994': 8388,
  '1995': 8387,
  '1996': 8859,
  '1997': 9410,
  '1998': 9942,
  '1999': 10627,
  '2000': 11143,
  '2001': 11743,
  '2002': 12237,
  '2003': 12449,
  '2004': 12845,
  '2005': 12367,
  '2006': 12687,
  '2007': 13248,
  '2008': 13656,
  '2009': 14147,
  '2010': 15040,
  '2011': 14995,
  '2012': 13594,
  '2013': 15904,
  '2014': 16476,
  '2015': 16305,
  '2016': 16161,
  'State': 'Arkansas',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d065e')},
 {'1978': '101',
  '1979': 115,
  '1980': 106,
  '1981': 131,
  '1982': 167,
  '1983': 196,
  '1984': 196,
  '1985': 217,
  '1986': 224,
  '1987': 262,
  '1988': 295,
  '1989': 443,
  '1990': 435,
  '1991': 437,
  '1992': 464,
  '1993': 495,
  '1994': 569,
  '1995': 523,
  '1996': 548,
  '1997': 611,
  '1998': 696,
  '1999': 788,
  '2000': 772,
  '2001': 851,
  '2002': 854,
  '2003': 866,
  '2004': 962,
  '2005': 1144,
  '2006': 1042,
  '2007': 1066,
  '2008': 1060,
  '2009': 1061,
  '2010': 1164,
  '2011': 1113,
  '2012': 1060,
  '2013': 1331,
  '2014': 1398,
  '2015': 1402,
  '2016': 1376,
  'State': 'Arkansas',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d065f')},
 {'1978': '21325',
  '1979': 22632,
  '1980': 24569,
  '1981': 29202,
  '1982': 34640,
  '1983': 39373,
  '1984': 43197,
  '1985': 50158,
  '1986': 59484,
  '1987': 66975,
  '1988': 76171,
  '1989': 87297,
  '1990': 97309,
  '1991': 101808,
  '1992': 109496,
  '1993': 119951,
  '1994': 126091,
  '1995': 135646,
  '1996': 146049,
  '1997': 155790,
  '1998': 161904,
  '1999': 163067,
  '2000': 163001,
  '2001': 159444,
  '2002': 161361,
  '2003': 164487,
  '2004': 166556,
  '2005': 170676,
  '2006': 175512,
  '2007': 174282,
  '2008': 173670,
  '2009': 171275,
  '2010': 165062,
  '2011': 149569,
  '2012': 134534,
  '2013': 135981,
  '2014': 136085,
  '2015': 129593,
  '2016': 130390,
  'State': 'California',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d0660')},
 {'1978': '20178',
  '1979': 21400,
  '1980': 23253,
  '1981': 27775,
  '1982': 32987,
  '1983': 37353,
  '1984': 40892,
  '1985': 47248,
  '1986': 55920,
  '1987': 62823,
  '1988': 71278,
  '1989': 81297,
  '1990': 90807,
  '1991': 95506,
  '1992': 102749,
  '1993': 112370,
  '1994': 117846,
  '1995': 126564,
  '1996': 135942,
  '1997': 144876,
  '1998': 150210,
  '1999': 151699,
  '2000': 151840,
  '2001': 149523,
  '2002': 151374,
  '2003': 153831,
  '2004': 155368,
  '2005': 159009,
  '2006': 163535,
  '2007': 162654,
  '2008': 162050,
  '2009': 160286,
  '2010': 155104,
  '2011': 141382,
  '2012': 128436,
  '2013': 129684,
  '2014': 129703,
  '2015': 123808,
  '2016': 124487,
  'State': 'California',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d0661')},
 {'1978': '1147',
  '1979': 1232,
  '1980': 1316,
  '1981': 1427,
  '1982': 1653,
  '1983': 2020,
  '1984': 2305,
  '1985': 2910,
  '1986': 3564,
  '1987': 4152,
  '1988': 4893,
  '1989': 6000,
  '1990': 6502,
  '1991': 6302,
  '1992': 6747,
  '1993': 7581,
  '1994': 8245,
  '1995': 9082,
  '1996': 10107,
  '1997': 10914,
  '1998': 11694,
  '1999': 11368,
  '2000': 11161,
  '2001': 9921,
  '2002': 9987,
  '2003': 10656,
  '2004': 11188,
  '2005': 11667,
  '2006': 11977,
  '2007': 11628,
  '2008': 11620,
  '2009': 10989,
  '2010': 9958,
  '2011': 8187,
  '2012': 6098,
  '2013': 6297,
  '2014': 6382,
  '2015': 5785,
  '2016': 5903,
  'State': 'California',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d0662')},
 {'1978': '2486',
  '1979': 2668,
  '1980': 2629,
  '1981': 2772,
  '1982': 3042,
  '1983': 3244,
  '1984': 3231,
  '1985': 3386,
  '1986': 3804,
  '1987': 4808,
  '1988': 5765,
  '1989': 6908,
  '1990': 7671,
  '1991': 8392,
  '1992': 8997,
  '1993': 9462,
  '1994': 10717,
  '1995': 11063,
  '1996': 12438,
  '1997': 13461,
  '1998': 14312,
  '1999': 15670,
  '2000': 16833,
  '2001': 17448,
  '2002': 18833,
  '2003': 19671,
  '2004': 20293,
  '2005': 21456,
  '2006': 22481,
  '2007': 22841,
  '2008': 23274,
  '2009': 22795,
  '2010': 22815,
  '2011': 21978,
  '2012': 20462,
  '2013': 20371,
  '2014': 20646,
  '2015': 20041,
  '2016': 19981,
  'State': 'Colorado',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d0663')},
 {'1978': '2419',
  '1979': 2587,
  '1980': 2560,
  '1981': 2691,
  '1982': 2923,
  '1983': 3108,
  '1984': 3091,
  '1985': 3238,
  '1986': 3627,
  '1987': 4565,
  '1988': 5488,
  '1989': 6513,
  '1990': 7238,
  '1991': 7939,
  '1992': 8470,
  '1993': 8920,
  '1994': 10047,
  '1995': 10350,
  '1996': 11593,
  '1997': 12512,
  '1998': 13242,
  '1999': 14457,
  '2000': 15500,
  '2001': 16073,
  '2002': 17267,
  '2003': 17935,
  '2004': 18393,
  '2005': 19336,
  '2006': 20179,
  '2007': 20506,
  '2008': 20980,
  '2009': 20694,
  '2010': 20763,
  '2011': 19957,
  '2012': 18739,
  '2013': 18556,
  '2014': 18738,
  '2015': 18199,
  '2016': 18078,
  'State': 'Colorado',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d0664')},
 {'1978': '67',
  '1979': 81,
  '1980': 69,
  '1981': 81,
  '1982': 119,
  '1983': 136,
  '1984': 140,
  '1985': 148,
  '1986': 177,
  '1987': 243,
  '1988': 277,
  '1989': 395,
  '1990': 433,
  '1991': 453,
  '1992': 527,
  '1993': 542,
  '1994': 670,
  '1995': 713,
  '1996': 845,
  '1997': 949,
  '1998': 1070,
  '1999': 1213,
  '2000': 1333,
  '2001': 1375,
  '2002': 1566,
  '2003': 1736,
  '2004': 1900,
  '2005': 2120,
  '2006': 2302,
  '2007': 2335,
  '2008': 2294,
  '2009': 2101,
  '2010': 2052,
  '2011': 2021,
  '2012': 1723,
  '2013': 1815,
  '2014': 1908,
  '2015': 1842,
  '2016': 1903,
  'State': 'Colorado',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d0665')},
 {'1978': '3189',
  '1979': 4061,
  '1980': 4308,
  '1981': 5263,
  '1982': 5156,
  '1983': 5474,
  '1984': 5718,
  '1985': 6149,
  '1986': 6905,
  '1987': 7511,
  '1988': 8005,
  '1989': 9301,
  '1990': 10500,
  '1991': 10977,
  '1992': 11403,
  '1993': 13691,
  '1994': 14380,
  '1995': 14802,
  '1996': 16571,
  '1997': 17241,
  '1998': 17605,
  '1999': 18639,
  '2000': 18355,
  '2001': 19196,
  '2002': 20720,
  '2003': 19846,
  '2004': 19497,
  '2005': 19442,
  '2006': 20566,
  '2007': 20924,
  '2008': 20661,
  '2009': 19716,
  '2010': 19321,
  '2011': 18324,
  '2012': 17530,
  '2013': 17563,
  '2014': 16636,
  '2015': 15816,
  '2016': 14957,
  'State': 'Connecticut',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d0666')},
 {'1978': '3044',
  '1979': 3919,
  '1980': 4102,
  '1981': 5011,
  '1982': 4952,
  '1983': 5193,
  '1984': 5431,
  '1985': 5826,
  '1986': 6510,
  '1987': 7059,
  '1988': 7455,
  '1989': 8654,
  '1990': 9817,
  '1991': 10317,
  '1992': 10693,
  '1993': 12697,
  '1994': 13381,
  '1995': 13827,
  '1996': 15191,
  '1997': 15840,
  '1998': 16248,
  '1999': 17180,
  '2000': 16949,
  '2001': 17749,
  '2002': 19026,
  '2003': 18298,
  '2004': 18009,
  '2005': 17953,
  '2006': 18972,
  '2007': 19428,
  '2008': 19159,
  '2009': 18381,
  '2010': 18075,
  '2011': 17090,
  '2012': 16312,
  '2013': 16328,
  '2014': 15510,
  '2015': 14695,
  '2016': 13892,
  'State': 'Connecticut',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d0667')},
 {'1978': '145',
  '1979': 142,
  '1980': 206,
  '1981': 252,
  '1982': 204,
  '1983': 281,
  '1984': 287,
  '1985': 323,
  '1986': 395,
  '1987': 452,
  '1988': 550,
  '1989': 647,
  '1990': 683,
  '1991': 660,
  '1992': 710,
  '1993': 994,
  '1994': 999,
  '1995': 975,
  '1996': 1380,
  '1997': 1401,
  '1998': 1357,
  '1999': 1459,
  '2000': 1406,
  '2001': 1447,
  '2002': 1694,
  '2003': 1548,
  '2004': 1488,
  '2005': 1489,
  '2006': 1594,
  '2007': 1496,
  '2008': 1502,
  '2009': 1335,
  '2010': 1246,
  '2011': 1234,
  '2012': 1218,
  '2013': 1235,
  '2014': 1126,
  '2015': 1121,
  '2016': 1065,
  'State': 'Connecticut',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d0668')},
 {'1978': '1325',
  '1979': 1419,
  '1980': 1474,
  '1981': 1712,
  '1982': 2068,
  '1983': 2198,
  '1984': 2202,
  '1985': 2553,
  '1986': 2833,
  '1987': 2982,
  '1988': 3197,
  '1989': 3458,
  '1990': 3471,
  '1991': 3717,
  '1992': 4062,
  '1993': 4210,
  '1994': 4466,
  '1995': 4836,
  '1996': 5110,
  '1997': 5435,
  '1998': 5558,
  '1999': 6983,
  '2000': 6921,
  '2001': 7003,
  '2002': 6778,
  '2003': 6794,
  '2004': 6927,
  '2005': 6944,
  '2006': 7186,
  '2007': 7257,
  '2008': 7057,
  '2009': 6775,
  '2010': 6615,
  '2011': 6739,
  '2012': 6914,
  '2013': 7004,
  '2014': 6955,
  '2015': 6654,
  '2016': 6585,
  'State': 'Delaware',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d0669')},
 {'1978': '1261',
  '1979': 1355,
  '1980': 1417,
  '1981': 1637,
  '1982': 1969,
  '1983': 2091,
  '1984': 2095,
  '1985': 2422,
  '1986': 2677,
  '1987': 2816,
  '1988': 3020,
  '1989': 3234,
  '1990': 3245,
  '1991': 3477,
  '1992': 3791,
  '1993': 3953,
  '1994': 4184,
  '1995': 4478,
  '1996': 4731,
  '1997': 5052,
  '1998': 5118,
  '1999': 6371,
  '2000': 6324,
  '2001': 6412,
  '2002': 6236,
  '2003': 6286,
  '2004': 6370,
  '2005': 6389,
  '2006': 6615,
  '2007': 6682,
  '2008': 6502,
  '2009': 6284,
  '2010': 6149,
  '2011': 6202,
  '2012': 6348,
  '2013': 6405,
  '2014': 6361,
  '2015': 6117,
  '2016': 6047,
  'State': 'Delaware',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d066a')},
 {'1978': '64',
  '1979': 64,
  '1980': 57,
  '1981': 75,
  '1982': 99,
  '1983': 107,
  '1984': 107,
  '1985': 131,
  '1986': 156,
  '1987': 166,
  '1988': 177,
  '1989': 224,
  '1990': 226,
  '1991': 240,
  '1992': 271,
  '1993': 257,
  '1994': 282,
  '1995': 358,
  '1996': 379,
  '1997': 383,
  '1998': 440,
  '1999': 612,
  '2000': 597,
  '2001': 591,
  '2002': 542,
  '2003': 508,
  '2004': 557,
  '2005': 555,
  '2006': 571,
  '2007': 575,
  '2008': 555,
  '2009': 491,
  '2010': 466,
  '2011': 537,
  '2012': 566,
  '2013': 599,
  '2014': 594,
  '2015': 537,
  '2016': 538,
  'State': 'Delaware',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d066b')},
 {'1978': '2864',
  '1979': 2973,
  '1980': 3145,
  '1981': 3479,
  '1982': 4081,
  '1983': 4344,
  '1984': 4521,
  '1985': 6404,
  '1986': 6618,
  '1987': 7645,
  '1988': 8831,
  '1989': 9954,
  '1990': 9947,
  '1991': 10455,
  '1992': 10875,
  '1993': 10845,
  '1994': 10949,
  '1995': 9800,
  '1996': 9376,

  '1997': 9353,
  '1998': 9829,
  '1999': 8652,
  '2000': 10352,
  '2001': 0,
  '2002': 0,
  '2003': 0,
  '2004': 0,
  '2005': 0,
  '2006': 0,
  '2007': 0,
  '2008': 0,
  '2009': 0,
  '2010': 0,
  '2011': 0,
  '2012': 0,
  '2013': 0,
  '2014': 0,
  '2015': 0,
  '2016': 0,
  'State': 'District of Columbia',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d066c')},
 {'1978': '2784',
  '1979': 2899,
  '1980': 3075,
  '1981': 3363,
  '1982': 3902,
  '1983': 4117,
  '1984': 4315,
  '1985': 6176,
  '1986': 6369,
  '1987': 7295,
  '1988': 8459,
  '1989': 9367,
  '1990': 9341,
  '1991': 9701,
  '1992': 10155,
  '1993': 10158,
  '1994': 10262,
  '1995': 9306,
  '1996': 8915,
  '1997': 8946,
  '1998': 9470,
  '1999': 8376,
  '2000': 9996,
  '2001': 0,
  '2002': 0,
  '2003': 0,
  '2004': 0,
  '2005': 0,
  '2006': 0,
  '2007': 0,
  '2008': 0,
  '2009': 0,
  '2010': 0,
  '2011': 0,
  '2012': 0,
  '2013': 0,
  '2014': 0,
  '2015': 0,
  '2016': 0,
  'State': 'District of Columbia',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d066d')},
 {'1978': '80',
  '1979': 74,
  '1980': 70,
  '1981': 116,
  '1982': 179,
  '1983': 227,
  '1984': 206,
  '1985': 228,
  '1986': 249,
  '1987': 350,
  '1988': 372,
  '1989': 587,
  '1990': 606,
  '1991': 754,
  '1992': 720,
  '1993': 687,
  '1994': 687,
  '1995': 494,
  '1996': 461,
  '1997': 407,
  '1998': 359,
  '1999': 276,
  '2000': 356,
  '2001': 0,
  '2002': 0,
  '2003': 0,
  '2004': 0,
  '2005': 0,
  '2006': 0,
  '2007': 0,
  '2008': 0,
  '2009': 0,
  '2010': 0,
  '2011': 0,
  '2012': 0,
  '2013': 0,
  '2014': 0,
  '2015': 0,
  '2016': 0,
  'State': 'District of Columbia',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d066e')},
 {'1978': '21436',
  '1979': 19748,
  '1980': 20735,
  '1981': 23589,
  '1982': 27830,
  '1983': 26334,
  '1984': 26914,
  '1985': 28600,
  '1986': 32237,
  '1987': 32445,
  '1988': 34732,
  '1989': 39999,
  '1990': 44387,
  '1991': 46533,
  '1992': 48302,
  '1993': 53048,
  '1994': 57163,
  '1995': 63879,
  '1996': 63763,
  '1997': 64626,
  '1998': 67224,
  '1999': 69596,
  '2000': 71319,
  '2001': 72404,
  '2002': 75210,
  '2003': 82012,
  '2004': 85533,
  '2005': 89768,
  '2006': 92969,
  '2007': 98219,
  '2008': 102388,
  '2009': 103915,
  '2010': 104306,
  '2011': 103055,
  '2012': 101930,
  '2013': 103028,
  '2014': 102870,
  '2015': 101424,
  '2016': 99974,
  'State': 'Florida',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d066f')},
 {'1978': '20572',
  '1979': 18919,
  '1980': 19896,
  '1981': 22595,
  '1982': 26584,
  '1983': 25154,
  '1984': 25764,
  '1985': 27296,
  '1986': 30602,
  '1987': 30764,
  '1988': 32721,
  '1989': 37448,
  '1990': 41723,
  '1991': 43895,
  '1992': 45703,
  '1993': 50349,
  '1994': 54099,
  '1995': 60219,
  '1996': 60461,
  '1997': 61207,
  '1998': 63698,
  '1999': 65776,
  '2000': 67214,
  '2001': 68122,
  '2002': 70615,
  '2003': 76847,
  '2004': 79873,
  '2005': 83615,
  '2006': 86480,
  '2007': 91365,
  '2008': 95237,
  '2009': 96632,
  '2010': 96956,
  '2011': 95913,
  '2012': 94945,
  '2013': 95757,
  '2014': 95567,
  '2015': 94481,
  '2016': 93111,
  'State': 'Florida',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d0670')},
 {'1978': '864',
  '1979': 829,
  '1980': 839,
  '1981': 994,
  '1982': 1246,
  '1983': 1180,
  '1984': 1150,
  '1985': 1304,
  '1986': 1635,
  '1987': 1681,
  '1988': 2011,
  '1989': 2551,
  '1990': 2664,
  '1991': 2638,
  '1992': 2599,
  '1993': 2699,
  '1994': 3064,
  '1995': 3660,
  '1996': 3302,
  '1997': 3419,
  '1998': 3526,
  '1999': 3820,
  '2000': 4105,
  '2001': 4282,
  '2002': 4595,
  '2003': 5165,
  '2004': 5660,
  '2005': 6153,
  '2006': 6489,
  '2007': 6854,
  '2008': 7151,
  '2009': 7283,
  '2010': 7350,
  '2011': 7142,
  '2012': 6985,
  '2013': 7271,
  '2014': 7303,
  '2015': 6943,
  '2016': 6863,
  'State': 'Florida',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d0671')},
 {'1978': '11317',
  '1979': 12106,
  '1980': 12178,
  '1981': 12444,
  '1982': 14405,
  '1983': 15358,
  '1984': 15404,
  '1985': 16262,
  '1986': 16922,
  '1987': 18575,
  '1988': 18787,
  '1989': 20885,
  '1990': 22411,
  '1991': 23743,
  '1992': 25290,
  '1993': 27783,
  '1994': 33425,
  '1995': 34266,
  '1996': 35139,
  '1997': 36505,
  '1998': 39262,
  '1999': 42091,
  '2000': 44232,
  '2001': 45937,
  '2002': 47445,
  '2003': 47208,
  '2004': 51104,
  '2005': 48749,
  '2006': 52792,
  '2007': 54256,
  '2008': 52719,
  '2009': 56986,
  '2010': 56432,
  '2011': 55944,
  '2012': 55457,
  '2013': 54004,
  '2014': 52949,
  '2015': 52193,
  '2016': 53627,
  'State': 'Georgia',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d0672')},
 {'1978': '10762',
  '1979': 11556,
  '1980': 11610,
  '1981': 11839,
  '1982': 13745,
  '1983': 14608,
  '1984': 14641,
  '1985': 15427,
  '1986': 16025,
  '1987': 17647,
  '1988': 17858,
  '1989': 19775,
  '1990': 21168,
  '1991': 22347,
  '1992': 23835,
  '1993': 26023,
  '1994': 31413,
  '1995': 32230,
  '1996': 32900,
  '1997': 34223,
  '1998': 36788,
  '1999': 39484,
  '2000': 41474,
  '2001': 43103,
  '2002': 44316,
  '2003': 44063,
  '2004': 47668,
  '2005': 45856,
  '2006': 49235,
  '2007': 50711,
  '2008': 49027,
  '2009': 53063,
  '2010': 52598,
  '2011': 52027,
  '2012': 51868,
  '2013': 50445,
  '2014': 49438,
  '2015': 48578,
  '2016': 49839,
  'State': 'Georgia',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d0673')},
 {'1978': '555',
  '1979': 550,
  '1980': 568,
  '1981': 605,
  '1982': 660,
  '1983': 750,
  '1984': 763,
  '1985': 835,
  '1986': 897,
  '1987': 928,
  '1988': 929,
  '1989': 1110,
  '1990': 1243,
  '1991': 1396,
  '1992': 1455,
  '1993': 1760,
  '1994': 2012,
  '1995': 2036,
  '1996': 2239,
  '1997': 2282,
  '1998': 2474,
  '1999': 2607,
  '2000': 2758,
  '2001': 2834,
  '2002': 3129,
  '2003': 3145,
  '2004': 3436,
  '2005': 2893,
  '2006': 3557,
  '2007': 3545,
  '2008': 3692,
  '2009': 3923,
  '2010': 3834,
  '2011': 3917,
  '2012': 3589,
  '2013': 3559,
  '2014': 3511,
  '2015': 3615,
  '2016': 3788,
  'State': 'Georgia',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d0674')},
 {'1978': '727',
  '1979': 856,
  '1980': 985,
  '1981': 1207,
  '1982': 1461,
  '1983': 1700,
  '1984': 1965,
  '1985': 2111,
  '1986': 2180,
  '1987': 2264,
  '1988': 2300,
  '1989': 2459,
  '1990': 2533,
  '1991': 2700,
  '1992': 2926,
  '1993': 3129,
  '1994': 3333,
  '1995': 3560,
  '1996': 4011,
  '1997': 4978,
  '1998': 4924,
  '1999': 4903,
  '2000': 5053,
  '2001': 5431,
  '2002': 5423,
  '2003': 5828,
  '2004': 5960,
  '2005': 6146,
  '2006': 5967,
  '2007': 5978,
  '2008': 5955,
  '2009': 5891,
  '2010': 5912,
  '2011': 6037,
  '2012': 5831,
  '2013': 5632,
  '2014': 5866,
  '2015': 5879,
  '2016': 5602,
  'State': 'Hawaii',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d0675')},
 {'1978': '690',
  '1979': 809,
  '1980': 954,
  '1981': 1158,
  '1982': 1386,
  '1983': 1591,
  '1984': 1858,
  '1985': 1963,
  '1986': 2044,
  '1987': 2106,
  '1988': 2128,
  '1989': 2287,
  '1990': 2362,
  '1991': 2533,
  '1992': 2729,
  '1993': 2923,
  '1994': 3076,
  '1995': 3248,
  '1996': 3626,
  '1997': 4460,
  '1998': 4494,
  '1999': 4350,
  '2000': 4492,
  '2001': 4815,
  '2002': 4754,
  '2003': 5143,
  '2004': 5261,
  '2005': 5414,
  '2006': 5233,
  '2007': 5232,
  '2008': 5227,
  '2009': 5190,
  '2010': 5184,
  '2011': 5304,
  '2012': 5143,
  '2013': 4972,
  '2014': 5198,
  '2015': 5177,
  '2016': 4934,
  'State': 'Hawaii',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d0676')},
 {'1978': '37',
  '1979': 47,
  '1980': 31,
  '1981': 49,
  '1982': 75,
  '1983': 109,
  '1984': 107,
  '1985': 148,
  '1986': 136,
  '1987': 158,
  '1988': 172,
  '1989': 172,
  '1990': 171,
  '1991': 167,
  '1992': 197,
  '1993': 206,
  '1994': 257,
  '1995': 312,
  '1996': 385,
  '1997': 518,
  '1998': 430,
  '1999': 553,
  '2000': 561,
  '2001': 616,
  '2002': 669,
  '2003': 685,
  '2004': 699,
  '2005': 732,
  '2006': 734,
  '2007': 746,
  '2008': 728,
  '2009': 701,
  '2010': 728,
  '2011': 733,
  '2012': 688,
  '2013': 660,
  '2014': 668,
  '2015': 702,
  '2016': 668,
  'State': 'Hawaii',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d0677')},
 {'1978': '802',
  '1979': 830,
  '1980': 817,
  '1981': 957,
  '1982': 1044,
  '1983': 1187,
  '1984': 1253,
  '1985': 1344,
  '1986': 1448,
  '1987': 1435,
  '1988': 1581,
  '1989': 1850,
  '1990': 1961,
  '1991': 2143,
  '1992': 2256,
  '1993': 2606,
  '1994': 2811,
  '1995': 3328,
  '1996': 3832,
  '1997': 3911,
  '1998': 4083,
  '1999': 4842,
  '2000': 5535,
  '2001': 5984,
  '2002': 5746,
  '2003': 5737,
  '2004': 6375,
  '2005': 6818,
  '2006': 7124,
  '2007': 7319,
  '2008': 7290,
  '2009': 7400,
  '2010': 7431,
  '2011': 7739,
  '2012': 7985,
  '2013': 8242,
  '2014': 8117,
  '2015': 8052,
  '2016': 8252,
  'State': 'Idaho',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d0678')},
 {'1978': '772',
  '1979': 796,
  '1980': 792,
  '1981': 932,
  '1982': 1013,
  '1983': 1147,
  '1984': 1203,
  '1985': 1293,
  '1986': 1387,
  '1987': 1359,
  '1988': 1497,
  '1989': 1738,
  '1990': 1841,
  '1991': 2022,
  '1992': 2131,
  '1993': 2458,
  '1994': 2639,
  '1995': 3116,
  '1996': 3561,
  '1997': 3648,
  '1998': 3762,
  '1999': 4443,
  '2000': 5042,
  '2001': 5443,
  '2002': 5154,
  '2003': 5146,
  '2004': 5728,
  '2005': 6027,
  '2006': 6347,
  '2007': 6519,
  '2008': 6532,
  '2009': 6656,
  '2010': 6621,
  '2011': 6854,
  '2012': 6977,
  '2013': 7176,
  '2014': 7080,
  '2015': 7068,
  '2016': 7239,
  'State': 'Idaho',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d0679')},
 {'1978': '30',
  '1979': 34,
  '1980': 25,
  '1981': 25,
  '1982': 31,
  '1983': 40,
  '1984': 50,
  '1985': 51,
  '1986': 61,
  '1987': 76,
  '1988': 84,
  '1989': 112,
  '1990': 120,
  '1991': 121,
  '1992': 125,
  '1993': 148,
  '1994': 172,
  '1995': 212,
  '1996': 271,
  '1997': 263,
  '1998': 321,
  '1999': 399,
  '2000': 493,
  '2001': 541,
  '2002': 592,
  '2003': 591,
  '2004': 647,
  '2005': 791,
  '2006': 777,
  '2007': 800,
  '2008': 758,
  '2009': 744,
  '2010': 810,
  '2011': 885,
  '2012': 1008,
  '2013': 1066,
  '2014': 1037,
  '2015': 984,
  '2016': 1013,
  'State': 'Idaho',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d067a')},
 {'1978': '11258',
  '1979': 11935,
  '1980': 11899,
  '1981': 14328,
  '1982': 14293,
  '1983': 15595,
  '1984': 17114,
  '1985': 18634,
  '1986': 19456,
  '1987': 19850,
  '1988': 21081,
  '1989': 24712,
  '1990': 27516,
  '1991': 29115,
  '1992': 31640,
  '1993': 34495,
  '1994': 36531,
  '1995': 37658,
  '1996': 38852,
  '1997': 40788,
  '1998': 43051,
  '1999': 44660,
  '2000': 45281,
  '2001': 44348,
  '2002': 42693,
  '2003': 43418,
  '2004': 44054,
  '2005': 44919,
  '2006': 45106,
  '2007': 45215,
  '2008': 45474,
  '2009': 45161,
  '2010': 48418,
  '2011': 48427,
  '2012': 49348,
  '2013': 48653,
  '2014': 48278,
  '2015': 46240,
  '2016': 43657,
  'State': 'Illinois',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d067b')},
 {'1978': '10918',
  '1979': 11469,
  '1980': 11553,
  '1981': 13870,
  '1982': 13806,
  '1983': 15038,
  '1984': 16479,
  '1985': 17961,
  '1986': 18692,
  '1987': 19071,
  '1988': 20182,
  '1989': 23693,
  '1990': 26333,
  '1991': 27858,
  '1992': 30184,
  '1993': 32807,
  '1994': 34718,
  '1995': 35462,
  '1996': 36603,
  '1997': 38358,
  '1998': 40405,
  '1999': 41858,
  '2000': 42432,
  '2001': 41601,
  '2002': 40173,
  '2003': 40718,
  '2004': 41304,
  '2005': 42194,
  '2006': 42386,
  '2007': 42391,
  '2008': 42753,
  '2009': 42571,
  '2010': 45496,
  '2011': 45562,
  '2012': 46599,
  '2013': 45737,
  '2014': 45390,
  '2015': 43565,
  '2016': 41044,
  'State': 'Illinois',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d067c')},
 {'1978': '340',
  '1979': 466,
  '1980': 346,
  '1981': 458,
  '1982': 487,
  '1983': 557,
  '1984': 635,
  '1985': 673,
  '1986': 764,
  '1987': 779,
  '1988': 899,
  '1989': 1019,
  '1990': 1183,
  '1991': 1257,
  '1992': 1456,
  '1993': 1688,
  '1994': 1813,
  '1995': 2196,
  '1996': 2249,
  '1997': 2430,
  '1998': 2646,
  '1999': 2802,
  '2000': 2849,
  '2001': 2747,
  '2002': 2520,
  '2003': 2700,
  '2004': 2750,
  '2005': 2725,
  '2006': 2720,
  '2007': 2824,
  '2008': 2721,
  '2009': 2590,
  '2010': 2922,
  '2011': 2865,
  '2012': 2749,
  '2013': 2916,
  '2014': 2888,
  '2015': 2675,
  '2016': 2613,
  'State': 'Illinois',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d067d')},
 {'1978': '4923',
  '1979': 5667,
  '1980': 6683,
  '1981': 8022,
  '1982': 8790,
  '1983': 9296,
  '1984': 9328,
  '1985': 10056,
  '1986': 10175,
  '1987': 10827,
  '1988': 11406,
  '1989': 12341,
  '1990': 12736,
  '1991': 13719,
  '1992': 13945,
  '1993': 14470,
  '1994': 15014,
  '1995': 16125,
  '1996': 16960,
  '1997': 17903,
  '1998': 19197,
  '1999': 19309,
  '2000': 20125,
  '2001': 20966,
  '2002': 21611,
  '2003': 23069,
  '2004': 24008,
  '2005': 24455,
  '2006': 26091,
  '2007': 27132,
  '2008': 28322,
  '2009': 28808,
  '2010': 28028,
  '2011': 28906,
  '2012': 28831,
  '2013': 29913,
  '2014': 29271,
  '2015': 27355,
  '2016': 25546,
  'State': 'Indiana',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d067e')},
 {'1978': '4754',
  '1979': 5475,
  '1980': 6442,
  '1981': 7736,
  '1982': 8440,
  '1983': 8907,
  '1984': 8933,
  '1985': 9605,
  '1986': 9771,
  '1987': 10336,
  '1988': 10904,
  '1989': 11717,
  '1990': 12055,
  '1991': 13013,
  '1992': 13207,
  '1993': 13692,
  '1994': 14188,
  '1995': 15233,
  '1996': 15952,
  '1997': 16832,
  '1998': 17999,
  '1999': 18087,
  '2000': 18673,
  '2001': 19424,
  '2002': 20028,
  '2003': 21311,
  '2004': 22116,
  '2005': 22571,
  '2006': 23924,
  '2007': 24837,
  '2008': 25829,
  '2009': 26302,
  '2010': 25522,
  '2011': 26406,
  '2012': 26265,
  '2013': 27078,
  '2014': 26396,
  '2015': 24815,
  '2016': 23341,
  'State': 'Indiana',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d067f')},
 {'1978': '169',
  '1979': 192,
  '1980': 241,
  '1981': 286,
  '1982': 350,
  '1983': 389,
  '1984': 395,
  '1985': 451,
  '1986': 404,
  '1987': 491,
  '1988': 502,
  '1989': 624,
  '1990': 681,
  '1991': 706,
  '1992': 738,
  '1993': 778,
  '1994': 826,
  '1995': 892,
  '1996': 1008,
  '1997': 1071,
  '1998': 1198,
  '1999': 1222,
  '2000': 1452,
  '2001': 1542,
  '2002': 1583,
  '2003': 1758,
  '2004': 1892,
  '2005': 1884,
  '2006': 2167,
  '2007': 2295,
  '2008': 2493,
  '2009': 2506,
  '2010': 2506,
  '2011': 2500,
  '2012': 2566,
  '2013': 2835,
  '2014': 2875,
  '2015': 2540,

  '2016': 2205,
  'State': 'Indiana',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d0680')},
 {'1978': '1982',
  '1979': 2272,
  '1980': 2481,
  '1981': 2670,
  '1982': 2829,
  '1983': 2814,
  '1984': 2836,
  '1985': 2687,
  '1986': 2777,
  '1987': 2851,
  '1988': 3034,
  '1989': 3584,
  '1990': 3967,
  '1991': 4145,
  '1992': 4518,
  '1993': 4898,
  '1994': 5437,
  '1995': 5906,
  '1996': 6342,
  '1997': 6938,
  '1998': 7394,
  '1999': 7232,
  '2000': 7955,
  '2001': 7962,
  '2002': 8398,
  '2003': 8546,
  '2004': 8525,
  '2005': 8737,
  '2006': 8838,
  '2007': 8732,
  '2008': 8766,
  '2009': 8813,
  '2010': 9455,
  '2011': 9116,
  '2012': 8733,
  '2013': 8697,
  '2014': 8838,
  '2015': 8849,
  '2016': 9031,
  'State': 'Iowa',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d0681')},
 {'1978': '1909',
  '1979': 2176,
  '1980': 2388,
  '1981': 2556,
  '1982': 2708,
  '1983': 2700,
  '1984': 2733,
  '1985': 2577,
  '1986': 2653,
  '1987': 2729,
  '1988': 2894,
  '1989': 3405,
  '1990': 3755,
  '1991': 3949,
  '1992': 4275,
  '1993': 4617,
  '1994': 5086,
  '1995': 5481,
  '1996': 5872,
  '1997': 6410,
  '1998': 6903,
  '1999': 6693,
  '2000': 7363,
  '2001': 7327,
  '2002': 7695,
  '2003': 7830,
  '2004': 7768,
  '2005': 7937,
  '2006': 8049,
  '2007': 8015,
  '2008': 8017,
  '2009': 8090,
  '2010': 8675,
  '2011': 8378,
  '2012': 7949,
  '2013': 7983,
  '2014': 8086,
  '2015': 8041,
  '2016': 8210,
  'State': 'Iowa',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d0682')},
 {'1978': '73',
  '1979': 96,
  '1980': 93,
  '1981': 114,
  '1982': 121,
  '1983': 114,
  '1984': 103,
  '1985': 110,
  '1986': 124,
  '1987': 122,
  '1988': 140,
  '1989': 179,
  '1990': 212,
  '1991': 196,
  '1992': 243,
  '1993': 281,
  '1994': 351,
  '1995': 425,
  '1996': 470,
  '1997': 528,
  '1998': 491,
  '1999': 539,
  '2000': 592,
  '2001': 635,
  '2002': 703,
  '2003': 716,
  '2004': 757,
  '2005': 800,
  '2006': 789,
  '2007': 717,
  '2008': 749,
  '2009': 723,
  '2010': 780,
  '2011': 738,
  '2012': 784,
  '2013': 714,
  '2014': 752,
  '2015': 808,
  '2016': 821,
  'State': 'Iowa',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d0683')},
 {'1978': '2341',
  '1979': 2290,
  '1980': 2494,
  '1981': 2770,
  '1982': 3078,
  '1983': 3705,
  '1984': 4244,
  '1985': 4732,
  '1986': 5345,
  '1987': 5781,
  '1988': 5817,
  '1989': 5616,
  '1990': 5775,
  '1991': 5903,
  '1992': 6028,
  '1993': 5727,
  '1994': 6371,
  '1995': 7054,
  '1996': 7756,
  '1997': 7911,
  '1998': 8183,
  '1999': 8567,
  '2000': 8344,
  '2001': 8577,
  '2002': 8935,
  '2003': 9132,
  '2004': 8966,
  '2005': 9068,
  '2006': 8816,
  '2007': 8696,
  '2008': 8539,
  '2009': 8641,
  '2010': 9051,
  '2011': 9327,
  '2012': 9682,
  '2013': 9763,
  '2014': 9877,
  '2015': 9857,
  '2016': 9920,
  'State': 'Kansas',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d0684')},
 {'1978': '2243',
  '1979': 2208,
  '1980': 2381,
  '1981': 2625,
  '1982': 2918,
  '1983': 3500,
  '1984': 4009,
  '1985': 4459,
  '1986': 5048,
  '1987': 5505,
  '1988': 5540,
  '1989': 5370,
  '1990': 5491,
  '1991': 5610,
  '1992': 5706,
  '1993': 5452,
  '1994': 6027,
  '1995': 6605,
  '1996': 7280,
  '1997': 7435,
  '1998': 7660,
  '1999': 7997,
  '2000': 7840,
  '2001': 8080,
  '2002': 8398,
  '2003': 8503,
  '2004': 8346,
  '2005': 8394,
  '2006': 8178,
  '2007': 8071,
  '2008': 7970,
  '2009': 8076,
  '2010': 8428,
  '2011': 8647,
  '2012': 8952,
  '2013': 9026,
  '2014': 9083,
  '2015': 9018,
  '2016': 9051,
  'State': 'Kansas',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d0685')},
 {'1978': '98',
  '1979': 82,
  '1980': 113,
  '1981': 145,
  '1982': 160,
  '1983': 205,
  '1984': 235,
  '1985': 273,
  '1986': 297,
  '1987': 276,
  '1988': 277,
  '1989': 246,
  '1990': 284,
  '1991': 293,
  '1992': 322,
  '1993': 275,
  '1994': 344,
  '1995': 449,
  '1996': 476,
  '1997': 476,
  '1998': 523,
  '1999': 570,
  '2000': 504,
  '2001': 497,
  '2002': 537,
  '2003': 629,
  '2004': 620,
  '2005': 674,
  '2006': 638,
  '2007': 625,
  '2008': 569,
  '2009': 565,
  '2010': 623,
  '2011': 680,
  '2012': 730,
  '2013': 737,
  '2014': 794,
  '2015': 839,
  '2016': 869,
  'State': 'Kansas',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d0686')},
 {'1978': '3390',
  '1979': 3691,
  '1980': 3588,
  '1981': 3993,
  '1982': 4031,
  '1983': 4773,
  '1984': 4820,
  '1985': 4981,
  '1986': 5288,
  '1987': 6437,
  '1988': 7119,
  '1989': 8289,
  '1990': 9023,
  '1991': 9799,
  '1992': 10364,
  '1993': 10440,
  '1994': 11066,
  '1995': 12060,
  '1996': 12910,
  '1997': 14600,
  '1998': 14987,
  '1999': 15317,
  '2000': 14919,
  '2001': 15424,
  '2002': 15820,
  '2003': 16622,
  '2004': 17814,
  '2005': 19662,
  '2006': 20000,
  '2007': 22457,
  '2008': 21706,
  '2009': 21638,
  '2010': 20544,
  '2011': 21545,
  '2012': 22110,
  '2013': 21030,
  '2014': 21657,
  '2015': 21701,
  '2016': 23022,
  'State': 'Kentucky',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d0687')},
 {'1978': '3279',
  '1979': 3550,
  '1980': 3463,
  '1981': 3863,
  '1982': 3872,
  '1983': 4581,
  '1984': 4617,
  '1985': 4768,
  '1986': 5067,
  '1987': 6144,
  '1988': 6771,
  '1989': 7842,
  '1990': 8544,
  '1991': 9286,
  '1992': 9819,
  '1993': 9895,
  '1994': 10429,
  '1995': 11326,
  '1996': 12090,
  '1997': 13548,
  '1998': 13941,
  '1999': 14220,
  '2000': 13858,
  '2001': 14286,
  '2002': 14551,
  '2003': 15211,
  '2004': 16254,
  '2005': 17658,
  '2006': 17942,
  '2007': 20016,
  '2008': 19436,
  '2009': 19343,
  '2010': 18406,
  '2011': 19091,
  '2012': 19425,
  '2013': 18717,
  '2014': 19084,
  '2015': 19114,
  '2016': 20080,
  'State': 'Kentucky',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d0688')},
 {'1978': '111',
  '1979': 141,
  '1980': 125,
  '1981': 130,
  '1982': 159,
  '1983': 192,
  '1984': 203,
  '1985': 213,
  '1986': 221,
  '1987': 293,
  '1988': 348,
  '1989': 447,
  '1990': 479,
  '1991': 513,
  '1992': 545,
  '1993': 545,
  '1994': 637,
  '1995': 734,
  '1996': 820,
  '1997': 1052,
  '1998': 1046,
  '1999': 1097,
  '2000': 1061,
  '2001': 1138,
  '2002': 1269,
  '2003': 1411,
  '2004': 1560,
  '2005': 2004,
  '2006': 2058,
  '2007': 2441,
  '2008': 2270,
  '2009': 2295,
  '2010': 2138,
  '2011': 2454,
  '2012': 2685,
  '2013': 2313,
  '2014': 2573,
  '2015': 2587,
  '2016': 2942,
  'State': 'Kentucky',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d0689')},
 {'1978': '7291',
  '1979': 7618,
  '1980': 8889,
  '1981': 9415,
  '1982': 10930,
  '1983': 12812,
  '1984': 13659,
  '1985': 13890,
  '1986': 14300,
  '1987': 15375,
  '1988': 16242,
  '1989': 17257,
  '1990': 18599,
  '1991': 20003,
  '1992': 20980,
  '1993': 22468,
  '1994': 24063,
  '1995': 25195,
  '1996': 26779,
  '1997': 29265,
  '1998': 32228,
  '1999': 34066,
  '2000': 35207,
  '2001': 35810,
  '2002': 36032,
  '2003': 36047,
  '2004': 36939,
  '2005': 36083,
  '2006': 37012,
  '2007': 37540,
  '2008': 38381,
  '2009': 39780,
  '2010': 39445,
  '2011': 39710,
  '2012': 40172,
  '2013': 39299,
  '2014': 38030,
  '2015': 36377,
  '2016': 35682,
  'State': 'Louisiana',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d068a')},
 {'1978': '7083',
  '1979': 7382,
  '1980': 8586,
  '1981': 9071,
  '1982': 10514,
  '1983': 12279,
  '1984': 13051,
  '1985': 13280,
  '1986': 13673,
  '1987': 14702,
  '1988': 15573,
  '1989': 16559,
  '1990': 17824,
  '1991': 19092,
  '1992': 19954,
  '1993': 21354,
  '1994': 22768,
  '1995': 23771,
  '1996': 25218,
  '1997': 27397,
  '1998': 30048,
  '1999': 31798,
  '2000': 32988,
  '2001': 33448,
  '2002': 33634,
  '2003': 33642,
  '2004': 34553,
  '2005': 33774,
  '2006': 34623,
  '2007': 35082,
  '2008': 35865,
  '2009': 37164,
  '2010': 37037,
  '2011': 37326,
  '2012': 37783,
  '2013': 37071,
  '2014': 35955,
  '2015': 34331,
  '2016': 33701,
  'State': 'Louisiana',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d068b')},
 {'1978': '208',
  '1979': 236,
  '1980': 303,
  '1981': 344,
  '1982': 416,
  '1983': 533,
  '1984': 608,
  '1985': 610,
  '1986': 627,
  '1987': 673,
  '1988': 669,
  '1989': 698,
  '1990': 775,
  '1991': 911,
  '1992': 1026,
  '1993': 1114,
  '1994': 1295,
  '1995': 1424,
  '1996': 1561,
  '1997': 1868,
  '1998': 2180,
  '1999': 2268,
  '2000': 2219,
  '2001': 2362,
  '2002': 2398,
  '2003': 2405,
  '2004': 2386,
  '2005': 2309,
  '2006': 2389,
  '2007': 2458,
  '2008': 2516,
  '2009': 2616,
  '2010': 2408,
  '2011': 2384,
  '2012': 2389,
  '2013': 2228,
  '2014': 2075,
  '2015': 2046,
  '2016': 1981,
  'State': 'Louisiana',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d068c')},
 {'1978': '711',
  '1979': 776,
  '1980': 814,
  '1981': 992,
  '1982': 1110,
  '1983': 1082,
  '1984': 1032,
  '1985': 1317,
  '1986': 1316,
  '1987': 1299,
  '1988': 1277,
  '1989': 1455,
  '1990': 1523,
  '1991': 1579,
  '1992': 1519,
  '1993': 1469,
  '1994': 1474,
  '1995': 1396,
  '1996': 1426,
  '1997': 1620,
  '1998': 1691,
  '1999': 1716,
  '2000': 1679,
  '2001': 1704,
  '2002': 1900,
  '2003': 2013,
  '2004': 2024,
  '2005': 2023,
  '2006': 2120,
  '2007': 2148,
  '2008': 2195,
  '2009': 2206,
  '2010': 2154,
  '2011': 2145,
  '2012': 2108,
  '2013': 2173,
  '2014': 2242,
  '2015': 2279,
  '2016': 2404,
  'State': 'Maine',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d068d')},
 {'1978': '695',
  '1979': 758,
  '1980': 793,
  '1981': 966,
  '1982': 1080,
  '1983': 1049,
  '1984': 1005,
  '1985': 1285,
  '1986': 1289,
  '1987': 1270,
  '1988': 1241,
  '1989': 1409,
  '1990': 1479,
  '1991': 1517,
  '1992': 1459,
  '1993': 1419,
  '1994': 1426,
  '1995': 1360,
  '1996': 1378,
  '1997': 1558,
  '1998': 1621,
  '1999': 1651,
  '2000': 1613,
  '2001': 1645,
  '2002': 1810,
  '2003': 1889,
  '2004': 1899,
  '2005': 1894,
  '2006': 1975,
  '2007': 2009,
  '2008': 2039,
  '2009': 2048,
  '2010': 1988,
  '2011': 1981,
  '2012': 1944,
  '2013': 2013,
  '2014': 2063,
  '2015': 2072,
  '2016': 2169,
  'State': 'Maine',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d068e')},
 {'1978': '16',
  '1979': 18,
  '1980': 21,
  '1981': 26,
  '1982': 30,
  '1983': 33,
  '1984': 27,
  '1985': 32,
  '1986': 27,
  '1987': 29,
  '1988': 36,
  '1989': 46,
  '1990': 44,
  '1991': 62,
  '1992': 60,
  '1993': 50,
  '1994': 48,
  '1995': 36,
  '1996': 48,
  '1997': 62,
  '1998': 70,
  '1999': 65,
  '2000': 66,
  '2001': 59,
  '2002': 90,
  '2003': 124,
  '2004': 125,
  '2005': 129,
  '2006': 145,
  '2007': 139,
  '2008': 156,
  '2009': 158,
  '2010': 166,
  '2011': 164,
  '2012': 164,
  '2013': 160,
  '2014': 179,
  '2015': 207,
  '2016': 235,
  'State': 'Maine',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d068f')},
 {'1978': '7966',
  '1979': 7860,
  '1980': 7731,
  '1981': 9335,
  '1982': 11617,
  '1983': 12617,
  '1984': 13124,
  '1985': 13005,
  '1986': 13326,
  '1987': 13467,
  '1988': 14276,
  '1989': 16514,
  '1990': 17848,
  '1991': 19291,
  '1992': 19977,
  '1993': 20264,
  '1994': 20998,
  '1995': 21453,
  '1996': 22050,
  '1997': 22232,
  '1998': 22572,
  '1999': 23095,
  '2000': 23538,
  '2001': 23752,
  '2002': 24162,
  '2003': 23791,
  '2004': 23285,
  '2005': 22737,
  '2006': 22945,
  '2007': 23433,
  '2008': 23324,
  '2009': 22255,
  '2010': 22645,
  '2011': 22558,
  '2012': 21522,
  '2013': 21335,
  '2014': 21011,
  '2015': 20764,
  '2016': 19994,
  'State': 'Maryland',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d0690')},
 {'1978': '7722',
  '1979': 7638,
  '1980': 7502,
  '1981': 9031,
  '1982': 11251,
  '1983': 12208,
  '1984': 12683,
  '1985': 12594,
  '1986': 12882,
  '1987': 13010,
  '1988': 13760,
  '1989': 15786,
  '1990': 16971,
  '1991': 18360,
  '1992': 19023,
  '1993': 19288,
  '1994': 19959,
  '1995': 20374,
  '1996': 20995,
  '1997': 21124,
  '1998': 21432,
  '1999': 21982,
  '2000': 22319,
  '2001': 22545,
  '2002': 22898,
  '2003': 22543,
  '2004': 22105,
  '2005': 21640,
  '2006': 21864,
  '2007': 22249,
  '2008': 22264,
  '2009': 21206,
  '2010': 21686,
  '2011': 21576,
  '2012': 20646,
  '2013': 20410,
  '2014': 20100,
  '2015': 19849,
  '2016': 19172,
  'State': 'Maryland',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d0691')},
 {'1978': '244',
  '1979': 222,
  '1980': 229,
  '1981': 304,
  '1982': 366,
  '1983': 409,
  '1984': 441,
  '1985': 411,
  '1986': 444,
  '1987': 457,
  '1988': 516,
  '1989': 728,
  '1990': 877,
  '1991': 931,
  '1992': 954,
  '1993': 976,
  '1994': 1039,
  '1995': 1079,
  '1996': 1055,
  '1997': 1108,
  '1998': 1140,
  '1999': 1113,
  '2000': 1219,
  '2001': 1207,
  '2002': 1264,
  '2003': 1248,
  '2004': 1180,
  '2005': 1097,
  '2006': 1081,
  '2007': 1184,
  '2008': 1060,

  '2009': 1049,
  '2010': 959,
  '2011': 982,
  '2012': 876,
  '2013': 925,
  '2014': 911,
  '2015': 915,
  '2016': 822,
  'State': 'Maryland',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d0692')},
 {'1978': '2806',
  '1979': 2924,
  '1980': 3185,
  '1981': 3889,
  '1982': 4334,
  '1983': 4482,
  '1984': 4883,
  '1985': 5390,
  '1986': 5636,
  '1987': 6268,
  '1988': 6757,
  '1989': 7524,
  '1990': 8345,
  '1991': 9415,
  '1992': 10053,
  '1993': 10229,
  '1994': 11293,
  '1995': 11687,
  '1996': 11796,
  '1997': 11947,
  '1998': 11799,
  '1999': 11356,
  '2000': 10722,
  '2001': 10588,
  '2002': 10329,
  '2003': 10232,
  '2004': 10144,
  '2005': 10701,
  '2006': 11032,
  '2007': 11436,
  '2008': 11408,
  '2009': 11316,
  '2010': 11313,
  '2011': 11623,
  '2012': 11308,
  '2013': 10950,
  '2014': 10713,
  '2015': 9922,
  '2016': 9403,
  'State': 'Massachusetts',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d0693')},
 {'1978': '2724',
  '1979': 2837,
  '1980': 3079,
  '1981': 3697,
  '1982': 4117,
  '1983': 4244,
  '1984': 4619,
  '1985': 5079,
  '1986': 5310,
  '1987': 5859,
  '1988': 6310,
  '1989': 7026,
  '1990': 7749,
  '1991': 8779,
  '1992': 9489,
  '1993': 9576,
  '1994': 10587,
  '1995': 11031,
  '1996': 11046,
  '1997': 11214,
  '1998': 11053,
  '1999': 10614,
  '2000': 10059,
  '2001': 9875,
  '2002': 9625,
  '2003': 9524,
  '2004': 9403,
  '2005': 9913,
  '2006': 10186,
  '2007': 10646,
  '2008': 10657,
  '2009': 10597,
  '2010': 10547,
  '2011': 10832,
  '2012': 10549,
  '2013': 10143,
  '2014': 9985,
  '2015': 9268,
  '2016': 8820,
  'State': 'Massachusetts',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d0694')},
 {'1978': '82',
  '1979': 87,
  '1980': 106,
  '1981': 192,
  '1982': 217,
  '1983': 238,
  '1984': 264,
  '1985': 311,
  '1986': 326,
  '1987': 409,
  '1988': 447,
  '1989': 498,
  '1990': 596,
  '1991': 636,
  '1992': 564,
  '1993': 653,
  '1994': 706,
  '1995': 656,
  '1996': 750,
  '1997': 733,
  '1998': 746,
  '1999': 742,
  '2000': 663,
  '2001': 713,
  '2002': 704,
  '2003': 708,
  '2004': 741,
  '2005': 788,
  '2006': 846,
  '2007': 790,
  '2008': 751,
  '2009': 719,
  '2010': 766,
  '2011': 791,
  '2012': 759,
  '2013': 807,
  '2014': 728,
  '2015': 654,
  '2016': 583,
  'State': 'Massachusetts',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d0695')},
 {'1978': '14944',
  '1979': 15002,
  '1980': 15124,
  '1981': 15157,
  '1982': 14913,
  '1983': 14510,
  '1984': 14604,
  '1985': 17755,
  '1986': 20742,
  '1987': 23879,
  '1988': 27612,
  '1989': 31639,
  '1990': 34267,
  '1991': 36423,
  '1992': 39113,
  '1993': 39318,
  '1994': 40631,
  '1995': 41112,
  '1996': 42349,
  '1997': 44771,
  '1998': 45879,
  '1999': 46617,
  '2000': 47718,
  '2001': 48849,
  '2002': 50591,
  '2003': 49358,
  '2004': 48883,
  '2005': 49546,
  '2006': 51577,
  '2007': 50233,
  '2008': 48738,
  '2009': 45478,
  '2010': 44165,
  '2011': 42940,
  '2012': 43636,
  '2013': 43759,
  '2014': 43390,
  '2015': 42628,
  '2016': 41122,
  'State': 'Michigan',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d0696')},
 {'1978': '14323',
  '1979': 14374,
  '1980': 14490,
  '1981': 14527,
  '1982': 14289,
  '1983': 13850,
  '1984': 13921,
  '1985': 16941,
  '1986': 19724,
  '1987': 22696,
  '1988': 26279,
  '1989': 30053,
  '1990': 32579,
  '1991': 34689,
  '1992': 37271,
  '1993': 37520,
  '1994': 38610,
  '1995': 39270,
  '1996': 40429,
  '1997': 42715,
  '1998': 43827,
  '1999': 44590,
  '2000': 45587,
  '2001': 46700,
  '2002': 48324,
  '2003': 47160,
  '2004': 46770,
  '2005': 47435,
  '2006': 49407,
  '2007': 48153,
  '2008': 46781,
  '2009': 43723,
  '2010': 42296,
  '2011': 41031,
  '2012': 41647,
  '2013': 41700,
  '2014': 41267,
  '2015': 40355,
  '2016': 38880,
  'State': 'Michigan',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d0697')},
 {'1978': '621',
  '1979': 628,
  '1980': 634,
  '1981': 630,
  '1982': 624,
  '1983': 660,
  '1984': 683,
  '1985': 814,
  '1986': 1018,
  '1987': 1183,
  '1988': 1333,
  '1989': 1586,
  '1990': 1688,
  '1991': 1734,
  '1992': 1842,
  '1993': 1798,
  '1994': 2021,
  '1995': 1842,
  '1996': 1920,
  '1997': 2056,
  '1998': 2052,
  '1999': 2027,
  '2000': 2131,
  '2001': 2149,
  '2002': 2267,
  '2003': 2198,
  '2004': 2113,
  '2005': 2111,
  '2006': 2170,
  '2007': 2080,
  '2008': 1957,
  '2009': 1755,
  '2010': 1869,
  '2011': 1909,
  '2012': 1989,
  '2013': 2059,
  '2014': 2123,
  '2015': 2273,
  '2016': 2242,
  'State': 'Michigan',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d0698')},
 {'1978': '1954',
  '1979': 2094,
  '1980': 2001,
  '1981': 1966,
  '1982': 2081,
  '1983': 2113,
  '1984': 2167,
  '1985': 2343,
  '1986': 2462,
  '1987': 2546,
  '1988': 2799,
  '1989': 3103,
  '1990': 3176,
  '1991': 3472,
  '1992': 3822,
  '1993': 4200,
  '1994': 4575,
  '1995': 4846,
  '1996': 5158,
  '1997': 5326,
  '1998': 5572,
  '1999': 5969,
  '2000': 6238,
  '2001': 6606,
  '2002': 7129,
  '2003': 7865,
  '2004': 8758,
  '2005': 9281,
  '2006': 9108,
  '2007': 9468,
  '2008': 9910,
  '2009': 9986,
  '2010': 9796,
  '2011': 9800,
  '2012': 9938,
  '2013': 10289,
  '2014': 10637,
  '2015': 10798,
  '2016': 10592,
  'State': 'Minnesota',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d0699')},
 {'1978': '1878',
  '1979': 2017,
  '1980': 1936,
  '1981': 1910,
  '1982': 2008,
  '1983': 2046,
  '1984': 2088,
  '1985': 2252,
  '1986': 2365,
  '1987': 2431,
  '1988': 2671,
  '1989': 2944,
  '1990': 3017,
  '1991': 3299,
  '1992': 3634,
  '1993': 4008,
  '1994': 4338,
  '1995': 4629,
  '1996': 4924,
  '1997': 5068,
  '1998': 5284,
  '1999': 5614,
  '2000': 5870,
  '2001': 6223,
  '2002': 6674,
  '2003': 7430,
  '2004': 8214,
  '2005': 8677,
  '2006': 8546,
  '2007': 8866,
  '2008': 9240,
  '2009': 9312,
  '2010': 9158,
  '2011': 9156,
  '2012': 9228,
  '2013': 9566,
  '2014': 9901,
  '2015': 10027,
  '2016': 9818,
  'State': 'Minnesota',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d069a')},
 {'1978': '76',
  '1979': 77,
  '1980': 65,
  '1981': 56,
  '1982': 73,
  '1983': 67,
  '1984': 79,
  '1985': 91,
  '1986': 97,
  '1987': 115,
  '1988': 128,
  '1989': 159,
  '1990': 159,
  '1991': 173,
  '1992': 188,
  '1993': 192,
  '1994': 237,
  '1995': 217,
  '1996': 234,
  '1997': 258,
  '1998': 288,
  '1999': 355,
  '2000': 368,
  '2001': 383,
  '2002': 455,
  '2003': 435,
  '2004': 544,
  '2005': 604,
  '2006': 562,
  '2007': 602,
  '2008': 670,
  '2009': 674,
  '2010': 638,
  '2011': 644,
  '2012': 710,
  '2013': 723,
  '2014': 736,
  '2015': 771,
  '2016': 774,
  'State': 'Minnesota',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d069b')},
 {'1978': '2896',
  '1979': 3508,
  '1980': 3902,
  '1981': 4624,
  '1982': 5484,
  '1983': 5586,
  '1984': 6115,
  '1985': 6392,
  '1986': 6747,
  '1987': 6880,
  '1988': 7384,
  '1989': 7911,
  '1990': 8375,
  '1991': 8904,
  '1992': 8905,
  '1993': 9907,
  '1994': 10930,
  '1995': 12684,
  '1996': 13859,
  '1997': 14296,
  '1998': 16678,
  '1999': 18247,
  '2000': 20241,
  '2001': 21460,
  '2002': 22705,
  '2003': 20589,
  '2004': 20983,
  '2005': 20515,
  '2006': 21068,
  '2007': 22431,
  '2008': 22754,
  '2009': 21482,
  '2010': 21067,
  '2011': 21386,
  '2012': 22319,
  '2013': 21969,
  '2014': 18793,
  '2015': 18911,
  '2016': 19192,
  'State': 'Mississippi',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d069c')},
 {'1978': '2785',
  '1979': 3401,
  '1980': 3785,
  '1981': 4475,
  '1982': 5298,
  '1983': 5381,
  '1984': 5855,
  '1985': 6103,
  '1986': 6443,
  '1987': 6557,
  '1988': 7030,
  '1989': 7509,
  '1990': 7927,
  '1991': 8396,
  '1992': 8356,
  '1993': 9330,
  '1994': 10282,
  '1995': 11893,
  '1996': 12968,
  '1997': 13334,
  '1998': 15465,
  '1999': 16842,
  '2000': 18572,
  '2001': 19637,
  '2002': 20623,
  '2003': 18834,
  '2004': 19187,
  '2005': 18729,
  '2006': 19279,
  '2007': 20469,
  '2008': 20773,
  '2009': 19747,
  '2010': 19542,
  '2011': 19808,
  '2012': 20652,
  '2013': 20352,
  '2014': 17448,
  '2015': 17595,
  '2016': 17823,
  'State': 'Mississippi',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d069d')},
 {'1978': '111',
  '1979': 107,
  '1980': 117,
  '1981': 149,
  '1982': 186,
  '1983': 205,
  '1984': 260,
  '1985': 289,
  '1986': 304,
  '1987': 323,
  '1988': 354,
  '1989': 402,
  '1990': 448,
  '1991': 508,
  '1992': 549,
  '1993': 577,
  '1994': 648,
  '1995': 791,
  '1996': 891,
  '1997': 962,
  '1998': 1213,
  '1999': 1405,
  '2000': 1669,
  '2001': 1823,
  '2002': 2082,
  '2003': 1755,

  '2004': 1796,
  '2005': 1786,
  '2006': 1789,
  '2007': 1962,
  '2008': 1981,
  '2009': 1735,
  '2010': 1525,
  '2011': 1578,
  '2012': 1667,
  '2013': 1617,
  '2014': 1345,
  '2015': 1316,
  '2016': 1369,
  'State': 'Mississippi',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d069e')},
 {'1978': '5637',
  '1979': 5279,
  '1980': 5726,
  '1981': 6489,
  '1982': 7445,
  '1983': 8103,
  '1984': 8770,
  '1985': 9796,
  '1986': 10309,
  '1987': 11357,
  '1988': 12176,
  '1989': 13921,
  '1990': 14943,
  '1991': 15897,
  '1992': 16195,
  '1993': 16178,
  '1994': 17898,
  '1995': 19134,
  '1996': 22003,
  '1997': 23664,
  '1998': 25060,
  '1999': 26155,
  '2000': 27543,
  '2001': 28757,
  '2002': 30099,
  '2003': 30303,
  '2004': 31081,
  '2005': 30823,
  '2006': 30167,
  '2007': 29857,
  '2008': 30186,
  '2009': 30563,
  '2010': 30623,
  '2011': 30833,
  '2012': 31247,
  '2013': 31537,
  '2014': 31942,
  '2015': 32330,
  '2016': 32461,
  'State': 'Missouri',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d069f')},
 {'1978': '5455',
  '1979': 5076,
  '1980': 5490,
  '1981': 6224,
  '1982': 7051,
  '1983': 7793,
  '1984': 8425,
  '1985': 9415,
  '1986': 9856,
  '1987': 10728,
  '1988': 11546,
  '1989': 13203,
  '1990': 14166,
  '1991': 15076,
  '1992': 15276,
  '1993': 15258,
  '1994': 16856,
  '1995': 17960,
  '1996': 20539,
  '1997': 22001,
  '1998': 23166,
  '1999': 24264,
  '2000': 25550,
  '2001': 26633,
  '2002': 27825,
  '2003': 28064,
  '2004': 28574,
  '2005': 28312,
  '2006': 27588,
  '2007': 27335,
  '2008': 27737,
  '2009': 28136,
  '2010': 28163,
  '2011': 28258,
  '2012': 28544,
  '2013': 28755,
  '2014': 28836,
  '2015': 29063,
  '2016': 29124,
  'State': 'Missouri',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06a0')},
 {'1978': '182',
  '1979': 203,
  '1980': 236,
  '1981': 265,
  '1982': 394,
  '1983': 310,
  '1984': 345,
  '1985': 381,
  '1986': 453,
  '1987': 629,
  '1988': 630,
  '1989': 718,
  '1990': 777,
  '1991': 821,
  '1992': 919,
  '1993': 920,
  '1994': 1042,
  '1995': 1174,
  '1996': 1464,
  '1997': 1663,
  '1998': 1894,
  '1999': 1891,
  '2000': 1993,
  '2001': 2124,
  '2002': 2274,
  '2003': 2239,
  '2004': 2507,
  '2005': 2511,
  '2006': 2579,
  '2007': 2522,
  '2008': 2449,
  '2009': 2427,
  '2010': 2460,
  '2011': 2575,
  '2012': 2703,
  '2013': 2782,
  '2014': 3106,
  '2015': 3267,
  '2016': 3337,
  'State': 'Missouri',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06a1')},
 {'1978': '690',
  '1979': 715,
  '1980': 739,
  '1981': 831,
  '1982': 914,
  '1983': 903,
  '1984': 964,
  '1985': 1129,
  '1986': 1111,
  '1987': 1207,
  '1988': 1272,
  '1989': 1328,
  '1990': 1425,
  '1991': 1478,
  '1992': 1548,
  '1993': 1541,
  '1994': 1764,
  '1995': 1999,
  '1996': 2230,
  '1997': 2541,
  '1998': 2734,
  '1999': 2951,
  '2000': 3105,
  '2001': 3328,
  '2002': 3323,
  '2003': 3620,
  '2004': 3164,
  '2005': 3509,
  '2006': 3563,
  '2007': 3431,
  '2008': 3517,
  '2009': 3605,
  '2010': 3716,
  '2011': 3678,
  '2012': 3609,
  '2013': 3642,
  '2014': 3699,
  '2015': 3685,
  '2016': 3814,
  'State': 'Montana',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06a2')},
 {'1978': '675',
  '1979': 695,
  '1980': 714,
  '1981': 807,
  '1982': 885,
  '1983': 879,
  '1984': 929,
  '1985': 1090,
  '1986': 1069,
  '1987': 1160,
  '1988': 1214,
  '1989': 1264,
  '1990': 1349,
  '1991': 1405,
  '1992': 1465,
  '1993': 1474,
  '1994': 1671,
  '1995': 1887,
  '1996': 2109,
  '1997': 2350,
  '1998': 2486,
  '1999': 2688,
  '2000': 2799,
  '2001': 2965,
  '2002': 2978,
  '2003': 3201,
  '2004': 2841,
  '2005': 3155,
  '2006': 3209,
  '2007': 3133,
  '2008': 3158,
  '2009': 3214,
  '2010': 3291,
  '2011': 3274,
  '2012': 3210,
  '2013': 3230,
  '2014': 3311,
  '2015': 3295,
  '2016': 3405,
  'State': 'Montana',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06a3')},
 {'1978': '15',
  '1979': 20,
  '1980': 25,
  '1981': 24,
  '1982': 29,
  '1983': 24,
  '1984': 35,
  '1985': 39,
  '1986': 42,
  '1987': 47,
  '1988': 58,
  '1989': 64,
  '1990': 76,
  '1991': 73,
  '1992': 83,
  '1993': 67,
  '1994': 93,
  '1995': 112,
  '1996': 121,
  '1997': 191,
  '1998': 248,
  '1999': 263,
  '2000': 306,
  '2001': 363,
  '2002': 345,
  '2003': 419,
  '2004': 323,
  '2005': 354,
  '2006': 354,
  '2007': 298,
  '2008': 359,
  '2009': 391,
  '2010': 425,
  '2011': 404,
  '2012': 399,
  '2013': 412,
  '2014': 388,
  '2015': 390,
  '2016': 409,
  'State': 'Montana',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06a4')},
 {'1978': '1347',
  '1979': 1291,
  '1980': 1446,
  '1981': 1488,
  '1982': 1739,
  '1983': 1629,
  '1984': 1655,
  '1985': 1814,
  '1986': 2044,
  '1987': 2086,
  '1988': 2156,
  '1989': 2393,
  '1990': 2403,
  '1991': 2526,
  '1992': 2514,
  '1993': 2518,
  '1994': 2711,
  '1995': 3074,
  '1996': 3287,
  '1997': 3402,
  '1998': 3676,
  '1999': 3688,
  '2000': 3895,
  '2001': 3937,
  '2002': 4058,
  '2003': 4040,
  '2004': 4130,
  '2005': 4455,
  '2006': 4407,
  '2007': 4505,
  '2008': 4520,
  '2009': 4474,
  '2010': 4587,
  '2011': 4616,
  '2012': 4705,
  '2013': 5026,
  '2014': 5441,
  '2015': 5372,
  '2016': 5302,
  'State': 'Nebraska',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06a5')},
 {'1978': '1264',
  '1979': 1228,
  '1980': 1390,
  '1981': 1426,
  '1982': 1658,
  '1983': 1571,
  '1984': 1582,
  '1985': 1744,
  '1986': 1959,
  '1987': 1991,
  '1988': 2059,
  '1989': 2250,
  '1990': 2258,
  '1991': 2357,
  '1992': 2341,
  '1993': 2349,
  '1994': 2535,
  '1995': 2863,
  '1996': 3062,
  '1997': 3180,
  '1998': 3427,
  '1999': 3437,
  '2000': 3629,
  '2001': 3595,
  '2002': 3706,
  '2003': 3717,
  '2004': 3761,
  '2005': 4032,
  '2006': 3994,
  '2007': 4106,
  '2008': 4130,
  '2009': 4108,
  '2010': 4176,
  '2011': 4247,
  '2012': 4352,
  '2013': 4656,
  '2014': 5001,
  '2015': 4943,
  '2016': 4878,
  'State': 'Nebraska',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06a6')},
 {'1978': '83',
  '1979': 63,
  '1980': 56,
  '1981': 62,
  '1982': 81,
  '1983': 58,
  '1984': 73,
  '1985': 70,
  '1986': 85,
  '1987': 95,
  '1988': 97,
  '1989': 143,
  '1990': 145,
  '1991': 169,
  '1992': 173,
  '1993': 169,
  '1994': 176,
  '1995': 211,
  '1996': 225,
  '1997': 222,
  '1998': 249,
  '1999': 251,
  '2000': 266,
  '2001': 342,
  '2002': 352,
  '2003': 323,
  '2004': 369,
  '2005': 423,
  '2006': 413,
  '2007': 399,
  '2008': 390,
  '2009': 366,
  '2010': 411,
  '2011': 369,
  '2012': 353,
  '2013': 370,
  '2014': 440,
  '2015': 429,
  '2016': 424,
  'State': 'Nebraska',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06a7')},
 {'1978': '1350',
  '1979': 1566,
  '1980': 1839,
  '1981': 2116,
  '1982': 2753,
  '1983': 3188,
  '1984': 3488,
  '1985': 3771,
  '1986': 4551,
  '1987': 4434,
  '1988': 4881,
  '1989': 5112,
  '1990': 5322,
  '1991': 5823,
  '1992': 6049,
  '1993': 6412,
  '1994': 6993,
  '1995': 7713,
  '1996': 8325,
  '1997': 9024,
  '1998': 9651,
  '1999': 9494,
  '2000': 10063,
  '2001': 10233,
  '2002': 10478,
  '2003': 10543,
  '2004': 11365,
  '2005': 11782,
  '2006': 12839,
  '2007': 13400,
  '2008': 12743,
  '2009': 12482,
  '2010': 12653,
  '2011': 12778,
  '2012': 12883,
  '2013': 13056,
  '2014': 12537,
  '2015': 13071,
  '2016': 13757,
  'State': 'Nevada',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06a8')},
 {'1978': '1274',
  '1979': 1475,
  '1980': 1739,
  '1981': 2030,
  '1982': 2634,
  '1983': 3024,
  '1984': 3260,
  '1985': 3512,
  '1986': 4326,
  '1987': 4153,
  '1988': 4539,
  '1989': 4674,
  '1990': 4916,
  '1991': 5370,
  '1992': 5611,
  '1993': 5975,
  '1994': 6552,
  '1995': 7183,
  '1996': 7713,
  '1997': 8329,
  '1998': 8908,
  '1999': 8763,
  '2000': 9217,
  '2001': 9392,
  '2002': 9627,
  '2003': 9663,
  '2004': 10487,
  '2005': 10838,
  '2006': 11709,
  '2007': 12221,
  '2008': 11761,
  '2009': 11533,
  '2010': 11689,
  '2011': 11811,
  '2012': 11845,
  '2013': 11971,
  '2014': 11452,
  '2015': 11905,
  '2016': 12490,
  'State': 'Nevada',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06a9')},
 {'1978': '76',
  '1979': 91,
  '1980': 100,
  '1981': 86,
  '1982': 119,
  '1983': 164,
  '1984': 228,
  '1985': 259,
  '1986': 225,
  '1987': 281,
  '1988': 342,
  '1989': 438,
  '1990': 406,
  '1991': 453,
  '1992': 438,
  '1993': 437,
  '1994': 441,
  '1995': 530,
  '1996': 612,
  '1997': 695,
  '1998': 743,
  '1999': 731,
  '2000': 846,
  '2001': 841,
  '2002': 851,
  '2003': 880,
  '2004': 878,
  '2005': 944,
  '2006': 1130,
  '2007': 1179,
  '2008': 982,
  '2009': 949,
  '2010': 964,
  '2011': 967,
  '2012': 1038,
  '2013': 1085,
  '2014': 1085,
  '2015': 1166,
  '2016': 1267,
  'State': 'Nevada',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06aa')},
 {'1978': '283',
  '1979': 316,
  '1980': 326,
  '1981': 398,
  '1982': 445,
  '1983': 479,
  '1984': 581,
  '1985': 683,
  '1986': 782,
  '1987': 867,
  '1988': 1019,
  '1989': 1166,
  '1990': 1342,
  '1991': 1533,
  '1992': 1777,
  '1993': 1775,
  '1994': 2021,
  '1995': 2015,
  '1996': 2062,
  '1997': 2168,
  '1998': 2169,
  '1999': 2257,
  '2000': 2257,
  '2001': 2392,
  '2002': 2451,
  '2003': 2434,
  '2004': 2448,
  '2005': 2530,
  '2006': 2805,
  '2007': 2943,
  '2008': 2702,
  '2009': 2731,
  '2010': 2761,
  '2011': 2614,
  '2012': 2790,
  '2013': 3018,
  '2014': 2963,
  '2015': 2897,
  '2016': 2818,
  'State': 'New Hampshire',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06ab')},
 {'1978': '277',
  '1979': 311,
  '1980': 321,
  '1981': 391,
  '1982': 435,
  '1983': 465,
  '1984': 567,
  '1985': 665,
  '1986': 760,
  '1987': 849,
  '1988': 995,
  '1989': 1128,
  '1990': 1298,
  '1991': 1460,
  '1992': 1698,
  '1993': 1689,
  '1994': 1911,
  '1995': 1906,
  '1996': 1957,
  '1997': 2059,
  '1998': 2053,
  '1999': 2140,
  '2000': 2137,
  '2001': 2263,
  '2002': 2307,
  '2003': 2317,
  '2004': 2329,
  '2005': 2397,
  '2006': 2633,
  '2007': 2741,
  '2008': 2521,
  '2009': 2564,
  '2010': 2560,
  '2011': 2444,
  '2012': 2583,
  '2013': 2781,
  '2014': 2715,
  '2015': 2661,
  '2016': 2591,
  'State': 'New Hampshire',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06ac')},
 {'1978': '6',
  '1979': 5,
  '1980': 5,
  '1981': 7,
  '1982': 10,
  '1983': 14,
  '1984': 14,
  '1985': 18,
  '1986': 22,
  '1987': 18,
  '1988': 24,
  '1989': 38,
  '1990': 44,
  '1991': 73,
  '1992': 79,
  '1993': 86,
  '1994': 110,
  '1995': 109,
  '1996': 105,
  '1997': 109,
  '1998': 116,
  '1999': 117,
  '2000': 120,
  '2001': 129,
  '2002': 144,
  '2003': 117,
  '2004': 119,
  '2005': 133,
  '2006': 172,
  '2007': 202,
  '2008': 181,
  '2009': 167,
  '2010': 201,
  '2011': 170,
  '2012': 207,
  '2013': 237,
  '2014': 248,
  '2015': 236,
  '2016': 227,
  'State': 'New Hampshire',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06ad')},
 {'1978': '5869',
  '1979': 5852,
  '1980': 5884,
  '1981': 7011,
  '1982': 8191,
  '1983': 9192,
  '1984': 10363,
  '1985': 11335,
  '1986': 12020,
  '1987': 15969,
  '1988': 16936,
  '1989': 19439,
  '1990': 21128,
  '1991': 23483,
  '1992': 22653,
  '1993': 23831,
  '1994': 24632,
  '1995': 27066,
  '1996': 27490,
  '1997': 28361,
  '1998': 31121,
  '1999': 31493,
  '2000': 29784,
  '2001': 28142,
  '2002': 27891,
  '2003': 27246,
  '2004': 26757,
  '2005': 27359,
  '2006': 27371,
  '2007': 26827,
  '2008': 25953,
  '2009': 25382,
  '2010': 25007,
  '2011': 23834,
  '2012': 23225,
  '2013': 22452,
  '2014': 21590,
  '2015': 20489,
  '2016': 19786,
  'State': 'New Jersey',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06ae')},
 {'1978': '5693',
  '1979': 5664,
  '1980': 5686,
  '1981': 6725,
  '1982': 7867,
  '1983': 8850,
  '1984': 9995,
  '1985': 10947,
  '1986': 11603,
  '1987': 15382,
  '1988': 16232,
  '1989': 18553,
  '1990': 20087,
  '1991': 22376,
  '1992': 21558,
  '1993': 22698,
  '1994': 23464,
  '1995': 25759,
  '1996': 26209,
  '1997': 26957,
  '1998': 29468,
  '1999': 29631,
  '2000': 28134,
  '2001': 26514,
  '2002': 26305,
  '2003': 25729,
  '2004': 25287,
  '2005': 25910,
  '2006': 25943,
  '2007': 25417,
  '2008': 24654,
  '2009': 24176,
  '2010': 23871,
  '2011': 22762,
  '2012': 22164,
  '2013': 21427,
  '2014': 20571,
  '2015': 19581,
  '2016': 18952,
  'State': 'New Jersey',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06af')},
 {'1978': '176',
  '1979': 188,
  '1980': 198,
  '1981': 286,
  '1982': 324,
  '1983': 342,
  '1984': 368,
  '1985': 388,
  '1986': 417,
  '1987': 587,
  '1988': 704,
  '1989': 886,
  '1990': 1041,
  '1991': 1107,
  '1992': 1095,
  '1993': 1133,
  '1994': 1168,
  '1995': 1307,
  '1996': 1281,
  '1997': 1404,
  '1998': 1653,
  '1999': 1862,
  '2000': 1650,
  '2001': 1628,
  '2002': 1586,
  '2003': 1517,
  '2004': 1470,
  '2005': 1449,
  '2006': 1428,
  '2007': 1410,
  '2008': 1299,
  '2009': 1206,
  '2010': 1136,
  '2011': 1072,
  '2012': 1061,
  '2013': 1025,
  '2014': 1019,
  '2015': 908,
  '2016': 834,
  'State': 'New Jersey',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06b0')},
 {'1978': '1593',
  '1979': 1556,
  '1980': 1279,
  '1981': 1497,
  '1982': 1718,
  '1983': 1977,
  '1984': 2129,
  '1985': 2313,
  '1986': 2416,
  '1987': 2670,
  '1988': 2825,

  '1989': 3158,
  '1990': 3187,
  '1991': 3119,
  '1992': 3271,
  '1993': 3498,
  '1994': 3712,
  '1995': 4078,
  '1996': 4724,
  '1997': 4688,
  '1998': 5078,
  '1999': 5174,
  '2000': 5342,
  '2001': 5668,
  '2002': 5991,
  '2003': 6223,
  '2004': 6379,
  '2005': 6571,
  '2006': 6639,
  '2007': 6466,
  '2008': 6322,
  '2009': 6363,
  '2010': 6763,
  '2011': 6998,
  '2012': 6727,
  '2013': 6931,
  '2014': 7021,
  '2015': 7104,
  '2016': 7055,
  'State': 'New Mexico',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06b1')},
 {'1978': '1526',
  '1979': 1509,
  '1980': 1222,
  '1981': 1407,
  '1982': 1635,
  '1983': 1906,
  '1984': 2044,
  '1985': 2187,
  '1986': 2273,
  '1987': 2533,
  '1988': 2675,
  '1989': 2994,
  '1990': 2994,
  '1991': 2959,
  '1992': 3087,
  '1993': 3292,
  '1994': 3521,
  '1995': 3800,
  '1996': 4346,
  '1997': 4314,
  '1998': 4628,
  '1999': 4805,
  '2000': 4831,
  '2001': 5151,
  '2002': 5473,
  '2003': 5647,
  '2004': 5798,
  '2005': 5905,
  '2006': 5972,
  '2007': 5890,
  '2008': 5754,
  '2009': 5775,
  '2010': 6161,
  '2011': 6366,
  '2012': 6096,
  '2013': 6276,
  '2014': 6348,
  '2015': 6398,
  '2016': 6344,
  'State': 'New Mexico',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06b2')},
 {'1978': '67',
  '1979': 47,
  '1980': 57,
  '1981': 90,
  '1982': 83,
  '1983': 71,
  '1984': 85,
  '1985': 126,
  '1986': 143,
  '1987': 137,
  '1988': 150,
  '1989': 164,
  '1990': 193,
  '1991': 160,
  '1992': 184,
  '1993': 206,
  '1994': 191,
  '1995': 278,
  '1996': 378,
  '1997': 374,
  '1998': 450,
  '1999': 369,
  '2000': 511,
  '2001': 517,
  '2002': 518,
  '2003': 576,
  '2004': 581,
  '2005': 666,
  '2006': 667,
  '2007': 576,
  '2008': 568,
  '2009': 588,
  '2010': 602,
  '2011': 632,
  '2012': 631,
  '2013': 655,
  '2014': 673,
  '2015': 706,
  '2016': 711,
  'State': 'New Mexico',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06b3')},
 {'1978': '20459',
  '1979': 20856,
  '1980': 21815,
  '1981': 25494,
  '1982': 27945,
  '1983': 30510,
  '1984': 33109,
  '1985': 34507,
  '1986': 38449,
  '1987': 40842,
  '1988': 44560,
  '1989': 51232,
  '1990': 54895,
  '1991': 57862,
  '1992': 61736,
  '1993': 64569,
  '1994': 66750,
  '1995': 68486,
  '1996': 69709,
  '1997': 69108,
  '1998': 72289,
  '1999': 72899,
  '2000': 70199,
  '2001': 67533,
  '2002': 67065,
  '2003': 65198,
  '2004': 63751,
  '2005': 62743,
  '2006': 63315,
  '2007': 62620,
  '2008': 60347,
  '2009': 58687,
  '2010': 56656,
  '2011': 55436,
  '2012': 54210,
  '2013': 53550,
  '2014': 52518,
  '2015': 51727,
  '2016': 50716,
  'State': 'New York',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06b4')},
 {'1978': '19899',
  '1979': 20259,
  '1980': 21202,
  '1981': 24728,
  '1982': 27127,
  '1983': 29679,
  '1984': 32091,
  '1985': 33422,
  '1986': 37123,
  '1987': 39355,
  '1988': 42800,
  '1989': 48767,
  '1990': 52204,
  '1991': 54494,
  '1992': 58237,
  '1993': 61041,
  '1994': 63175,
  '1995': 64871,
  '1996': 65981,
  '1997': 65539,
  '1998': 68686,
  '1999': 69279,
  '2000': 66919,
  '2001': 64400,
  '2002': 64069,
  '2003': 62284,
  '2004': 60962,
  '2005': 59941,
  '2006': 60456,
  '2007': 59866,
  '2008': 57760,
  '2009': 56198,
  '2010': 54438,
  '2011': 53124,
  '2012': 51963,
  '2013': 51193,
  '2014': 50192,
  '2015': 49373,
  '2016': 48442,
  'State': 'New York',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06b5')},
 {'1978': '560',
  '1979': 597,
  '1980': 613,
  '1981': 766,
  '1982': 818,
  '1983': 831,
  '1984': 1018,
  '1985': 1085,
  '1986': 1326,
  '1987': 1487,
  '1988': 1760,
  '1989': 2465,
  '1990': 2691,
  '1991': 3368,
  '1992': 3499,
  '1993': 3528,
  '1994': 3575,
  '1995': 3615,
  '1996': 3728,
  '1997': 3569,
  '1998': 3603,
  '1999': 3620,
  '2000': 3280,
  '2001': 3133,
  '2002': 2996,
  '2003': 2914,
  '2004': 2789,
  '2005': 2802,
  '2006': 2859,
  '2007': 2754,
  '2008': 2587,
  '2009': 2489,
  '2010': 2218,
  '2011': 2312,
  '2012': 2247,
  '2013': 2357,
  '2014': 2326,
  '2015': 2354,
  '2016': 2274,
  'State': 'New York',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06b6')},
 {'1978': '13252',
  '1979': 14255,
  '1980': 15513,
  '1981': 15770,
  '1982': 16569,
  '1983': 15395,
  '1984': 16371,
  '1985': 17344,
  '1986': 17698,
  '1987': 17218,
  '1988': 17078,
  '1989': 17454,
  '1990': 18411,
  '1991': 18903,
  '1992': 20454,
  '1993': 21892,
  '1994': 23648,
  '1995': 29253,
  '1996': 30647,
  '1997': 31612,
  '1998': 31961,
  '1999': 31086,
  '2000': 31266,
  '2001': 32253,
  '2002': 32832,
  '2003': 33560,
  '2004': 35434,
  '2005': 36365,
  '2006': 37460,
  '2007': 37970,
  '2008': 39482,
  '2009': 39860,
  '2010': 40382,
  '2011': 39440,
  '2012': 37136,
  '2013': 36922,
  '2014': 37096,
  '2015': 36617,
  '2016': 35697,
  'State': 'North Carolina',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06b7')},
 {'1978': '12718',
  '1979': 13691,
  '1980': 14897,
  '1981': 15133,
  '1982': 15873,
  '1983': 14806,
  '1984': 15669,
  '1985': 16597,
  '1986': 16868,
  '1987': 16410,
  '1988': 16295,
  '1989': 16611,
  '1990': 17466,
  '1991': 17882,
  '1992': 19504,
  '1993': 20772,
  '1994': 22465,
  '1995': 27501,
  '1996': 28779,
  '1997': 29752,
  '1998': 30023,
  '1999': 29206,
  '2000': 29363,
  '2001': 30211,
  '2002': 30659,
  '2003': 31304,
  '2004': 33004,
  '2005': 33776,
  '2006': 34774,
  '2007': 35344,
  '2008': 36704,
  '2009': 37052,
  '2010': 37563,
  '2011': 36800,
  '2012': 34675,
  '2013': 34430,
  '2014': 34455,
  '2015': 33928,
  '2016': 32985,
  'State': 'North Carolina',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06b8')},
 {'1978': '534',
  '1979': 564,
  '1980': 616,
  '1981': 637,
  '1982': 696,
  '1983': 589,
  '1984': 702,
  '1985': 747,
  '1986': 830,
  '1987': 808,
  '1988': 783,
  '1989': 843,
  '1990': 945,
  '1991': 1021,
  '1992': 950,
  '1993': 1120,
  '1994': 1183,
  '1995': 1752,
  '1996': 1868,
  '1997': 1860,
  '1998': 1938,
  '1999': 1880,
  '2000': 1903,
  '2001': 2042,
  '2002': 2173,
  '2003': 2256,
  '2004': 2430,
  '2005': 2589,
  '2006': 2686,
  '2007': 2626,
  '2008': 2778,
  '2009': 2808,
  '2010': 2819,
  '2011': 2640,
  '2012': 2461,
  '2013': 2492,
  '2014': 2641,
  '2015': 2689,
  '2016': 2712,
  'State': 'North Carolina',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06b9')},
 {'1978': '200',
  '1979': 186,
  '1980': 253,
  '1981': 280,
  '1982': 322,
  '1983': 410,
  '1984': 432,
  '1985': 422,
  '1986': 421,
  '1987': 430,
  '1988': 466,
  '1989': 451,
  '1990': 483,
  '1991': 492,
  '1992': 477,
  '1993': 498,
  '1994': 536,
  '1995': 608,
  '1996': 722,
  '1997': 797,
  '1998': 915,
  '1999': 943,
  '2000': 1076,
  '2001': 1111,
  '2002': 1112,
  '2003': 1239,
  '2004': 1327,
  '2005': 1385,
  '2006': 1363,
  '2007': 1416,
  '2008': 1452,
  '2009': 1486,
  '2010': 1487,
  '2011': 1423,
  '2012': 1512,
  '2013': 1576,
  '2014': 1718,
  '2015': 1795,
  '2016': 1791,
  'State': 'North Dakota',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06ba')},
 {'1978': '196',
  '1979': 184,
  '1980': 251,
  '1981': 277,
  '1982': 312,
  '1983': 400,
  '1984': 420,
  '1985': 413,
  '1986': 410,
  '1987': 423,
  '1988': 458,
  '1989': 430,
  '1990': 463,
  '1991': 461,
  '1992': 463,
  '1993': 477,
  '1994': 520,
  '1995': 579,
  '1996': 677,
  '1997': 735,
  '1998': 846,
  '1999': 873,
  '2000': 1008,
  '2001': 1010,
  '2002': 1009,
  '2003': 1126,
  '2004': 1198,
  '2005': 1230,
  '2006': 1206,
  '2007': 1269,
  '2008': 1292,
  '2009': 1312,
  '2010': 1308,
  '2011': 1276,
  '2012': 1341,
  '2013': 1419,
  '2014': 1514,
  '2015': 1587,
  '2016': 1578,
  'State': 'North Dakota',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06bb')},
 {'1978': '4',
  '1979': 2,
  '1980': 2,
  '1981': 3,
  '1982': 10,
  '1983': 10,
  '1984': 12,
  '1985': 9,
  '1986': 11,
  '1987': 7,
  '1988': 8,
  '1989': 21,
  '1990': 20,
  '1991': 31,
  '1992': 14,
  '1993': 21,
  '1994': 16,
  '1995': 29,
  '1996': 45,
  '1997': 62,
  '1998': 69,
  '1999': 70,
  '2000': 68,
  '2001': 101,
  '2002': 103,
  '2003': 113,
  '2004': 129,
  '2005': 155,
  '2006': 157,
  '2007': 147,
  '2008': 160,
  '2009': 174,
  '2010': 179,
  '2011': 147,
  '2012': 171,
  '2013': 157,
  '2014': 204,
  '2015': 208,
  '2016': 213,
  'State': 'North Dakota',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06bc')},
 {'1978': '13107',
  '1979': 13360,
  '1980': 13489,
  '1981': 14968,
  '1982': 17317,
  '1983': 18007,
  '1984': 18619,
  '1985': 20864,
  '1986': 22463,
  '1987': 24240,
  '1988': 26462,
  '1989': 30538,
  '1990': 31822,
  '1991': 35744,
  '1992': 38378,
  '1993': 40641,
  '1994': 41908,
  '1995': 44663,
  '1996': 46174,
  '1997': 48016,
  '1998': 48450,
  '1999': 46842,
  '2000': 45833,
  '2001': 45281,
  '2002': 45646,
  '2003': 44778,
  '2004': 44806,
  '2005': 45854,
  '2006': 49166,
  '2007': 50731,
  '2008': 51686,
  '2009': 51606,
  '2010': 51712,
  '2011': 50964,
  '2012': 50876,
  '2013': 51729,
  '2014': 51519,
  '2015': 52233,
  '2016': 52175,
  'State': 'Ohio',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06bd')},
 {'1978': '12569',
  '1979': 12762,
  '1980': 12857,
  '1981': 14205,
  '1982': 16417,
  '1983': 17030,
  '1984': 17601,
  '1985': 19711,
  '1986': 21250,
  '1987': 22945,
  '1988': 24885,
  '1989': 28543,
  '1990': 29875,
  '1991': 33451,
  '1992': 35959,
  '1993': 38057,
  '1994': 39313,
  '1995': 41870,
  '1996': 43369,
  '1997': 45174,
  '1998': 45538,
  '1999': 44001,
  '2000': 43025,
  '2001': 42452,
  '2002': 42717,
  '2003': 41881,
  '2004': 41621,
  '2005': 42594,
  '2006': 45465,
  '2007': 46909,
  '2008': 47773,
  '2009': 47617,
  '2010': 47720,
  '2011': 47061,
  '2012': 47008,
  '2013': 47579,
  '2014': 47311,
  '2015': 47803,
  '2016': 47581,
  'State': 'Ohio',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06be')},
 {'1978': '538',
  '1979': 598,
  '1980': 632,
  '1981': 763,
  '1982': 900,
  '1983': 977,
  '1984': 1018,
  '1985': 1153,
  '1986': 1213,
  '1987': 1295,
  '1988': 1577,
  '1989': 1995,
  '1990': 1947,
  '1991': 2293,
  '1992': 2419,
  '1993': 2584,
  '1994': 2595,
  '1995': 2793,
  '1996': 2805,
  '1997': 2842,
  '1998': 2912,
  '1999': 2841,
  '2000': 2808,
  '2001': 2829,
  '2002': 2929,
  '2003': 2897,
  '2004': 3185,
  '2005': 3260,
  '2006': 3701,
  '2007': 3822,
  '2008': 3913,
  '2009': 3989,
  '2010': 3992,
  '2011': 3903,
  '2012': 3868,
  '2013': 4150,
  '2014': 4208,
  '2015': 4430,
  '2016': 4594,
  'State': 'Ohio',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06bf')},
 {'1978': '4186',
  '1979': 4250,
  '1980': 4796,
  '1981': 5281,
  '1982': 6500,
  '1983': 7480,
  '1984': 7872,
  '1985': 8330,
  '1986': 9708,
  '1987': 9639,
  '1988': 10448,
  '1989': 11608,
  '1990': 12285,
  '1991': 13340,
  '1992': 14821,
  '1993': 16409,
  '1994': 16631,
  '1995': 18151,
  '1996': 19593,
  '1997': 20542,
  '1998': 20892,
  '1999': 22393,
  '2000': 23181,
  '2001': 22780,
  '2002': 22802,
  '2003': 22821,
  '2004': 24508,
  '2005': 24826,
  '2006': 24288,
  '2007': 24603,
  '2008': 24660,
  '2009': 24803,
  '2010': 26252,
  '2011': 25977,
  '2012': 25225,
  '2013': 27547,
  '2014': 27650,
  '2015': 28547,
  '2016': 26871,
  'State': 'Oklahoma',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06c0')},
 {'1978': '4010',
  '1979': 4073,
  '1980': 4549,
  '1981': 5006,
  '1982': 6174,
  '1983': 7031,
  '1984': 7400,
  '1985': 7823,
  '1986': 9021,
  '1987': 8945,
  '1988': 9717,
  '1989': 10633,
  '1990': 11214,
  '1991': 12104,
  '1992': 13421,
  '1993': 14827,
  '1994': 15024,
  '1995': 16336,
  '1996': 17653,
  '1997': 18489,
  '1998': 18801,
  '1999': 20077,
  '2000': 20787,
  '2001': 20490,
  '2002': 20464,
  '2003': 20501,
  '2004': 22024,
  '2005': 22371,
  '2006': 21886,
  '2007': 22141,
  '2008': 22165,
  '2009': 22230,
  '2010': 23703,
  '2011': 23558,
  '2012': 22728,
  '2013': 24769,
  '2014': 24799,
  '2015': 25489,
  '2016': 23834,
  'State': 'Oklahoma',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06c1')},
 {'1978': '176',
  '1979': 177,
  '1980': 247,
  '1981': 275,
  '1982': 326,
  '1983': 449,
  '1984': 472,
  '1985': 507,
  '1986': 687,
  '1987': 694,
  '1988': 731,
  '1989': 975,
  '1990': 1071,
  '1991': 1236,
  '1992': 1400,
  '1993': 1582,
  '1994': 1607,
  '1995': 1815,
  '1996': 1940,
  '1997': 2053,
  '1998': 2091,
  '1999': 2316,
  '2000': 2394,
  '2001': 2290,
  '2002': 2338,
  '2003': 2320,
  '2004': 2484,
  '2005': 2455,
  '2006': 2402,
  '2007': 2462,
  '2008': 2495,
  '2009': 2573,
  '2010': 2549,
  '2011': 2419,
  '2012': 2497,
  '2013': 2778,
  '2014': 2851,
  '2015': 3058,
  '2016': 3037,
  'State': 'Oklahoma',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06c2')},
 {'1978': '2879',
  '1979': 3179,
  '1980': 3177,
  '1981': 3295,
  '1982': 3900,
  '1983': 3952,
  '1984': 4224,
  '1985': 4376,
  '1986': 4770,
  '1987': 5457,
  '1988': 5991,
  '1989': 6156,

  '1990': 6492,
  '1991': 6732,
  '1992': 6583,
  '1993': 6557,
  '1994': 6936,
  '1995': 7886,
  '1996': 8661,
  '1997': 7999,
  '1998': 9034,
  '1999': 9860,
  '2000': 10580,
  '2001': 11410,
  '2002': 12085,
  '2003': 12715,
  '2004': 13183,
  '2005': 13411,
  '2006': 13707,
  '2007': 13948,
  '2008': 14167,
  '2009': 14403,
  '2010': 14876,
  '2011': 14510,
  '2012': 14840,
  '2013': 15517,
  '2014': 15075,
  '2015': 15245,
  '2016': 15166,
  'State': 'Oregon',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06c3')},
 {'1978': '2757',
  '1979': 3059,
  '1980': 3077,
  '1981': 3192,
  '1982': 3760,
  '1983': 3807,
  '1984': 4054,
  '1985': 4188,
  '1986': 4532,
  '1987': 5152,
  '1988': 5644,
  '1989': 5816,
  '1990': 6130,
  '1991': 6323,
  '1992': 6244,
  '1993': 6217,
  '1994': 6557,
  '1995': 7421,
  '1996': 8090,
  '1997': 7549,
  '1998': 8509,
  '1999': 9276,
  '2000': 9984,
  '2001': 10749,
  '2002': 11273,
  '2003': 11832,
  '2004': 12198,
  '2005': 12396,
  '2006': 12687,
  '2007': 12888,
  '2008': 13058,
  '2009': 13278,
  '2010': 13745,
  '2011': 13387,
  '2012': 13609,
  '2013': 14212,
  '2014': 13799,
  '2015': 13938,
  '2016': 13862,
  'State': 'Oregon',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06c4')},
 {'1978': '122',
  '1979': 120,
  '1980': 100,
  '1981': 103,
  '1982': 140,
  '1983': 145,
  '1984': 170,
  '1985': 188,
  '1986': 238,
  '1987': 305,
  '1988': 347,
  '1989': 340,
  '1990': 362,
  '1991': 409,
  '1992': 339,
  '1993': 340,
  '1994': 379,
  '1995': 465,
  '1996': 571,
  '1997': 450,
  '1998': 525,
  '1999': 584,
  '2000': 596,
  '2001': 661,
  '2002': 812,
  '2003': 883,
  '2004': 985,
  '2005': 1015,
  '2006': 1020,
  '2007': 1060,
  '2008': 1109,
  '2009': 1125,
  '2010': 1131,
  '2011': 1123,
  '2012': 1231,
  '2013': 1305,
  '2014': 1276,
  '2015': 1307,
  '2016': 1304,
  'State': 'Oregon',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06c5')},
 {'1978': '7814',
  '1979': 7772,
  '1980': 8171,
  '1981': 9365,
  '1982': 10508,
  '1983': 11767,
  '1984': 13090,
  '1985': 14227,
  '1986': 15201,
  '1987': 16267,
  '1988': 17900,
  '1989': 20469,
  '1990': 22290,
  '1991': 23388,
  '1992': 24974,
  '1993': 26050,
  '1994': 28302,
  '1995': 32416,
  '1996': 34537,
  '1997': 34964,
  '1998': 36377,
  '1999': 36525,
  '2000': 36847,
  '2001': 38062,
  '2002': 40168,
  '2003': 40890,
  '2004': 40963,
  '2005': 42380,
  '2006': 44397,
  '2007': 45969,
  '2008': 49215,
  '2009': 51429,
  '2010': 51264,
  '2011': 51578,
  '2012': 51125,
  '2013': 51422,
  '2014': 50694,
  '2015': 49858,
  '2016': 49244,
  'State': 'Pennsylvania',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06c6')},
 {'1978': '7585',
  '1979': 7524,
  '1980': 7899,
  '1981': 9053,
  '1982': 10180,
  '1983': 11370,
  '1984': 12615,
  '1985': 13727,
  '1986': 14610,
  '1987': 15588,
  '1988': 17133,
  '1989': 19525,
  '1990': 21284,
  '1991': 22300,
  '1992': 23868,
  '1993': 24856,
  '1994': 26980,
  '1995': 30914,
  '1996': 33060,
  '1997': 33540,
  '1998': 34860,
  '1999': 34907,
  '2000': 35268,
  '2001': 36351,
  '2002': 38347,
  '2003': 39067,
  '2004': 39136,
  '2005': 40351,
  '2006': 42148,
  '2007': 43506,
  '2008': 46451,
  '2009': 48601,
  '2010': 48552,
  '2011': 48795,
  '2012': 48380,
  '2013': 48760,
  '2014': 47936,
  '2015': 47039,
  '2016': 46381,
  'State': 'Pennsylvania',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06c7')},
 {'1978': '229',
  '1979': 248,
  '1980': 272,
  '1981': 312,
  '1982': 328,
  '1983': 397,
  '1984': 475,
  '1985': 500,
  '1986': 591,
  '1987': 679,
  '1988': 767,
  '1989': 944,
  '1990': 1006,
  '1991': 1088,
  '1992': 1106,
  '1993': 1194,
  '1994': 1322,
  '1995': 1502,
  '1996': 1477,
  '1997': 1424,
  '1998': 1517,
  '1999': 1618,
  '2000': 1579,
  '2001': 1711,
  '2002': 1821,
  '2003': 1823,
  '2004': 1827,
  '2005': 2029,
  '2006': 2249,
  '2007': 2463,
  '2008': 2764,
  '2009': 2828,
  '2010': 2712,
  '2011': 2783,
  '2012': 2745,
  '2013': 2662,
  '2014': 2758,
  '2015': 2819,
  '2016': 2863,
  'State': 'Pennsylvania',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06c8')},
 {'1978': '664',
  '1979': 738,
  '1980': 813,
  '1981': 962,
  '1982': 1037,
  '1983': 1157,
  '1984': 1221,
  '1985': 1306,
  '1986': 1358,
  '1987': 1428,
  '1988': 1906,
  '1989': 2479,
  '1990': 2392,
  '1991': 2771,
  '1992': 2775,
  '1993': 2783,
  '1994': 2919,
  '1995': 2902,
  '1996': 3271,
  '1997': 3371,
  '1998': 3445,
  '1999': 3003,
  '2000': 3286,
  '2001': 3241,
  '2002': 3520,
  '2003': 3527,
  '2004': 3430,
  '2005': 3654,
  '2006': 3996,
  '2007': 4018,
  '2008': 4045,
  '2009': 3674,
  '2010': 3357,
  '2011': 3337,
  '2012': 3318,
  '2013': 3361,
  '2014': 3359,
  '2015': 3248,
  '2016': 3103,
  'State': 'Rhode Island',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06c9')},
 {'1978': '648',
  '1979': 721,
  '1980': 787,
  '1981': 937,
  '1982': 1013,
  '1983': 1120,
  '1984': 1188,
  '1985': 1267,
  '1986': 1312,
  '1987': 1348,
  '1988': 1782,
  '1989': 2274,
  '1990': 2226,
  '1991': 2576,
  '1992': 2594,
  '1993': 2628,
  '1994': 2767,
  '1995': 2745,
  '1996': 3042,
  '1997': 3158,
  '1998': 3210,
  '1999': 2815,
  '2000': 3048,
  '2001': 3048,
  '2002': 3306,
  '2003': 3305,
  '2004': 3222,
  '2005': 3423,
  '2006': 3716,
  '2007': 3736,
  '2008': 3802,
  '2009': 3444,
  '2010': 3139,
  '2011': 3158,
  '2012': 3128,
  '2013': 3169,
  '2014': 3201,
  '2015': 3102,
  '2016': 2927,
  'State': 'Rhode Island',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06ca')},
 {'1978': '16',
  '1979': 17,
  '1980': 26,
  '1981': 25,
  '1982': 24,
  '1983': 37,
  '1984': 33,
  '1985': 39,
  '1986': 46,
  '1987': 80,
  '1988': 124,
  '1989': 205,
  '1990': 166,
  '1991': 195,
  '1992': 181,
  '1993': 155,
  '1994': 152,
  '1995': 157,
  '1996': 229,
  '1997': 213,
  '1998': 235,
  '1999': 188,
  '2000': 238,
  '2001': 193,
  '2002': 214,
  '2003': 222,
  '2004': 208,
  '2005': 231,
  '2006': 280,
  '2007': 282,
  '2008': 243,
  '2009': 230,
  '2010': 218,
  '2011': 179,
  '2012': 190,
  '2013': 192,
  '2014': 158,
  '2015': 146,
  '2016': 176,
  'State': 'Rhode Island',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06cb')},
 {'1978': '7536',
  '1979': 7643,
  '1980': 7862,
  '1981': 8538,
  '1982': 9137,
  '1983': 9576,
  '1984': 9892,
  '1985': 10510,
  '1986': 11676,
  '1987': 12664,
  '1988': 13888,
  '1989': 15720,
  '1990': 17319,
  '1991': 18269,
  '1992': 18643,
  '1993': 18704,
  '1994': 18999,
  '1995': 19611,
  '1996': 20446,
  '1997': 21173,
  '1998': 21764,
  '1999': 22008,
  '2000': 21778,
  '2001': 22576,
  '2002': 23715,
  '2003': 23719,
  '2004': 23428,
  '2005': 23160,
  '2006': 23616,
  '2007': 24239,
  '2008': 24326,
  '2009': 24288,
  '2010': 23578,
  '2011': 22914,
  '2012': 22388,
  '2013': 22060,
  '2014': 21401,
  '2015': 20929,
  '2016': 20858,
  'State': 'South Carolina',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06cc')},
 {'1978': '7234',
  '1979': 7327,
  '1980': 7535,
  '1981': 8177,
  '1982': 8732,
  '1983': 9150,
  '1984': 9455,
  '1985': 10009,
  '1986': 11075,
  '1987': 12003,
  '1988': 13089,
  '1989': 14791,
  '1990': 16266,
  '1991': 17224,
  '1992': 17516,
  '1993': 17599,
  '1994': 17977,
  '1995': 18566,
  '1996': 19244,
  '1997': 19871,
  '1998': 20381,
  '1999': 20561,
  '2000': 20358,
  '2001': 21067,
  '2002': 22044,
  '2003': 22143,
  '2004': 21866,
  '2005': 21646,
  '2006': 22013,
  '2007': 22635,
  '2008': 22693,
  '2009': 22771,
  '2010': 22105,
  '2011': 21528,
  '2012': 21051,
  '2013': 20669,
  '2014': 20032,
  '2015': 19574,
  '2016': 19384,
  'State': 'South Carolina',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06cd')},
 {'1978': '302',
  '1979': 316,
  '1980': 327,
  '1981': 361,
  '1982': 405,
  '1983': 426,
  '1984': 437,
  '1985': 501,
  '1986': 601,
  '1987': 661,
  '1988': 799,
  '1989': 929,
  '1990': 1053,
  '1991': 1045,
  '1992': 1127,
  '1993': 1105,
  '1994': 1022,
  '1995': 1045,
  '1996': 1202,
  '1997': 1302,
  '1998': 1383,
  '1999': 1447,
  '2000': 1420,
  '2001': 1509,
  '2002': 1671,
  '2003': 1576,
  '2004': 1562,
  '2005': 1514,
  '2006': 1603,
  '2007': 1604,
  '2008': 1633,
  '2009': 1517,
  '2010': 1473,
  '2011': 1386,
  '2012': 1337,
  '2013': 1391,
  '2014': 1369,
  '2015': 1355,
  '2016': 1474,
  'State': 'South Carolina',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06ce')},
 {'1978': '532',
  '1979': 562,
  '1980': 635,
  '1981': 693,
  '1982': 791,
  '1983': 826,
  '1984': 921,
  '1985': 1049,
  '1986': 1081,
  '1987': 1133,
  '1988': 1020,
  '1989': 1256,
  '1990': 1341,
  '1991': 1374,
  '1992': 1487,
  '1993': 1553,
  '1994': 1708,
  '1995': 1871,
  '1996': 2063,
  '1997': 2242,
  '1998': 2422,
  '1999': 2506,
  '2000': 2616,
  '2001': 2790,
  '2002': 2918,
  '2003': 3026,
  '2004': 3095,
  '2005': 3463,
  '2006': 3359,
  '2007': 3311,
  '2008': 3342,
  '2009': 3434,
  '2010': 3434,
  '2011': 3535,
  '2012': 3650,
  '2013': 3682,
  '2014': 3608,
  '2015': 3564,
  '2016': 3831,
  'State': 'South Dakota',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06cf')},
 {'1978': '514',
  '1979': 538,
  '1980': 617,
  '1981': 664,
  '1982': 748,
  '1983': 785,
  '1984': 889,
  '1985': 1008,
  '1986': 1032,
  '1987': 1080,
  '1988': 974,
  '1989': 1175,
  '1990': 1264,
  '1991': 1294,
  '1992': 1408,
  '1993': 1465,
  '1994': 1605,
  '1995': 1737,
  '1996': 1922,
  '1997': 2073,
  '1998': 2219,
  '1999': 2317,
  '2000': 2416,
  '2001': 2570,
  '2002': 2691,
  '2003': 2757,
  '2004': 2803,
  '2005': 3107,
  '2006': 3009,
  '2007': 2942,
  '2008': 2987,
  '2009': 3054,
  '2010': 3023,
  '2011': 3094,
  '2012': 3227,
  '2013': 3240,
  '2014': 3199,
  '2015': 3148,
  '2016': 3333,
  'State': 'South Dakota',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06d0')},
 {'1978': '18',
  '1979': 24,
  '1980': 18,
  '1981': 29,
  '1982': 43,
  '1983': 41,
  '1984': 32,
  '1985': 41,
  '1986': 49,
  '1987': 53,
  '1988': 46,
  '1989': 81,
  '1990': 77,
  '1991': 80,
  '1992': 79,
  '1993': 88,
  '1994': 103,
  '1995': 134,
  '1996': 141,
  '1997': 169,
  '1998': 203,
  '1999': 189,
  '2000': 200,
  '2001': 220,
  '2002': 227,
  '2003': 269,
  '2004': 292,
  '2005': 356,
  '2006': 350,
  '2007': 369,
  '2008': 355,
  '2009': 380,
  '2010': 411,
  '2011': 441,
  '2012': 423,
  '2013': 442,
  '2014': 409,
  '2015': 416,
  '2016': 498,
  'State': 'South Dakota',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06d1')},
 {'1978': '5835',
  '1979': 6629,
  '1980': 7022,
  '1981': 7897,
  '1982': 7869,
  '1983': 8201,
  '1984': 7307,
  '1985': 7127,
  '1986': 7591,
  '1987': 7639,
  '1988': 7732,
  '1989': 10630,
  '1990': 10388,
  '1991': 11474,
  '1992': 11849,
  '1993': 12824,
  '1994': 14401,
  '1995': 15206,
  '1996': 15626,
  '1997': 16659,
  '1998': 21438,
  '1999': 22502,
  '2000': 22166,
  '2001': 23671,
  '2002': 24989,
  '2003': 25403,
  '2004': 25884,
  '2005': 26369,
  '2006': 25745,
  '2007': 26267,
  '2008': 27228,
  '2009': 26965,
  '2010': 27451,
  '2011': 28479,
  '2012': 28411,
  '2013': 28521,
  '2014': 28769,
  '2015': 28172,
  '2016': 28203,
  'State': 'Tennessee',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06d2')},
 {'1978': '5574',
  '1979': 6346,
  '1980': 6686,
  '1981': 7502,
  '1982': 7489,
  '1983': 7803,
  '1984': 6993,
  '1985': 6825,
  '1986': 7178,
  '1987': 7249,
  '1988': 7330,
  '1989': 10159,
  '1990': 9998,
  '1991': 11015,
  '1992': 11321,
  '1993': 12316,
  '1994': 13814,
  '1995': 14569,
  '1996': 14938,
  '1997': 15861,
  '1998': 20178,
  '1999': 21134,
  '2000': 20797,
  '2001': 22203,
  '2002': 23254,
  '2003': 23577,
  '2004': 23979,
  '2005': 24347,
  '2006': 23787,
  '2007': 24344,
  '2008': 25099,
  '2009': 24956,
  '2010': 25345,
  '2011': 26070,
  '2012': 26048,
  '2013': 26069,
  '2014': 26160,
  '2015': 25532,
  '2016': 25481,
  'State': 'Tennessee',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06d3')},
 {'1978': '261',
  '1979': 283,
  '1980': 336,
  '1981': 395,
  '1982': 380,
  '1983': 398,
  '1984': 314,
  '1985': 302,
  '1986': 413,
  '1987': 390,
  '1988': 402,
  '1989': 471,
  '1990': 390,
  '1991': 459,
  '1992': 528,
  '1993': 508,
  '1994': 587,
  '1995': 637,
  '1996': 688,
  '1997': 798,
  '1998': 1260,
  '1999': 1368,
  '2000': 1369,
  '2001': 1468,
  '2002': 1735,
  '2003': 1826,
  '2004': 1905,
  '2005': 2022,
  '2006': 1958,
  '2007': 1923,
  '2008': 2129,
  '2009': 2009,
  '2010': 2106,
  '2011': 2409,
  '2012': 2363,
  '2013': 2452,
  '2014': 2609,
  '2015': 2640,
  '2016': 2722,
  'State': 'Tennessee',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06d4')},
 {'1978': '24575',
  '1979': 26522,
  '1980': 29892,
  '1981': 31502,
  '1982': 36149,
  '1983': 35259,
  '1984': 36682,
  '1985': 37532,
  '1986': 38534,
  '1987': 38821,
  '1988': 40437,
  '1989': 44022,
  '1990': 50042,
  '1991': 51677,
  '1992': 60467,
  '1993': 92013,
  '1994': 118195,
  '1995': 127766,
  '1996': 132383,
  '1997': 140351,
  '1998': 144510,
  '1999': 163190,
  '2000': 166719,
  '2001': 162070,
  '2002': 162003,
  '2003': 166911,
  '2004': 168105,
  '2005': 169003,
  '2006': 172116,

  '2007': 171790,
  '2008': 172506,
  '2009': 171249,
  '2010': 173649,
  '2011': 172224,
  '2012': 166372,
  '2013': 168280,
  '2014': 166043,
  '2015': 163909,
  '2016': 163703,
  'State': 'Texas',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06d5')},
 {'1978': '23570',
  '1979': 25355,
  '1980': 28671,
  '1981': 30050,
  '1982': 34472,
  '1983': 33789,
  '1984': 34987,
  '1985': 35938,
  '1986': 36789,
  '1987': 37279,
  '1988': 38789,
  '1989': 41953,
  '1990': 47846,
  '1991': 49186,
  '1992': 58056,
  '1993': 85064,
  '1994': 109356,
  '1995': 119831,
  '1996': 122450,
  '1997': 130051,
  '1998': 134178,
  '1999': 150688,
  '2000': 153097,
  '2001': 149701,
  '2002': 148952,
  '2003': 153424,
  '2004': 154147,
  '2005': 155497,
  '2006': 158317,
  '2007': 157859,
  '2008': 158653,
  '2009': 157679,
  '2010': 159298,
  '2011': 158036,
  '2012': 152823,
  '2013': 154450,
  '2014': 151717,
  '2015': 149501,
  '2016': 149368,
  'State': 'Texas',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06d6')},
 {'1978': '1005',
  '1979': 1167,
  '1980': 1221,
  '1981': 1452,
  '1982': 1677,
  '1983': 1470,
  '1984': 1695,
  '1985': 1594,
  '1986': 1745,
  '1987': 1542,
  '1988': 1648,
  '1989': 2069,
  '1990': 2196,
  '1991': 2491,
  '1992': 2411,
  '1993': 6949,
  '1994': 8839,
  '1995': 7935,
  '1996': 9933,
  '1997': 10300,
  '1998': 10332,
  '1999': 12502,
  '2000': 13622,
  '2001': 12369,
  '2002': 13051,
  '2003': 13487,
  '2004': 13958,
  '2005': 13506,
  '2006': 13799,
  '2007': 13931,
  '2008': 13853,
  '2009': 13570,
  '2010': 14351,
  '2011': 14188,
  '2012': 13549,
  '2013': 13830,
  '2014': 14326,
  '2015': 14408,
  '2016': 14335,
  'State': 'Texas',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06d7')},
 {'1978': '911',
  '1979': 960,
  '1980': 932,
  '1981': 1140,
  '1982': 1216,
  '1983': 1274,
  '1984': 1504,
  '1985': 1633,
  '1986': 1776,
  '1987': 1853,
  '1988': 1961,
  '1989': 2394,
  '1990': 2496,
  '1991': 2625,
  '1992': 2699,
  '1993': 2888,
  '1994': 3045,
  '1995': 3471,
  '1996': 4002,
  '1997': 4301,
  '1998': 4907,
  '1999': 5322,
  '2000': 5637,
  '2001': 5339,
  '2002': 5562,
  '2003': 5763,
  '2004': 5991,
  '2005': 6382,
  '2006': 6433,
  '2007': 6515,
  '2008': 6552,
  '2009': 6538,
  '2010': 6807,
  '2011': 6879,
  '2012': 6962,
  '2013': 7077,
  '2014': 7031,
  '2015': 6495,
  '2016': 6182,
  'State': 'Utah',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06d8')},
 {'1978': '875',
  '1979': 926,
  '1980': 905,
  '1981': 1099,
  '1982': 1169,
  '1983': 1223,
  '1984': 1456,
  '1985': 1570,
  '1986': 1704,
  '1987': 1778,
  '1988': 1872,
  '1989': 2285,
  '1990': 2371,
  '1991': 2505,
  '1992': 2575,
  '1993': 2765,
  '1994': 2914,
  '1995': 3310,
  '1996': 3791,
  '1997': 4088,
  '1998': 4590,
  '1999': 4967,
  '2000': 5256,
  '2001': 5024,
  '2002': 5191,
  '2003': 5336,
  '2004': 5480,
  '2005': 5807,
  '2006': 5810,
  '2007': 5883,
  '2008': 5912,
  '2009': 5956,
  '2010': 6199,
  '2011': 6266,
  '2012': 6323,
  '2013': 6415,
  '2014': 6369,
  '2015': 5980,
  '2016': 5777,
  'State': 'Utah',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06d9')},
 {'1978': '36',
  '1979': 34,
  '1980': 27,
  '1981': 41,
  '1982': 47,
  '1983': 51,
  '1984': 48,
  '1985': 63,
  '1986': 72,
  '1987': 75,
  '1988': 89,
  '1989': 109,
  '1990': 125,
  '1991': 120,
  '1992': 124,
  '1993': 123,
  '1994': 131,
  '1995': 161,
  '1996': 211,
  '1997': 213,
  '1998': 317,
  '1999': 355,
  '2000': 381,
  '2001': 315,
  '2002': 371,
  '2003': 427,
  '2004': 511,
  '2005': 575,
  '2006': 623,
  '2007': 632,
  '2008': 640,
  '2009': 582,
  '2010': 608,
  '2011': 613,
  '2012': 639,
  '2013': 662,
  '2014': 662,
  '2015': 515,
  '2016': 405,
  'State': 'Utah',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06da')},
 {'1978': '441',
  '1979': 431,
  '1980': 480,
  '1981': 534,
  '1982': 599,
  '1983': 497,
  '1984': 501,
  '1985': 677,
  '1986': 697,
  '1987': 759,
  '1988': 820,
  '1989': 905,
  '1990': 1049,
  '1991': 1118,
  '1992': 1254,
  '1993': 1223,
  '1994': 1301,
  '1995': 1279,
  '1996': 1119,
  '1997': 1270,
  '1998': 1473,
  '1999': 1536,
  '2000': 1697,
  '2001': 1741,
  '2002': 1863,
  '2003': 1944,
  '2004': 1968,
  '2005': 2078,
  '2006': 2215,
  '2007': 2116,
  '2008': 2116,
  '2009': 2220,
  '2010': 2079,
  '2011': 2053,
  '2012': 2034,
  '2013': 2078,
  '2014': 1979,
  '2015': 1750,
  '2016': 1735,
  'State': 'Vermont',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06db')},
 {'1978': '430',
  '1979': 420,
  '1980': 464,
  '1981': 519,
  '1982': 582,
  '1983': 488,
  '1984': 488,
  '1985': 660,
  '1986': 686,
  '1987': 745,
  '1988': 792,
  '1989': 869,
  '1990': 1013,
  '1991': 1081,
  '1992': 1208,
  '1993': 1175,
  '1994': 1252,
  '1995': 1235,
  '1996': 1087,
  '1997': 1217,
  '1998': 1421,
  '1999': 1477,
  '2000': 1617,
  '2001': 1646,
  '2002': 1731,
  '2003': 1809,
  '2004': 1825,
  '2005': 1926,
  '2006': 2058,
  '2007': 1998,
  '2008': 1998,
  '2009': 2065,
  '2010': 1930,
  '2011': 1905,
  '2012': 1907,
  '2013': 1924,
  '2014': 1823,
  '2015': 1600,
  '2016': 1600,
  'State': 'Vermont',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06dc')},
 {'1978': '11',
  '1979': 11,
  '1980': 16,
  '1981': 15,
  '1982': 17,
  '1983': 9,
  '1984': 13,
  '1985': 17,
  '1986': 11,
  '1987': 14,
  '1988': 28,
  '1989': 36,
  '1990': 36,
  '1991': 37,
  '1992': 46,
  '1993': 48,
  '1994': 49,
  '1995': 44,
  '1996': 32,
  '1997': 53,
  '1998': 52,
  '1999': 59,
  '2000': 80,
  '2001': 95,
  '2002': 132,
  '2003': 135,
  '2004': 143,
  '2005': 152,
  '2006': 157,
  '2007': 118,
  '2008': 118,
  '2009': 155,
  '2010': 149,
  '2011': 148,
  '2012': 127,
  '2013': 154,
  '2014': 156,
  '2015': 150,
  '2016': 135,
  'State': 'Vermont',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06dd')},
 {'1978': '8344',
  '1979': 8449,
  '1980': 8920,
  '1981': 9388,
  '1982': 10079,
  '1983': 10093,
  '1984': 10839,
  '1985': 12073,
  '1986': 12930,
  '1987': 13321,
  '1988': 14184,
  '1989': 16477,
  '1990': 17593,
  '1991': 19829,
  '1992': 21199,
  '1993': 22850,
  '1994': 26968,
  '1995': 27415,
  '1996': 27655,
  '1997': 28385,
  '1998': 30276,
  '1999': 29789,
  '2000': 30168,
  '2001': 31662,
  '2002': 34973,
  '2003': 35067,
  '2004': 35564,
  '2005': 35344,
  '2006': 36688,
  '2007': 37984,
  '2008': 38216,
  '2009': 38059,
  '2010': 37638,
  '2011': 38130,
  '2012': 37044,
  '2013': 36982,
  '2014': 37544,
  '2015': 38403,
  '2016': 37813,
  'State': 'Virginia',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06de')},
 {'1978': '7985',
  '1979': 8148,
  '1980': 8617,
  '1981': 9040,
  '1982': 9715,
  '1983': 9712,
  '1984': 10406,
  '1985': 11604,
  '1986': 12442,
  '1987': 12822,
  '1988': 13596,
  '1989': 15683,
  '1990': 16666,
  '1991': 18789,
  '1992': 20036,
  '1993': 21631,
  '1994': 25403,
  '1995': 25756,
  '1996': 25968,
  '1997': 26675,
  '1998': 28419,
  '1999': 27778,
  '2000': 28109,
  '2001': 29422,
  '2002': 32332,
  '2003': 32386,
  '2004': 32858,
  '2005': 32676,
  '2006': 33795,
  '2007': 35055,
  '2008': 35249,
  '2009': 35156,
  '2010': 34790,
  '2011': 35321,
  '2012': 34150,
  '2013': 34133,
  '2014': 34529,
  '2015': 35167,
  '2016': 34704,
  'State': 'Virginia',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06df')},
 {'1978': '359',
  '1979': 301,
  '1980': 303,
  '1981': 348,
  '1982': 364,
  '1983': 381,
  '1984': 433,
  '1985': 469,
  '1986': 488,
  '1987': 499,
  '1988': 588,
  '1989': 794,
  '1990': 927,
  '1991': 1040,
  '1992': 1163,
  '1993': 1219,
  '1994': 1565,
  '1995': 1659,
  '1996': 1687,
  '1997': 1710,
  '1998': 1857,
  '1999': 2011,
  '2000': 2059,
  '2001': 2240,
  '2002': 2641,
  '2003': 2681,
  '2004': 2706,
  '2005': 2668,
  '2006': 2893,
  '2007': 2929,
  '2008': 2967,
  '2009': 2903,
  '2010': 2848,
  '2011': 2809,
  '2012': 2894,
  '2013': 2849,
  '2014': 3015,
  '2015': 3236,
  '2016': 3109,
  'State': 'Virginia',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06e0')},
 {'1978': '4487',
  '1979': 4342,
  '1980': 4399,
  '1981': 5336,
  '1982': 6264,
  '1983': 6658,
  '1984': 6821,
  '1985': 6919,
  '1986': 6603,
  '1987': 6131,
  '1988': 5816,
  '1989': 6928,
  '1990': 7995,
  '1991': 9156,
  '1992': 9959,
  '1993': 10419,
  '1994': 10833,
  '1995': 11608,
  '1996': 12527,
  '1997': 13214,
  '1998': 14161,
  '1999': 14590,
  '2000': 14915,
  '2001': 15159,
  '2002': 16062,
  '2003': 16148,
  '2004': 16614,
  '2005': 17382,
  '2006': 17561,
  '2007': 17772,
  '2008': 17926,
  '2009': 18233,
  '2010': 18235,
  '2011': 17847,
  '2012': 17271,
  '2013': 17984,
  '2014': 18120,
  '2015': 18284,
  '2016': 19104,
  'State': 'Washington',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06e1')},
 {'1978': '4251',
  '1979': 4137,
  '1980': 4209,
  '1981': 5124,
  '1982': 6018,
  '1983': 6416,
  '1984': 6567,
  '1985': 6689,
  '1986': 6381,
  '1987': 5911,
  '1988': 5567,
  '1989': 6597,
  '1990': 7560,
  '1991': 8617,
  '1992': 9341,
  '1993': 9753,
  '1994': 10135,
  '1995': 10815,
  '1996': 11607,
  '1997': 12290,
  '1998': 13143,
  '1999': 13479,
  '2000': 13850,
  '2001': 14080,
  '2002': 14808,
  '2003': 14860,
  '2004': 15284,
  '2005': 15927,
  '2006': 16065,
  '2007': 16258,
  '2008': 16522,
  '2009': 16836,
  '2010': 16808,
  '2011': 16452,
  '2012': 15934,
  '2013': 16535,
  '2014': 16666,
  '2015': 16829,
  '2016': 17446,
  'State': 'Washington',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06e2')},
 {'1978': '236',
  '1979': 205,
  '1980': 190,
  '1981': 212,
  '1982': 246,
  '1983': 242,
  '1984': 254,
  '1985': 230,
  '1986': 222,
  '1987': 220,
  '1988': 249,
  '1989': 331,
  '1990': 435,
  '1991': 539,
  '1992': 618,
  '1993': 666,
  '1994': 698,
  '1995': 793,
  '1996': 920,
  '1997': 924,
  '1998': 1018,
  '1999': 1111,
  '2000': 1065,
  '2001': 1079,
  '2002': 1254,
  '2003': 1288,
  '2004': 1330,
  '2005': 1455,
  '2006': 1496,
  '2007': 1514,
  '2008': 1404,
  '2009': 1397,
  '2010': 1427,
  '2011': 1395,
  '2012': 1337,
  '2013': 1449,
  '2014': 1454,
  '2015': 1455,
  '2016': 1658,
  'State': 'Washington',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06e3')},
 {'1978': '1237',
  '1979': 1251,
  '1980': 1257,
  '1981': 1565,
  '1982': 1547,
  '1983': 1611,
  '1984': 1579,
  '1985': 1725,
  '1986': 1472,
  '1987': 1449,
  '1988': 1455,
  '1989': 1536,
  '1990': 1565,
  '1991': 1502,
  '1992': 1674,
  '1993': 1805,
  '1994': 2332,
  '1995': 2512,
  '1996': 2749,
  '1997': 3148,
  '1998': 3478,
  '1999': 3532,
  '2000': 3856,
  '2001': 4215,
  '2002': 4544,
  '2003': 4758,
  '2004': 5067,
  '2005': 5312,
  '2006': 5733,
  '2007': 6056,
  '2008': 6059,
  '2009': 6367,
  '2010': 6681,

  '2011': 6826,
  '2012': 7070,
  '2013': 6824,
  '2014': 6896,
  '2015': 7118,
  '2016': 7162,
  'State': 'Virginia',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06e4')},
 {'1978': '1208',
  '1979': 1218,
  '1980': 1227,
  '1981': 1528,
  '1982': 1500,
  '1983': 1553,
  '1984': 1528,
  '1985': 1658,
  '1986': 1405,
  '1987': 1380,
  '1988': 1389,
  '1989': 1463,
  '1990': 1489,
  '1991': 1432,
  '1992': 1594,
  '1993': 1726,
  '1994': 2241,
  '1995': 2383,
  '1996': 2600,
  '1997': 2962,
  '1998': 3267,
  '1999': 3293,
  '2000': 3553,
  '2001': 3869,
  '2002': 4182,
  '2003': 4353,
  '2004': 4608,
  '2005': 4832,
  '2006': 5159,
  '2007': 5422,
  '2008': 5411,
  '2009': 5683,
  '2010': 5956,
  '2011': 6074,
  '2012': 6265,
  '2013': 6016,
  '2014': 6065,
  '2015': 6253,
  '2016': 6286,
  'State': 'Virginia',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06e5')},
 {'1978': '29',
  '1979': 33,
  '1980': 30,
  '1981': 37,
  '1982': 47,
  '1983': 58,
  '1984': 51,
  '1985': 67,
  '1986': 67,
  '1987': 69,
  '1988': 66,
  '1989': 73,
  '1990': 76,
  '1991': 70,
  '1992': 80,
  '1993': 79,
  '1994': 91,
  '1995': 129,
  '1996': 149,
  '1997': 186,
  '1998': 211,
  '1999': 239,
  '2000': 303,
  '2001': 346,
  '2002': 362,
  '2003': 405,
  '2004': 459,
  '2005': 480,
  '2006': 574,
  '2007': 634,
  '2008': 648,
  '2009': 684,
  '2010': 725,
  '2011': 752,
  '2012': 805,
  '2013': 808,
  '2014': 831,
  '2015': 865,
  '2016': 876,
  'State': 'Virginia',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06e6')},
 {'1978': '3432',
  '1979': 3677,
  '1980': 3980,
  '1981': 4385,
  '1982': 4714,
  '1983': 4845,
  '1984': 4974,
  '1985': 5425,
  '1986': 5736,
  '1987': 6143,
  '1988': 6353,
  '1989': 6788,
  '1990': 7465,
  '1991': 7854,
  '1992': 8191,
  '1993': 8781,
  '1994': 10022,
  '1995': 11199,
  '1996': 12991,
  '1997': 16280,
  '1998': 18403,
  '1999': 20390,
  '2000': 20754,
  '2001': 21495,
  '2002': 22113,
  '2003': 22604,
  '2004': 22959,
  '2005': 22697,
  '2006': 23415,
  '2007': 23743,
  '2008': 23379,
  '2009': 23165,
  '2010': 22729,
  '2011': 22657,
  '2012': 22600,
  '2013': 22471,
  '2014': 22597,
  '2015': 22975,
  '2016': 23377,
  'State': 'Wisconsin',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06e7')},
 {'1978': '3285',
  '1979': 3532,
  '1980': 3826,
  '1981': 4216,
  '1982': 4517,
  '1983': 4632,
  '1984': 4747,
  '1985': 5174,
  '1986': 5451,
  '1987': 5844,
  '1988': 6071,
  '1989': 6485,
  '1990': 7117,
  '1991': 7506,
  '1992': 7855,
  '1993': 8394,
  '1994': 9610,
  '1995': 10697,
  '1996': 12346,
  '1997': 15292,
  '1998': 17235,
  '1999': 19007,
  '2000': 19387,
  '2001': 20192,
  '2002': 20757,
  '2003': 21199,
  '2004': 21572,
  '2005': 21348,
  '2006': 21991,
  '2007': 22216,
  '2008': 22022,
  '2009': 21859,
  '2010': 21465,
  '2011': 21472,
  '2012': 21375,
  '2013': 21232,
  '2014': 21219,
  '2015': 21567,
  '2016': 21889,
  'State': 'Wisconsin',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06e8')},
 {'1978': '147',
  '1979': 145,
  '1980': 154,
  '1981': 169,
  '1982': 197,
  '1983': 213,
  '1984': 227,
  '1985': 251,
  '1986': 285,
  '1987': 299,
  '1988': 282,
  '1989': 303,
  '1990': 348,
  '1991': 348,
  '1992': 336,
  '1993': 387,
  '1994': 412,
  '1995': 502,
  '1996': 645,
  '1997': 988,
  '1998': 1168,
  '1999': 1383,
  '2000': 1367,
  '2001': 1303,
  '2002': 1356,
  '2003': 1405,
  '2004': 1387,
  '2005': 1349,
  '2006': 1424,
  '2007': 1527,
  '2008': 1357,
  '2009': 1306,
  '2010': 1264,
  '2011': 1185,
  '2012': 1225,
  '2013': 1239,
  '2014': 1378,
  '2015': 1408,
  '2016': 1488,
  'State': 'Wisconsin',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06e9')},
 {'1978': '433',
  '1979': 504,
  '1980': 534,
  '1981': 556,
  '1982': 702,
  '1983': 721,
  '1984': 724,
  '1985': 762,
  '1986': 861,
  '1987': 916,
  '1988': 945,
  '1989': 1026,
  '1990': 1110,
  '1991': 1099,
  '1992': 1063,
  '1993': 1129,
  '1994': 1217,
  '1995': 1395,
  '1996': 1477,
  '1997': 1549,
  '1998': 1571,
  '1999': 1710,
  '2000': 1680,
  '2001': 1684,
  '2002': 1737,
  '2003': 1872,
  '2004': 1980,
  '2005': 2047,
  '2006': 2114,
  '2007': 2084,
  '2008': 2084,
  '2009': 2075,
  '2010': 2112,
  '2011': 2183,
  '2012': 2204,
  '2013': 2310,
  '2014': 2383,
  '2015': 2424,
  '2016': 2374,
  'State': 'Wyoming',
  'Total/Sex': 'Total',
  '_id': ObjectId('5d7482e5e743752d0e2d06ea')},
 {'1978': '414',
  '1979': 474,
  '1980': 505,
  '1981': 532,
  '1982': 674,
  '1983': 688,
  '1984': 685,
  '1985': 716,
  '1986': 810,
  '1987': 870,
  '1988': 880,
  '1989': 943,
  '1990': 1022,
  '1991': 1042,
  '1992': 999,
  '1993': 1063,
  '1994': 1135,
  '1995': 1289,
  '1996': 1365,
  '1997': 1413,
  '1998': 1440,
  '1999': 1571,
  '2000': 1524,
  '2001': 1549,
  '2002': 1570,
  '2003': 1697,
  '2004': 1770,
  '2005': 1825,
  '2006': 1871,
  '2007': 1838,
  '2008': 1876,
  '2009': 1861,
  '2010': 1881,
  '2011': 1944,
  '2012': 1966,
  '2013': 2050,
  '2014': 2106,
  '2015': 2157,
  '2016': 2088,
  'State': 'Wyoming',
  'Total/Sex': 'Male',
  '_id': ObjectId('5d7482e5e743752d0e2d06eb')},
 {'1978': '19',
  '1979': 30,
  '1980': 29,
  '1981': 24,
  '1982': 28,
  '1983': 33,
  '1984': 39,
  '1985': 46,
  '1986': 51,
  '1987': 46,
  '1988': 65,
  '1989': 83,
  '1990': 88,
  '1991': 57,
  '1992': 64,
  '1993': 66,
  '1994': 82,
  '1995': 106,
  '1996': 112,
  '1997': 136,
  '1998': 131,
  '1999': 139,
  '2000': 156,
  '2001': 135,
  '2002': 167,
  '2003': 175,
  '2004': 210,
  '2005': 222,
  '2006': 243,
  '2007': 246,
  '2008': 208,
  '2009': 214,
  '2010': 231,
  '2011': 239,
  '2012': 238,
  '2013': 260,
  '2014': 277,
  '2015': 267,
  '2016': 286,
  'State': 'Wyoming',
  'Total/Sex': 'Female',
  '_id': ObjectId('5d7482e5e743752d0e2d06ec')}]